begin;
set local client_min_messages=error;
\ir fixtures/product_spec_binding_prerequisites.sql
select no_plan();
create temp table rows_cases(case_data jsonb);
select set_config('request.jwt.claims','{}',true);
select set_config('request.jwt.claim.sub','',true);
insert into public.tenants(id,shop_name) values
 ('99ba0000-0000-4000-8000-000000000001','Spec A'),('99ba0000-0000-4000-8000-000000000002','Spec B');
insert into auth.users(id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select id::uuid,'authenticated','authenticated',email,'',now(),'{}',
 jsonb_build_object('account_type','public_store_customer','customer_tenant_id',tenant),now(),now()
from (values
 ('99ba0000-0000-4000-8000-000000000091','spec-a@example.invalid','99ba0000-0000-4000-8000-000000000001'),
 ('99ba0000-0000-4000-8000-000000000092','spec-b@example.invalid','99ba0000-0000-4000-8000-000000000002')) a(id,email,tenant);
delete from public.user_profiles where user_id in ('99ba0000-0000-4000-8000-000000000091','99ba0000-0000-4000-8000-000000000092');
insert into public.user_profiles(user_id,tenant_id,role) values
 ('99ba0000-0000-4000-8000-000000000091','99ba0000-0000-4000-8000-000000000001','admin'),
 ('99ba0000-0000-4000-8000-000000000092','99ba0000-0000-4000-8000-000000000002','admin');
select set_config('request.jwt.claims','{"sub":"99ba0000-0000-4000-8000-000000000091","role":"authenticated"}',true);
select set_config('request.jwt.claim.sub','99ba0000-0000-4000-8000-000000000091',true);
insert into public.product_categories(id,tenant_id,name,full_path) values
 ('99ba0000-0000-4000-8000-000000000010','99ba0000-0000-4000-8000-000000000001','Spec chains','Spec chains'),
 ('99ba0000-0000-4000-8000-000000000011','99ba0000-0000-4000-8000-000000000002','Other chains','Other chains');
insert into public.category_tech_mappings(tenant_id,category_id,technical_family,template_id,status)
select '99ba0000-0000-4000-8000-000000000001','99ba0000-0000-4000-8000-000000000010','chain',id,'active'
from public.spec_templates where key='chain' and tenant_id is null;


insert into public.products(id,tenant_id,name,sku,category_id,price,cost,is_active)
values('99ba0000-0000-4000-8000-000000000020','99ba0000-0000-4000-8000-000000000001','Legacy boundary','SPEC-LEGACY-BOUNDARY','99ba0000-0000-4000-8000-000000000010',100,50,true);
insert into rows_cases values($fixture${"id": "separate_configurations", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": true, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "decimal_precision", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "9007199254740993.1", "width_max": "9007199254740993.2", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": true, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "canonical_decimal", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "4.00e1", "width_max": "062.000", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": true, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "partial_is_unknown", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": true, "missing_required": 1}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "json_number_is_not_exact", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": 28, "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "numeric_string_not_boolean", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": "false"}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "token_is_literal", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "001", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "foreign_cell", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": false, "chain_speeds": ["8"]}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "array_is_not_one_cell", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": ["584", "622"], "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "reversed_within_row", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "48", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "decimal_reversal_beyond_ieee", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "9007199254740993.2", "width_max": "9007199254740993.1", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "duplicate_position", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "1.000", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "duplicate_id", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-a", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "id_newline", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b\n", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "source_credentials", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://user:pass@example.test/source"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "source_duplicate", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/source", "https://example.test/source"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "source_invalid_escape", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/%0X"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "number_comma_wire", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28,5", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "number_space_wire", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": " 28", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "negative_dimension", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "-1", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "fractional_count", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1.5", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "nonfinite", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "Infinity", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "empty_row", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "null_is_omission_only", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": null, "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "future_version", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 2, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "extra_envelope_field", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": "01", "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}], "compatible": true}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "nested_object", "schema": {"version": 1, "columns": [{"key": "bsd", "label": "Asiento nominal", "type": "integer", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_min", "label": "Ancho mínimo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "width_max", "label": "Ancho máximo", "type": "decimal", "unit": "mm", "required": true, "validation": {"positive": true}}, {"key": "position", "label": "Posición", "type": "integer", "validation": {"positive": true}}, {"key": "token", "label": "Modelo", "type": "token", "allowed_values": ["01", "1", "A", "B"]}, {"key": "adapter", "label": "Adaptador", "type": "boolean"}, {"key": "manual", "label": "Manual", "type": "url"}], "ordered_pairs": [["width_min", "width_max"]], "unique_by": [["position"]]}, "value": {"schema_version": 1, "rows": [{"id": "row-a", "values": {"bsd": "622", "width_min": "28", "width_max": "47", "position": "1", "token": {"value": "01"}, "adapter": false}, "sources": ["https://example.test/model-a"]}, {"id": "row-b", "values": {"bsd": "584", "width_min": "40", "width_max": "62", "position": "2", "token": "1"}, "sources": ["https://example.test/model-b"]}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "zero_tiny_exponent", "schema": {"version": 1, "columns": [{"key": "length", "label": "Longitud", "type": "decimal"}]}, "value": {"schema_version": 1, "rows": [{"id": "x", "values": {"length": "0e-9999999999999999"}, "sources": []}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "zero_input_scale_limit", "schema": {"version": 1, "columns": [{"key": "length", "label": "Longitud", "type": "decimal"}]}, "value": {"schema_version": 1, "rows": [{"id": "x", "values": {"length": "0e-16383"}, "sources": []}]}, "valid": true, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "zero_input_scale_overflow", "schema": {"version": 1, "columns": [{"key": "length", "label": "Longitud", "type": "decimal"}]}, "value": {"schema_version": 1, "rows": [{"id": "x", "values": {"length": "0e-16384"}, "sources": []}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "zero_large_exponent", "schema": {"version": 1, "columns": [{"key": "length", "label": "Longitud", "type": "decimal"}]}, "value": {"schema_version": 1, "rows": [{"id": "x", "values": {"length": "0e131073"}, "sources": []}]}, "valid": true, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "zero_exponent_limit", "schema": {"version": 1, "columns": [{"key": "length", "label": "Longitud", "type": "decimal"}]}, "value": {"schema_version": 1, "rows": [{"id": "x", "values": {"length": "0e1073741823"}, "sources": []}]}, "valid": true, "missing_required": 0}$fixture$::jsonb);
insert into rows_cases values($fixture${"id": "zero_exponent_overflow", "schema": {"version": 1, "columns": [{"key": "length", "label": "Longitud", "type": "decimal"}]}, "value": {"schema_version": 1, "rows": [{"id": "x", "values": {"length": "0e1073741824"}, "sources": []}]}, "valid": false, "missing_required": 0}$fixture$::jsonb);
-- Shared SQL/Dart shape cases, with no manufacturer claims.
create function pg_temp.validate_row_fixture(p_value jsonb) returns jsonb language sql as $$
 select public.spec_rows_validate_internal_v1((select case_data->'schema' from rows_cases limit 1),p_value)
$$;
select case when (case_data->>'valid')::boolean
 then lives_ok(format('select public.spec_rows_validate_internal_v1(%L::jsonb,%L::jsonb)',case_data->'schema',case_data->'value'),case_data->>'id')
 else throws_ok(format('select public.spec_rows_validate_internal_v1(%L::jsonb,%L::jsonb)',case_data->'schema',case_data->'value'),'23514',null,case_data->>'id') end
from rows_cases;
select is(pg_temp.validate_row_fixture((select case_data->'value' from rows_cases where case_data->>'id'='canonical_decimal'))#>>'{rows,1,values,width_min}','40','canonical exact decimal readback');

insert into public.spec_definitions(id,key,label,data_type,validation_rules,is_filterable,is_customer_visible)
select '99ba0000-0000-4000-8000-000000000051','rows_fixture','Configuraciones','json',
 jsonb_build_object('rows_schema',case_data->'schema'),false,true from rows_cases limit 1;
insert into public.spec_templates(id,key,name,technical_family,form_contract)
values('99ba0000-0000-4000-8000-000000000050','rows_fixture','Configuraciones fixture','fixture','{"roles":{"rows_fixture":"measurement"}}');
insert into public.spec_template_fields(template_id,spec_definition_id,section_key,sort_order)
values('99ba0000-0000-4000-8000-000000000050','99ba0000-0000-4000-8000-000000000051','measurement',1);
update public.products set spec_template_id='99ba0000-0000-4000-8000-000000000050',is_published=true,show_on_website=true
 where id='99ba0000-0000-4000-8000-000000000020';
create function pg_temp.row_payload(p_id text) returns jsonb language sql as $$
 select jsonb_build_object('99ba0000-0000-4000-8000-000000000051',jsonb_build_object('rows',case_data->'value'))
 from rows_cases where case_data->>'id'=p_id
$$;
create function pg_temp.save_rows(p_value jsonb,p_operation text) returns jsonb language sql as $$
 select public.save_product_with_specs_v1(
 '{"id":"99ba0000-0000-4000-8000-000000000020","name":"Legacy boundary","sku":"SPEC-LEGACY-BOUNDARY"}',false,
 '99ba0000-0000-4000-8000-000000000050',
 (select contract_version from public.spec_templates where id='99ba0000-0000-4000-8000-000000000050'),p_value,
 (select spec_revision from public.products where id='99ba0000-0000-4000-8000-000000000020'),null,p_operation,
 (select updated_at from public.products where id='99ba0000-0000-4000-8000-000000000020'))
$$;
grant select on rows_cases to authenticated;
grant execute on function pg_temp.row_payload(text),pg_temp.save_rows(jsonb,text) to authenticated;
set local role authenticated;
select lives_ok($$select pg_temp.save_rows(pg_temp.row_payload('decimal_precision'),'rows-save')$$,'authenticated aggregate writes paired exact observations');
select is(public.get_product_spec_snapshot_v1('99ba0000-0000-4000-8000-000000000020')#>>'{values,rows_fixture,rows,1,values,width_min}',
 '9007199254740993.1','snapshot keeps the exact value in its own row');
select is(public.get_product_spec_contexts_v1(array['99ba0000-0000-4000-8000-000000000020'::uuid])#>>'{99ba0000-0000-4000-8000-000000000020,rows_fixture,rows,0,values,adapter}',
 'false','context retains false and the row envelope');
select is(public.get_product_spec_typed_configurations_v1(array['99ba0000-0000-4000-8000-000000000020'::uuid])#>>'{99ba0000-0000-4000-8000-000000000020,fields,rows_fixture,value_type}',
 'rows','typed relation transport identifies rows rather than flattening them');
select throws_ok($$select pg_temp.save_rows(pg_temp.row_payload('reversed_within_row'),'rows-invalid')$$,'23514',null,'range reversal cannot partially update aggregate');
select is(public.get_product_spec_snapshot_v1('99ba0000-0000-4000-8000-000000000020')#>>'{values,rows_fixture,rows,1,values,width_min}',
 '9007199254740993.1','rejected aggregate preserves previous configurations');
select throws_ok($$select public.save_product_spec_facts_v1('99ba0000-0000-4000-8000-000000000020',array['99ba0000-0000-4000-8000-000000000051'::uuid],'{}')$$,'23514',null,'old writer cannot erase a structured field by omission');
select throws_ok($$insert into public.spec_facts(tenant_id,subject_type,subject_id,spec_definition_id,value_json)
 values('99ba0000-0000-4000-8000-000000000001','product','99ba0000-0000-4000-8000-000000000020','99ba0000-0000-4000-8000-000000000051',(select case_data->'value' from rows_cases limit 1))$$,'42501',null,'new column cannot bypass product commands');
reset role;
select is((select value_json#>>'{rows,1,values,width_min}' from public.product_spec_values where product_id='99ba0000-0000-4000-8000-000000000020' and spec_definition_id='99ba0000-0000-4000-8000-000000000051'),
 '9007199254740993.1','compatibility projection retains structured rows');
select ok((select display_value like '%9007199254740993.1%' and display_value not like '%schema_version%' from public.get_public_product_technical_specs('99ba0000-0000-4000-8000-000000000001','99ba0000-0000-4000-8000-000000000020') where spec_key='rows_fixture'),
 'storefront renders cells and units, not implementation JSON');
select throws_ok($$update public.spec_definitions set validation_rules='{}' where id='99ba0000-0000-4000-8000-000000000051'$$,'23514',null,'metadata cannot reinterpret populated rows as generic JSON');
select throws_ok($$update public.spec_facts set value_json=null,value_text='[{"bsd":622}]' where subject_id='99ba0000-0000-4000-8000-000000000020'$$,'23514',null,'structured values cannot move into a text fallback');
select ok(exists(select 1 from jsonb_array_elements(public.spec_validate_draft_internal_v1('99ba0000-0000-4000-8000-000000000050',jsonb_build_object('rows_fixture',(select case_data->'value' from rows_cases where case_data->>'id'='partial_is_unknown')))) i where i->>'code'='row_incomplete' and i->>'blocking'='false'),'partial configuration is reported without inventing negative compatibility');
-- A reference's meaning is frozen even before any product adopts it.
insert into public.spec_definitions(id,key,label,data_type,validation_rules,is_filterable,is_customer_visible)
values ('99bb0000-0000-4000-8000-000000000051','rows_review_reference_schema','Reference unit review','json',
 '{"rows_schema":{"version":1,"columns":[{"key":"length","label":"Length","type":"decimal","unit":"mm"}]}}',false,true);
insert into public.product_spec_references(id,technical_family,brand,model,label,fact_values,sources,reviewed_on)
values ('rows-review-reference-schema-v1','fixture','Review','Rows','Rows review',
 '{"99bb0000-0000-4000-8000-000000000051":{"rows":{"schema_version":1,"rows":[{"id":"x","values":{"length":"10"},"sources":["https://example.test/manual"]}]}}}',
 '["https://example.test/manual"]','2026-09-06');
select throws_ok($$update public.spec_definitions set validation_rules=jsonb_set(validation_rules,'{rows_schema,columns,0,unit}','"in"')
 where id='99bb0000-0000-4000-8000-000000000051'$$,'23514',null,'unused reference prevents reinterpretation of units');
select is(public.spec_rows_display_internal_v1(d.validation_rules->'rows_schema',r.fact_values->d.id::text->'rows'),
 'Length: 10 mm','reference retains original meaning after rejected metadata edit')
 from public.spec_definitions d cross join public.product_spec_references r
 where d.id='99bb0000-0000-4000-8000-000000000051' and r.id='rows-review-reference-schema-v1';
select throws_ok($$delete from public.spec_definitions where id='99bb0000-0000-4000-8000-000000000051'$$,
 '23514',null,'unused reference prevents deletion of its row schema');
select throws_ok($$insert into public.product_spec_references(id,technical_family,brand,model,label,fact_values,sources,reviewed_on)
 select 'rows-review-foreign-source','fixture','Review','Other','Foreign source',fact_values,'["https://example.test/other"]','2026-09-06'
 from public.product_spec_references where id='rows-review-reference-schema-v1'$$,
 '23514',null,'row sources must belong to their manufacturer reference');
select throws_ok($$insert into public.product_spec_references(id,technical_family,brand,model,label,fact_values,sources,reviewed_on)
 select 'rows-review-mixed-value','fixture','Review','Other','Mixed value',
 jsonb_set(fact_values,'{99bb0000-0000-4000-8000-000000000051,text}','"extra"'),sources,'2026-09-06'
 from public.product_spec_references where id='rows-review-reference-schema-v1'$$,
 '23514',null,'reference cannot silently discard a mixed scalar alongside rows');
-- Scalar numeric transport is exact at the database boundary as well.
insert into public.spec_definitions(id,key,label,data_type,validation_rules)
values('99ba0000-0000-4000-8000-000000000052','exact_scalar_fixture','Exact scalar','number','{"positive":true}');
insert into public.spec_template_fields(template_id,spec_definition_id,section_key,sort_order)
values('99ba0000-0000-4000-8000-000000000050','99ba0000-0000-4000-8000-000000000052','measurement',2);
select lives_ok($$select pg_temp.save_rows(pg_temp.row_payload('decimal_precision') ||
 '{"99ba0000-0000-4000-8000-000000000052":{"number":"9007199254740993.1"}}','rows-scalar')$$,
 'aggregate accepts exact decimal string beside row configurations');
select is(public.get_product_spec_typed_configurations_v1(array['99ba0000-0000-4000-8000-000000000020'::uuid])
 #>>'{99ba0000-0000-4000-8000-000000000020,fields,exact_scalar_fixture,value}',
 '9007199254740993.1','typed transport preserves scalar numeric precision');
select is(jsonb_typeof(public.get_product_spec_typed_configurations_v1(array['99ba0000-0000-4000-8000-000000000020'::uuid])
 #>'{99ba0000-0000-4000-8000-000000000020,fields,exact_scalar_fixture,value}'),
 'string','typed scalar is not sent through an IEEE JSON number');

-- Reclassification preserves rows as unassigned history by exact definition.
select public.assign_product_spec_template_v1('99ba0000-0000-4000-8000-000000000020',
 (select id from public.spec_templates where key='chain' and tenant_id is null),
 (select spec_revision from public.products where id='99ba0000-0000-4000-8000-000000000020'),
 (select updated_at from public.products where id='99ba0000-0000-4000-8000-000000000020'),'rows-reclassify','synthetic reclassification');
select ok(not(public.get_product_spec_contexts_v1(array['99ba0000-0000-4000-8000-000000000020'::uuid])->'99ba0000-0000-4000-8000-000000000020' ? 'rows_fixture'),'reclassified rows do not become active criteria');
select is((select f#>>'{value,rows,1,values,width_min}' from jsonb_array_elements(public.get_product_spec_snapshot_v1('99ba0000-0000-4000-8000-000000000020')->'unassigned_facts') f where f->>'definition_id'='99ba0000-0000-4000-8000-000000000051'),
 '9007199254740993.1','reclassified row remains inspectable in history');
select is((select f#>>'{rows_schema,columns,0,unit}' from jsonb_array_elements(public.get_product_spec_snapshot_v1('99ba0000-0000-4000-8000-000000000020')->'unassigned_facts') f where f->>'definition_id'='99ba0000-0000-4000-8000-000000000051'),'mm','history retains schema labels and units for readable configurations');
select set_config('request.jwt.claim.sub','99ba0000-0000-4000-8000-000000000092',true);
select is(public.get_product_spec_typed_configurations_v1(array['99ba0000-0000-4000-8000-000000000020'::uuid]),'{}'::jsonb,'typed reader excludes another tenant');
select ok(not has_function_privilege('authenticated','spec_rows_validate_internal_v1(jsonb,jsonb)','execute') and not has_function_privilege('anon','get_product_spec_typed_configurations_v1(uuid[])','execute'),'helpers private, typed reader authenticated only');
select * from finish();
rollback;
