name: vinabike_erp
description: A modular ERP system for bikeshop management built with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Navigation
  go_router: ^14.2.0
  
  # State Management
  provider: ^6.1.2
  
  # Supabase
  supabase_flutter: ^2.6.0
  
  # Deep linking for OAuth
  app_links: ^6.3.2
  
  # HTTP & Networking
  http: ^1.2.1
  
  # Images
  cached_network_image: ^3.3.1
  image_picker: ^1.1.0
  cross_file: ^0.3.4+2
  file_picker: ^8.1.6
  
  # Localization
  intl: ^0.20.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_colorpicker: ^1.1.0
  fl_chart: ^0.66.2
  
  # Utilities
  uuid: ^4.4.0
  path_provider: ^2.1.3
  path: ^1.9.1
  mime: ^2.0.0
  shared_preferences: ^2.2.3
  csv: ^5.1.1
  excel: ^4.0.2
  file_saver: ^0.2.8
  
  # Bluetooth & Barcode Scanning
  flutter_blue_plus: ^1.32.12
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/block_marketplace/