import 'package:flutter/foundation.dart';

/// Task type enumeration for mechanic job tasks
enum TaskType {
  diagnostic('diagnostic', 'Diagnóstico'),
  installPart('install_part', 'Instalar Repuesto'),
  performService('perform_service', 'Realizar Servicio'),
  qualityCheck('quality_check', 'Control de Calidad'),
  testRide('test_ride', 'Prueba de Rodaje'),
  cleanup('cleanup', 'Limpieza/Pulido'),
  general('general', 'Tarea General');

  final String value;
  final String displayName;

  const TaskType(this.value, this.displayName);

  static TaskType fromString(String value) {
    return TaskType.values.firstWhere(
      (e) => e.value == value,
      orElse: () => TaskType.general,
    );
  }
}

/// Task status enumeration
enum TaskStatus {
  pending('pending', 'Pendiente'),
  inProgress('in_progress', 'En Progreso'),
  completed('completed', 'Completado'),
  skipped('skipped', 'Omitido'),
  blocked('blocked', 'Bloqueado');

  final String value;
  final String displayName;

  const TaskStatus(this.value, this.displayName);

  static TaskStatus fromString(String value) {
    return TaskStatus.values.firstWhere(
      (e) => e.value == value,
      orElse: () => TaskStatus.pending,
    );
  }
}

/// Task priority enumeration
enum TaskPriority {
  urgent('urgent', 'Urgente'),
  high('high', 'Alta'),
  normal('normal', 'Normal'),
  low('low', 'Baja');

  final String value;
  final String displayName;

  const TaskPriority(this.value, this.displayName);

  static TaskPriority fromString(String value) {
    return TaskPriority.values.firstWhere(
      (e) => e.value == value,
      orElse: () => TaskPriority.normal,
    );
  }
}

/// Model representing a task in a mechanic job (pega)
/// Tasks are linked to specific parts/services and sync with pega status
@immutable
class MechanicJobTask {
  final String id;
  final String tenantId;
  final String jobId;
  final String? jobItemId;
  final String? jobLaborId;
  final TaskType taskType;
  final String title;
  final String? description;
  final TaskStatus status;
  final TaskPriority priority;
  final String? assignedTo;
  final String? assignedTechnicianName;
  final int? estimatedDurationMinutes;
  final int? actualDurationMinutes;
  final DateTime? startedAt;
  final DateTime? completedAt;
  final bool isAutoGenerated;
  final String? completedBy;
  final String? completedByName;
  final String? notes;
  final int displayOrder;
  final DateTime createdAt;
  final DateTime updatedAt;

  const MechanicJobTask({
    required this.id,
    required this.tenantId,
    required this.jobId,
    this.jobItemId,
    this.jobLaborId,
    required this.taskType,
    required this.title,
    this.description,
    required this.status,
    required this.priority,
    this.assignedTo,
    this.assignedTechnicianName,
    this.estimatedDurationMinutes,
    this.actualDurationMinutes,
    this.startedAt,
    this.completedAt,
    required this.isAutoGenerated,
    this.completedBy,
    this.completedByName,
    this.notes,
    required this.displayOrder,
    required this.createdAt,
    required this.updatedAt,
  });

  factory MechanicJobTask.fromJson(Map<String, dynamic> json) {
    return MechanicJobTask(
      id: json['id'] as String,
      tenantId: json['tenant_id'] as String,
      jobId: json['job_id'] as String,
      jobItemId: json['job_item_id'] as String?,
      jobLaborId: json['job_labor_id'] as String?,
      taskType: TaskType.fromString(json['task_type'] as String),
      title: json['title'] as String,
      description: json['description'] as String?,
      status: TaskStatus.fromString(json['status'] as String),
      priority: TaskPriority.fromString(json['priority'] as String),
      assignedTo: json['assigned_to'] as String?,
      assignedTechnicianName: json['assigned_technician_name'] as String?,
      estimatedDurationMinutes: json['estimated_duration_minutes'] as int?,
      actualDurationMinutes: json['actual_duration_minutes'] as int?,
      startedAt: json['started_at'] != null
          ? DateTime.parse(json['started_at'] as String)
          : null,
      completedAt: json['completed_at'] != null
          ? DateTime.parse(json['completed_at'] as String)
          : null,
      isAutoGenerated: json['is_auto_generated'] as bool? ?? false,
      completedBy: json['completed_by'] as String?,
      completedByName: json['completed_by_name'] as String?,
      notes: json['notes'] as String?,
      displayOrder: json['display_order'] as int? ?? 0,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'tenant_id': tenantId,
      'job_id': jobId,
      if (jobItemId != null) 'job_item_id': jobItemId,
      if (jobLaborId != null) 'job_labor_id': jobLaborId,
      'task_type': taskType.value,
      'title': title,
      if (description != null) 'description': description,
      'status': status.value,
      'priority': priority.value,
      if (assignedTo != null) 'assigned_to': assignedTo,
      if (assignedTechnicianName != null)
        'assigned_technician_name': assignedTechnicianName,
      if (estimatedDurationMinutes != null)
        'estimated_duration_minutes': estimatedDurationMinutes,
      if (actualDurationMinutes != null)
        'actual_duration_minutes': actualDurationMinutes,
      if (startedAt != null) 'started_at': startedAt!.toIso8601String(),
      if (completedAt != null) 'completed_at': completedAt!.toIso8601String(),
      'is_auto_generated': isAutoGenerated,
      if (completedBy != null) 'completed_by': completedBy,
      if (completedByName != null) 'completed_by_name': completedByName,
      if (notes != null) 'notes': notes,
      'display_order': displayOrder,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  MechanicJobTask copyWith({
    String? id,
    String? tenantId,
    String? jobId,
    String? jobItemId,
    String? jobLaborId,
    TaskType? taskType,
    String? title,
    String? description,
    TaskStatus? status,
    TaskPriority? priority,
    String? assignedTo,
    String? assignedTechnicianName,
    int? estimatedDurationMinutes,
    int? actualDurationMinutes,
    DateTime? startedAt,
    DateTime? completedAt,
    bool? isAutoGenerated,
    String? completedBy,
    String? completedByName,
    String? notes,
    int? displayOrder,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return MechanicJobTask(
      id: id ?? this.id,
      tenantId: tenantId ?? this.tenantId,
      jobId: jobId ?? this.jobId,
      jobItemId: jobItemId ?? this.jobItemId,
      jobLaborId: jobLaborId ?? this.jobLaborId,
      taskType: taskType ?? this.taskType,
      title: title ?? this.title,
      description: description ?? this.description,
      status: status ?? this.status,
      priority: priority ?? this.priority,
      assignedTo: assignedTo ?? this.assignedTo,
      assignedTechnicianName:
          assignedTechnicianName ?? this.assignedTechnicianName,
      estimatedDurationMinutes:
          estimatedDurationMinutes ?? this.estimatedDurationMinutes,
      actualDurationMinutes:
          actualDurationMinutes ?? this.actualDurationMinutes,
      startedAt: startedAt ?? this.startedAt,
      completedAt: completedAt ?? this.completedAt,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      completedBy: completedBy ?? this.completedBy,
      completedByName: completedByName ?? this.completedByName,
      notes: notes ?? this.notes,
      displayOrder: displayOrder ?? this.displayOrder,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  /// Get estimated duration in human-readable format
  String get estimatedDurationFormatted {
    if (estimatedDurationMinutes == null) return 'Sin estimar';
    final hours = estimatedDurationMinutes! ~/ 60;
    final minutes = estimatedDurationMinutes! % 60;
    if (hours > 0 && minutes > 0) {
      return '$hours h $minutes min';
    } else if (hours > 0) {
      return '$hours h';
    } else {
      return '$minutes min';
    }
  }

  /// Get actual duration in human-readable format
  String? get actualDurationFormatted {
    if (actualDurationMinutes == null) return null;
    final hours = actualDurationMinutes! ~/ 60;
    final minutes = actualDurationMinutes! % 60;
    if (hours > 0 && minutes > 0) {
      return '$hours h $minutes min';
    } else if (hours > 0) {
      return '$hours h';
    } else {
      return '$minutes min';
    }
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is MechanicJobTask && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() {
    return 'MechanicJobTask(id: $id, title: $title, status: ${status.displayName}, priority: ${priority.displayName})';
  }
}

/// Task summary statistics for a job
@immutable
class TaskSummary {
  final int totalTasks;
  final int completed;
  final int inProgress;
  final int pending;
  final int blocked;
  final double completionPercentage;

  const TaskSummary({
    required this.totalTasks,
    required this.completed,
    required this.inProgress,
    required this.pending,
    required this.blocked,
    required this.completionPercentage,
  });

  factory TaskSummary.fromJson(Map<String, dynamic> json) {
    return TaskSummary(
      totalTasks: json['total_tasks'] as int? ?? 0,
      completed: json['completed'] as int? ?? 0,
      inProgress: json['in_progress'] as int? ?? 0,
      pending: json['pending'] as int? ?? 0,
      blocked: json['blocked'] as int? ?? 0,
      completionPercentage:
          (json['completion_percentage'] as num?)?.toDouble() ?? 0.0,
    );
  }

  factory TaskSummary.empty() {
    return const TaskSummary(
      totalTasks: 0,
      completed: 0,
      inProgress: 0,
      pending: 0,
      blocked: 0,
      completionPercentage: 0.0,
    );
  }

  bool get hasActiveTasks => totalTasks > 0;
  bool get isComplete => completed == totalTasks && totalTasks > 0;
  int get remainingTasks => totalTasks - completed;

  @override
  String toString() {
    return 'TaskSummary(total: $totalTasks, completed: $completed, ${completionPercentage.toStringAsFixed(1)}%)';
  }
}
