-- Read-only exact deployed contract; absent/drifted objects fail at SQL level.
with reviewed(signature,definition_md5) as(values
('mirror_facts_into_product_specs_internal_v1()','0441072aa7fee0cf927b9e09815423e3'),
('record_product_spec_reading_v1(uuid,text,jsonb,text,text)','49076ebef1568025b62ed51e48ae0442'),
('save_product_spec_facts_v1(uuid,uuid[],jsonb)','c7ae43770592d0ae1a9bcf1ca83a9735'),
('spec_validate_draft_internal_v1(uuid,jsonb,text,text,text,text)','1b9760ba2076900cb68b9afb627c5173'),
('spec_write_payload_internal_v2(uuid,uuid,jsonb,text)','8d1cd17f62155def6cd528baf82a4817')) select 1/case when count(*)=5 and bool_and(coalesce(md5(pg_get_functiondef(to_regprocedure(signature)))=definition_md5,false)) then 1 else 0 end function_contract_assertion from reviewed;
with reviewed as(select * from jsonb_to_recordset($policies$[{"cmd":"DELETE","qual":"false","roles":["anon","authenticated"],"tablename":"product_spec_values","permissive":"RESTRICTIVE","policyname":"product_spec_values_product_command_delete","with_check":null},{"cmd":"INSERT","qual":null,"roles":["anon","authenticated"],"tablename":"product_spec_values","permissive":"RESTRICTIVE","policyname":"product_spec_values_product_command_insert","with_check":"false"},{"cmd":"UPDATE","qual":"false","roles":["anon","authenticated"],"tablename":"product_spec_values","permissive":"RESTRICTIVE","policyname":"product_spec_values_product_command_update","with_check":"false"},{"cmd":"DELETE","qual":"(EXISTS ( SELECT 1\n   FROM spec_facts f\n  WHERE ((f.id = spec_fact_values.fact_id) AND (f.subject_type <> 'product'::text))))","roles":["anon","authenticated"],"tablename":"spec_fact_values","permissive":"RESTRICTIVE","policyname":"spec_fact_values_product_command_delete","with_check":null},{"cmd":"INSERT","qual":null,"roles":["anon","authenticated"],"tablename":"spec_fact_values","permissive":"RESTRICTIVE","policyname":"spec_fact_values_product_command_insert","with_check":"(EXISTS ( SELECT 1\n   FROM spec_facts f\n  WHERE ((f.id = spec_fact_values.fact_id) AND (f.subject_type <> 'product'::text))))"},{"cmd":"UPDATE","qual":"(EXISTS ( SELECT 1\n   FROM spec_facts f\n  WHERE ((f.id = spec_fact_values.fact_id) AND (f.subject_type <> 'product'::text))))","roles":["anon","authenticated"],"tablename":"spec_fact_values","permissive":"RESTRICTIVE","policyname":"spec_fact_values_product_command_update","with_check":"(EXISTS ( SELECT 1\n   FROM spec_facts f\n  WHERE ((f.id = spec_fact_values.fact_id) AND (f.subject_type <> 'product'::text))))"},{"cmd":"DELETE","qual":"(subject_type <> 'product'::text)","roles":["anon","authenticated"],"tablename":"spec_facts","permissive":"RESTRICTIVE","policyname":"spec_facts_product_command_delete","with_check":null},{"cmd":"INSERT","qual":null,"roles":["anon","authenticated"],"tablename":"spec_facts","permissive":"RESTRICTIVE","policyname":"spec_facts_product_command_insert","with_check":"(subject_type <> 'product'::text)"},{"cmd":"UPDATE","qual":"(subject_type <> 'product'::text)","roles":["anon","authenticated"],"tablename":"spec_facts","permissive":"RESTRICTIVE","policyname":"spec_facts_product_command_update","with_check":"(subject_type <> 'product'::text)"}]$policies$::jsonb) r(tablename text,policyname text,permissive text,roles name[],cmd text,qual text,with_check text)) select 1/case when count(p.policyname)=9 and bool_and(p.permissive=r.permissive and p.roles=r.roles and p.cmd=r.cmd and p.qual is not distinct from r.qual and p.with_check is not distinct from r.with_check) then 1 else 0 end restrictive_policies_assertion from reviewed r left join pg_policies p on p.schemaname='public' and p.tablename=r.tablename and p.policyname=r.policyname;
select 1/case when has_function_privilege('authenticated','save_product_spec_facts_v1(uuid,uuid[],jsonb)','EXECUTE') and not has_function_privilege('anon','save_product_spec_facts_v1(uuid,uuid[],jsonb)','EXECUTE') and not has_function_privilege('authenticated','spec_write_payload_internal_v2(uuid,uuid,jsonb,text)','EXECUTE') then 1 else 0 end command_permissions_assertion;
