// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu00oqAuIPBLlBBHziNCKMMrgPy7u6wQ4',
    appId: '1:452996097799:web:6af010266020d8ee7e47a2',
    messagingSenderId: '452996097799',
    projectId: 'project-vinabike',
    authDomain: 'project-vinabike.firebaseapp.com',
    storageBucket: 'project-vinabike.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu00oqAuIPBLlBBHziNCKMMrgPy7u6wQ4',
    appId: '1:452996097799:web:859d3944359a5fd27e47a2',
    messagingSenderId: '452996097799',
    projectId: 'project-vinabike',
    authDomain: 'project-vinabike.firebaseapp.com',
    storageBucket: 'project-vinabike.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5q_tMOACwvvLt6d0UEISpEwaTBh-0zKE',
    appId: '1:452996097799:ios:9f19dd71884b7dde7e47a2',
    messagingSenderId: '452996097799',
    projectId: 'project-vinabike',
    storageBucket: 'project-vinabike.firebasestorage.app',
    androidClientId: '452996097799-fqend7u92h8j41c10lbkirm2kshvph1c.apps.googleusercontent.com',
    iosClientId: '452996097799-s6mfnp814p0goo4eltbu1sco0hf5n87e.apps.googleusercontent.com',
    iosBundleId: 'com.vinabike.erp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDUNqLY7jx7p8bsq5iJYNuAlelK6wJBnQ',
    appId: '1:452996097799:android:acfa1afc2da1411e7e47a2',
    messagingSenderId: '452996097799',
    projectId: 'project-vinabike',
    storageBucket: 'project-vinabike.firebasestorage.app',
  );

}