-- Read-back of 20261002100000: every English or jargon option shows its Spanish
-- display name, the option labels (identities) are unchanged, and the ten
-- field names are plain, and every table names its items. 25 options and 10 field names on 2026-10-01.
-- Read-only; division by zero fails it.
select 1/(case when (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='drivetrain_mode' and v.tenant_id is null and v.label='Derailleur' and v.display_label='Con cambio trasero')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='drivetrain_mode' and v.tenant_id is null and v.label='Single speed / BMX / IGH' and v.display_label='Una velocidad, BMX o cambios en la maza')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='chain_connector_type' and v.tenant_id is null and v.label='Missing link' and v.display_label='Eslabón rápido (missing link)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='chain_connector_type' and v.tenant_id is null and v.label='Pin' and v.display_label='Pasador (pin)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='chain_connector_type' and v.tenant_id is null and v.label='Half link' and v.display_label='Medio eslabón (half link)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='front_derailleur_swing' and v.tenant_id is null and v.label='Down swing' and v.display_label='Hacia abajo (down swing)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='front_derailleur_swing' and v.tenant_id is null and v.label='Side swing' and v.display_label='Lateral (side swing)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='front_derailleur_pull_direction' and v.tenant_id is null and v.label='Side swing' and v.display_label='Lateral (side swing)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='front_derailleur_mount' and v.tenant_id is null and v.label='Braze-on' and v.display_label='Soldado al cuadro (braze-on)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='front_derailleur_mount_type' and v.tenant_id is null and v.label='Braze-on' and v.display_label='Soldado al cuadro (braze-on)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='spindle_interface' and v.tenant_id is null and v.label='One-piece / americano' and v.display_label='Una pieza (americano)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='spindle_interface_accepted' and v.tenant_id is null and v.label='One-piece / americano' and v.display_label='Una pieza (americano)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='control_part_kind' and v.tenant_id is null and v.label='Noodle V-brake' and v.display_label='Codo de V-brake (noodle)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='lock_kind' and v.tenant_id is null and v.label='U-lock' and v.display_label='Candado en U (U-lock)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bar_fit_representation' and v.tenant_id is null and v.label='Medidas discretas (filas)' and v.display_label='Una lista de medidas')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bar_fit_representation' and v.tenant_id is null and v.label='Rango continuo declarado por OEM' and v.display_label='Un rango de medidas del fabricante')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='cassette_spline_standard' and v.tenant_id is null and v.label='Shimano HG spline L (ROAD 11/12v; otras coronas sólo según filas C-731)' and v.display_label='Shimano HG spline L (ruta 11/12v)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='cassette_spline_standard' and v.tenant_id is null and v.label='Shimano HG spline L2 (ROAD 12v dedicado)' and v.display_label='Shimano HG spline L2 (ruta 12v)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='cassette_spline_standard' and v.tenant_id is null and v.label='Shimano HG spline M (8/9/10v y MTB 11v; ROAD 11v y 7v sólo según filas C-731; LINKGLIDE según C-649)' and v.display_label='Shimano HG spline M (8/9/10v y MTB 11v)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='rear_drive_interface' and v.tenant_id is null and v.label='Shimano HG spline L (ROAD 11/12v; otras coronas sólo según filas C-731)' and v.display_label='Shimano HG spline L (ruta 11/12v)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='rear_drive_interface' and v.tenant_id is null and v.label='Shimano HG spline L2 (ROAD 12v dedicado)' and v.display_label='Shimano HG spline L2 (ruta 12v)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='rear_drive_interface' and v.tenant_id is null and v.label='Shimano HG spline M (8/9/10v y MTB 11v; ROAD 11v y 7v sólo según filas C-731; LINKGLIDE según C-649)' and v.display_label='Shimano HG spline M (8/9/10v y MTB 11v)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='target_rear_drive_interface' and v.tenant_id is null and v.label='Shimano HG spline L (ROAD 11/12v; otras coronas sólo según filas C-731)' and v.display_label='Shimano HG spline L (ruta 11/12v)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='target_rear_drive_interface' and v.tenant_id is null and v.label='Shimano HG spline L2 (ROAD 12v dedicado)' and v.display_label='Shimano HG spline L2 (ruta 12v)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='target_rear_drive_interface' and v.tenant_id is null and v.label='Shimano HG spline M (8/9/10v y MTB 11v; ROAD 11v y 7v sólo según filas C-731; LINKGLIDE según C-649)' and v.display_label='Shimano HG spline M (8/9/10v y MTB 11v)')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='bar_clamp_configurations' and label='Diámetros de abrazadera admitidos')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='conflicting_claims' and label='Datos del fabricante que se contradicen')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='brake_model_fluid_approvals' and label='Fluidos aprobados por el fabricante')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='power_port_configurations' and label='Puertos')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='certification_configurations' and label='Certificaciones declaradas')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='helmet_construction' and label='Construcción declarada por el fabricante')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='light_member_configurations' and label='Luces del producto')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='co2_cartridge_configurations' and label='Cartuchos admitidos o incluidos')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='rack_mount_configurations' and label='Puntos de anclaje de la parrilla')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='seatpost_dimension_document' and label='Documento de medidas del fabricante')=1
 and position('display_label' in pg_get_functiondef('public.spec_template_editor_internal_v1(uuid,uuid)'::regprocedure))>0
 and position('spec_option_display_internal_v1' in pg_get_functiondef('public.get_public_product_technical_specs(uuid,uuid)'::regprocedure))>0 and (select count(*) from public.spec_definitions where tenant_id is null and validation_rules ? 'rows_schema' and not validation_rules ? 'row_label')=0 then 1 else 0 end) as spec_sheet_plain_words_ok;
