-- Verifier: fails (division by zero) until every hub label and helper is in place.
select 1/(case when (select count(*) from public.spec_definitions where tenant_id is null and key='spec_evidence_source' and label='Fuente del dato')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='hub_old_mm' and label='Ancho entre tuercas (OLD)')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='spoke_hole_count' and label='Cantidad de hoyos (rayos)')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='hub_spoke_head_interface' and label='Tipo de rayo (con codo o recto)')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='bearing_system' and label='Tipo de rodamiento')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='rotor_mount_type' and label='Anclaje del disco (6 pernos o Centerlock)')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='hub_drive_receiver_present' and label='Lleva núcleo o rosca para piñón')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='hub_drive_receiver_kind' and label='Tipo de núcleo')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='hub_drive_receiver_reference' and label='Modelo del núcleo')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='flange_pcd_left_mm' and label='Círculo de hoyos, brida izquierda (PCD)')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='flange_pcd_right_mm' and label='Círculo de hoyos, brida derecha (PCD)')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='center_to_flange_left_mm' and label='Del centro a la brida izquierda')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='center_to_flange_right_mm' and label='Del centro a la brida derecha')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='hub_flange_to_flange_mm' and label='Entre bridas (centro a centro)')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='spoke_hole_diameter_mm' and label='Diámetro del hoyo del rayo')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='hub_axle_diameter_datum' and label='Dónde se mide el eje')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='hub_supplied_thru_axle_reference' and label='Modelo del eje pasante incluido')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='hub_package_pieces' and label='Mazas de este juego')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_package_position'='Qué viene en la caja: una maza delantera, una trasera, o el juego de las dos. Si es el juego, cada maza va en su propia fila más abajo y no se llena un solo ancho ni una sola perforación.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'spec_evidence_source'='Pega el link de la página del fabricante, o escribe «manual» o «caja» si lo leíste ahí. Sin fuente, los demás datos quedan como no confirmados.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_old_mm'='De tuerca a tuerca del eje, donde la maza apoya en el cuadro o la horquilla. Lo normal: 100 delante; 135 atrás con cierre rápido; 142 o 148 con eje pasante. Un juego de dos mazas no tiene un solo ancho.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'spoke_hole_count'='Cuántos rayos lleva la rueda. Lo común es 32 o 36; cuenta los hoyos de una brida.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_axle_mount_kind'='Cierre rápido: eje hueco con palanca (9 o 10 mm). Eje pasante: eje grueso de 12 o 15 mm que se enrosca al cuadro. Con tuercas: eje macizo con una tuerca a cada lado.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_spoke_head_interface'='Con codo (J-bend) es el rayo de siempre, con la cabeza doblada que entra por el hoyo de la brida. Recto (straight pull) entra derecho. Si el fabricante no lo dice, déjalo sin confirmar.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_rotor_mount_present'='Sí si la maza trae dónde afirmar el disco de freno. No si es para freno de llanta (V-brake o caliper).')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'rotor_mount_type'='6 pernos: el disco va apernado con seis pernos Torx. Centerlock: el disco entra estriado y se afirma con un anillo.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'bearing_system'='Sellados: rodamientos de cartucho, se cambian enteros. Bolas sueltas: bolitas con conos y tazas, se ajustan y se engrasan.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_drive_receiver_present'='Sólo para mazas traseras. Sí si trae el núcleo para cassette o el hilo para piñón de rosca.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_drive_receiver_kind'='Núcleo de cassette (HG de Shimano, Micro Spline, XD) o rosca para piñón de rueda libre. Contrapedal es un freno: no dice por sí solo qué piñón acepta.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_drive_receiver_reference'='El nombre exacto del núcleo según el fabricante (por ejemplo «HG 8-11v» o «Micro Spline»), si lo publica.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'flange_pcd_left_mm'='Diámetro del círculo que forman los hoyos de los rayos en la brida izquierda (lado del disco). Se mide de centro de hoyo a centro del hoyo de enfrente.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'flange_pcd_right_mm'='Diámetro del círculo que forman los hoyos de los rayos en la brida derecha (lado del piñón). Se mide de centro de hoyo a centro del hoyo de enfrente.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'center_to_flange_left_mm'='Desde el centro de la maza (la mitad del ancho entre tuercas) hasta el centro de la brida izquierda. Si el fabricante mide desde la tuerca, convierte antes de escribir; no lo copies tal cual.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'center_to_flange_right_mm'='Desde el centro de la maza hasta el centro de la brida derecha, medido igual que el lado izquierdo.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_flange_to_flange_mm'='De centro de una brida al centro de la otra. Es la suma de las dos distancias al centro, no una de ellas.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'spoke_hole_diameter_mm'='Lo que mide el agujero de la brida por donde entra el rayo. Lo normal es 2,5 o 2,6 mm.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_axle_diameter_datum'='Escribe dónde se mide: por fuera del eje (lo que se ve en la puntera), en el paso por dentro de la maza, u otro punto que indique el fabricante. Ojo: el perno del cierre rápido no es el eje.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_axle_diameter_mm'='Grosor del eje en el punto que indicaste arriba. Cierre rápido: 9 o 10 mm. Pasante: 12 o 15 mm.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_thru_axle_supplied'='Sí sólo si el eje pasante viene en la caja.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_supplied_thru_axle_reference'='El código del eje que viene. Su rosca y su largo son del eje y del cuadro, no de la maza.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_package_pieces'='Sólo lo que viene en la caja: una fila por maza. No es la lista de variantes del fabricante ni una rueda armada.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and key='hub' and form_contract->'helpers'->>'hub_package_piece_count'='Cuántas mazas trae el juego (normalmente dos: delantera y trasera). Confírmalo con la fuente, no por el título.')=1 then 1 else 0 end);
