-- Verifier: fails (division by zero) while any renamed option label is still in allowed_values.
select 1/(case when (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='hub_drive_receiver_kind' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Núcleo estriado de cassette'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='hub_drive_receiver_kind' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Rosca para rueda libre'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='hub_drive_receiver_kind' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Rosca para piñón fijo y contratuerca'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='hub_drive_receiver_kind' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Otra interfaz OEM'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='bearing_system' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Rodamientos sellados'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='derailleur_cage_length' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['SS / corta'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='derailleur_cage_length' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['GS / media'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='derailleur_cage_length' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['SGS / larga'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='locking_mechanism' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Combinación'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='front_derailleur_cable_pull' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Top pull'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='front_derailleur_cable_pull' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Down pull'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='front_derailleur_cable_pull' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Dual pull'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='crankset_construction' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Una pieza (americana / Ashtabula)'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='crankset_construction' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Dos piezas (eje solidario al brazo derecho)'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='crankset_construction' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Tres piezas (eje independiente)'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='compound_type' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Orgánico'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='bar_style' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Recto'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='valve_standard' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Presta (francesa)'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='valve_standard' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Schrader (americana / auto)'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='locking_mechanism' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Llave + combinación'::text]))=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='hub_drive_receiver_kind' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Núcleo de cassette'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='hub_drive_receiver_kind' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Rosca para piñón (rueda libre)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='hub_drive_receiver_kind' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Rosca para piñón fijo'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='hub_drive_receiver_kind' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Otro'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='bearing_system' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Sellados'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='derailleur_cage_length' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Corta (SS)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='derailleur_cage_length' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Media (GS)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='derailleur_cage_length' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Larga (SGS)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='locking_mechanism' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Clave (combinación)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='front_derailleur_cable_pull' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Tiro arriba (top pull)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='front_derailleur_cable_pull' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Tiro abajo (down pull)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='front_derailleur_cable_pull' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Doble tiro (dual pull)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='crankset_construction' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Una pieza (americana)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='crankset_construction' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Dos piezas (integrado)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='crankset_construction' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Tres piezas (motor aparte)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='compound_type' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Orgánico (resina)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='bar_style' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Recto (plano)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='valve_standard' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Francesa (Presta)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='valve_standard' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Auto (Schrader / americana)'::text]))=1
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='locking_mechanism' and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array['Llave y combinación'::text]))=1 then 1 else 0 end) as allowed_values_ok;
