-- Read-only research applier read-back. Fails before publication (division
-- by zero), passes only when the exact reviewed objects are installed and
-- nothing is enabled, registered or applied.
select 1/(case when (select jsonb_agg(jsonb_build_object('identity',p.oid::regprocedure::text,
   'md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,
   'security_definer',p.prosecdef,'volatility',p.provolatile::text,'config',to_jsonb(p.proconfig))
   order by p.oid::regprocedure::text)
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.proname=any(array['apply_product_spec_research_v1','get_product_spec_research_receipt_v1','get_product_spec_research_application_status_v1']))='[{"acl": "{postgres=X/postgres,authenticated=X/postgres}", "config": ["search_path=pg_catalog, public, pg_temp"], "identity": "apply_product_spec_research_v1(uuid)", "md5": "dd356e99326b9d1727b5dcba3b695c43", "owner": "postgres", "security_definer": true, "volatility": "v"}, {"acl": "{postgres=X/postgres,authenticated=X/postgres}", "config": ["search_path=pg_catalog, public, pg_temp"], "identity": "get_product_spec_research_application_status_v1(uuid)", "md5": "c9f31a17aad9cdc3e290d301e8372548", "owner": "postgres", "security_definer": true, "volatility": "s"}, {"acl": "{postgres=X/postgres,authenticated=X/postgres}", "config": ["search_path=pg_catalog, public, pg_temp"], "identity": "get_product_spec_research_receipt_v1(uuid)", "md5": "eb079dec2f23aa54d7223b13124d1c3a", "owner": "postgres", "security_definer": true, "volatility": "s"}]'::jsonb then 1 else 0 end) as exact_applier_functions;
select 1/(case when (select jsonb_agg(jsonb_build_object('name',c.relname,'owner',pg_get_userbyid(c.relowner),
   'acl',c.relacl::text,'rls',c.relrowsecurity,
   'constraints',(select jsonb_agg(jsonb_build_array(conname,pg_get_constraintdef(oid)) order by conname)
     from pg_constraint where conrelid=c.oid),
   'policies',(select count(*) from pg_policies where schemaname='public' and tablename=c.relname))
   order by c.relname)
  from pg_class c join pg_namespace n on n.oid=c.relnamespace
  where n.nspname='public' and c.relname=any(array['product_spec_research_readiness','product_spec_research_applications','product_spec_research_receipts']))='[{"acl": "{postgres=arwdDxtm/postgres}", "constraints": [["product_spec_research_applications_actor_id_fkey", "FOREIGN KEY (actor_id) REFERENCES auth.users(id)"], ["product_spec_research_applications_bundle_sha256_check", "CHECK ((bundle_sha256 ~ ''^[a-f0-9]{64}$''::text))"], ["product_spec_research_applications_check", "CHECK ((encode(digest(command_text, ''sha256''::text), ''hex''::text) = command_sha256))"], ["product_spec_research_applications_command_sha256_check", "CHECK ((command_sha256 ~ ''^[a-f0-9]{64}$''::text))"], ["product_spec_research_applications_command_text_check", "CHECK (((octet_length(command_text) >= 2) AND (octet_length(command_text) <= 4194304)))"], ["product_spec_research_applications_pkey", "PRIMARY KEY (id)"], ["product_spec_research_applications_proposal_check", "CHECK ((jsonb_typeof(proposal) = ''object''::text))"], ["product_spec_research_applications_readiness_id_tenant_id_fkey", "FOREIGN KEY (readiness_id, tenant_id) REFERENCES product_spec_research_readiness(id, tenant_id)"], ["product_spec_research_applications_tenant_id_command_sha256_key", "UNIQUE (tenant_id, command_sha256)"], ["product_spec_research_applications_tenant_id_fkey", "FOREIGN KEY (tenant_id) REFERENCES tenants(id)"]], "name": "product_spec_research_applications", "owner": "postgres", "policies": 0, "rls": true}, {"acl": "{postgres=arwdDxtm/postgres}", "constraints": [["product_spec_research_readiness_audit_sha256_check", "CHECK ((audit_sha256 ~ ''^[a-f0-9]{64}$''::text))"], ["product_spec_research_readiness_id_tenant_id_key", "UNIQUE (id, tenant_id)"], ["product_spec_research_readiness_pkey", "PRIMARY KEY (id)"], ["product_spec_research_readiness_review_sha256_check", "CHECK ((review_sha256 ~ ''^[a-f0-9]{64}$''::text))"], ["product_spec_research_readiness_tenant_id_fkey", "FOREIGN KEY (tenant_id) REFERENCES tenants(id)"]], "name": "product_spec_research_readiness", "owner": "postgres", "policies": 0, "rls": true}, {"acl": "{postgres=arwdDxtm/postgres}", "constraints": [["product_spec_research_receipts_actor_id_fkey", "FOREIGN KEY (actor_id) REFERENCES auth.users(id)"], ["product_spec_research_receipts_application_id_fkey", "FOREIGN KEY (application_id) REFERENCES product_spec_research_applications(id)"], ["product_spec_research_receipts_pkey", "PRIMARY KEY (application_id)"], ["product_spec_research_receipts_product_id_fkey", "FOREIGN KEY (product_id) REFERENCES products(id)"], ["product_spec_research_receipts_tenant_id_fkey", "FOREIGN KEY (tenant_id) REFERENCES tenants(id)"]], "name": "product_spec_research_receipts", "owner": "postgres", "policies": 0, "rls": true}]'::jsonb then 1 else 0 end) as exact_applier_tables;
select 1/(case when (select pg_get_constraintdef(oid) from pg_constraint
  where conrelid='public.spec_facts'::regclass and conname='spec_facts_source_known')='CHECK ((source = ANY (ARRAY[''mechanic''::text, ''catalog''::text, ''supplier_text''::text, ''inferred''::text, ''import''::text, ''name_reading''::text, ''research''::text])))' then 1 else 0 end) as research_source_admitted;
select 1/(case when (select count(*) from public.product_spec_research_readiness)=0
  and (select count(*) from public.product_spec_research_applications)=0
  and (select count(*) from public.product_spec_research_receipts)=0
  and (select count(*) from public.spec_facts where source='research')=0 then 1 else 0 end) as nothing_enabled_registered_or_applied;
