-- Verifier: fails until the local vocabulary is consistent in labels, options, rows and saved JSON.
select 1/(case when (select count(*) from public.spec_definitions where tenant_id is null and key='adapter_to' and label='Conexión de salida del adaptador')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='axle_fit' and label='Eje que acepta')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='bottle_bosses_count' and label='Cantidad de anclajes roscados para portabotella')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='cage_mount' and label='Fijación del portabotella')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='crank_axle_interface_by_member' and label='Unión al eje de cada biela')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='crank_axle_interface_declarations' and label='Uniones documentadas entre biela y eje')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='dropper_actuation' and label='Accionamiento del poste telescópico')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='hub_interface' and label='Conexión de la maza')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='hanger_interface' and label='Tipo de postiza')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='hanger_model_code' and label='Código de la postiza / fusible')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='lever_inline_hydraulic_ports' and label='Conexiones de la manilla hidráulica en línea')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='rear_drive_interface' and label='Sistema de montaje del piñón trasero')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='rear_derailleur_hanger_interface' and label='Montaje del cambio trasero')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='rotor_mount_out' and label='Fijación del disco de salida')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='seatpost_kind' and label='Tipo de poste de asiento')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='seatpost_offset_mm' and label='Retroceso del poste de asiento')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='smallest_cog_fit' and label='Montaje del piñón más pequeño')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='tire_tubeless_ready' and label='Apto para usar sin cámara (Tubeless Ready)' and description='Indica si el neumático declara compatibilidad Tubeless Ready.')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='tire_width_in' and label='Ancho nominal (pulgadas)' and description='Ancho nominal del neumático declarado en pulgadas. No se deriva automáticamente del nombre comercial.')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='tire_width_mm' and label='Ancho' and description='Ancho nominal del neumático declarado en milímetros. Se conserva separado de pulgadas para no inventar conversiones nominales.')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and key='wheel_size' and label='Tamaño de rueda' and description='Rodado nominal declarado para el neumático; no reemplaza una medida ETRTO cuando esa precisión está disponible.')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bag_position' and v.label='Bajo el asiento')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bag_position' and v.label='Bajo sillín')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='bag_position' and d.allowed_values @> to_jsonb(array['Bajo el asiento'::text]) and not d.allowed_values @> to_jsonb(array['Bajo sillín'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='bag_position' and (p.value_text='Bajo sillín' or p.value_option='Bajo sillín' or p.display_value='Bajo sillín'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bar_construction' and v.label='Manubrio y tee integrados')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bar_construction' and v.label='Integrado manubrio + potencia')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='bar_construction' and d.allowed_values @> to_jsonb(array['Manubrio y tee integrados'::text]) and not d.allowed_values @> to_jsonb(array['Integrado manubrio + potencia'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='bar_construction' and (p.value_text='Integrado manubrio + potencia' or p.value_option='Integrado manubrio + potencia' or p.display_value='Integrado manubrio + potencia'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bar_style' and v.label='Ruta (manubrio curvo)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bar_style' and v.label='Ruta (drop)')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='bar_style' and d.allowed_values @> to_jsonb(array['Ruta (manubrio curvo)'::text]) and not d.allowed_values @> to_jsonb(array['Ruta (drop)'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='bar_style' and (p.value_text='Ruta (drop)' or p.value_option='Ruta (drop)' or p.display_value='Ruta (drop)'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bar_width_reference' and v.label='Centro a centro en las manillas (hoods)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bar_width_reference' and v.label='Centro a centro en manetas (hoods)')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='bar_width_reference' and d.allowed_values @> to_jsonb(array['Centro a centro en las manillas (hoods)'::text]) and not d.allowed_values @> to_jsonb(array['Centro a centro en manetas (hoods)'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='bar_width_reference' and (p.value_text='Centro a centro en manetas (hoods)' or p.value_option='Centro a centro en manetas (hoods)' or p.display_value='Centro a centro en manetas (hoods)'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bar_width_reference' and v.label='Centro a centro en la parte baja del manubrio')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bar_width_reference' and v.label='Centro a centro en drops')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='bar_width_reference' and d.allowed_values @> to_jsonb(array['Centro a centro en la parte baja del manubrio'::text]) and not d.allowed_values @> to_jsonb(array['Centro a centro en drops'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='bar_width_reference' and (p.value_text='Centro a centro en drops' or p.value_option='Centro a centro en drops' or p.display_value='Centro a centro en drops'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bike_attachment_kind' and v.label='Abrazadera al tee o poste de asiento')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bike_attachment_kind' and v.label='Abrazadera de potencia / tija')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='bike_attachment_kind' and d.allowed_values @> to_jsonb(array['Abrazadera al tee o poste de asiento'::text]) and not d.allowed_values @> to_jsonb(array['Abrazadera de potencia / tija'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='bike_attachment_kind' and (p.value_text='Abrazadera de potencia / tija' or p.value_option='Abrazadera de potencia / tija' or p.display_value='Abrazadera de potencia / tija'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bike_protection_kind' and v.label='Funda para bicicleta')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bike_protection_kind' and v.label='Funda de bicicleta (cubierta)')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='bike_protection_kind' and d.allowed_values @> to_jsonb(array['Funda para bicicleta'::text]) and not d.allowed_values @> to_jsonb(array['Funda de bicicleta (cubierta)'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='bike_protection_kind' and (p.value_text='Funda de bicicleta (cubierta)' or p.value_option='Funda de bicicleta (cubierta)' or p.display_value='Funda de bicicleta (cubierta)'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bottle_retention_system' and v.label='Portabotella convencional (de aro)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='bottle_retention_system' and v.label='Convencional (portabidón de aro)')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='bottle_retention_system' and d.allowed_values @> to_jsonb(array['Portabotella convencional (de aro)'::text]) and not d.allowed_values @> to_jsonb(array['Convencional (portabidón de aro)'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='bottle_retention_system' and (p.value_text='Convencional (portabidón de aro)' or p.value_option='Convencional (portabidón de aro)' or p.display_value='Convencional (portabidón de aro)'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and v.label='Cáliper con manguera, sin manilla')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and v.label='Cáliper con manguera, sin maneta')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='brake_presentation' and d.allowed_values @> to_jsonb(array['Cáliper con manguera, sin manilla'::text]) and not d.allowed_values @> to_jsonb(array['Cáliper con manguera, sin maneta'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and (p.value_text='Cáliper con manguera, sin maneta' or p.value_option='Cáliper con manguera, sin maneta' or p.display_value='Cáliper con manguera, sin maneta'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and v.label='Cáliper sin manilla')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and v.label='Cáliper sin maneta')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='brake_presentation' and d.allowed_values @> to_jsonb(array['Cáliper sin manilla'::text]) and not d.allowed_values @> to_jsonb(array['Cáliper sin maneta'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and (p.value_text='Cáliper sin maneta' or p.value_option='Cáliper sin maneta' or p.display_value='Cáliper sin maneta'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and v.label='Juego con manillas y cables')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and v.label='Set con manetas y cables')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='brake_presentation' and d.allowed_values @> to_jsonb(array['Juego con manillas y cables'::text]) and not d.allowed_values @> to_jsonb(array['Set con manetas y cables'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and (p.value_text='Set con manetas y cables' or p.value_option='Set con manetas y cables' or p.display_value='Set con manetas y cables'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and v.label='Un freno completo (manilla, cable, funda y cáliper)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and v.label='Un freno completo (maneta, cable y funda, cáliper)')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='brake_presentation' and d.allowed_values @> to_jsonb(array['Un freno completo (manilla, cable, funda y cáliper)'::text]) and not d.allowed_values @> to_jsonb(array['Un freno completo (maneta, cable y funda, cáliper)'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and (p.value_text='Un freno completo (maneta, cable y funda, cáliper)' or p.value_option='Un freno completo (maneta, cable y funda, cáliper)' or p.display_value='Un freno completo (maneta, cable y funda, cáliper)'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and v.label='Un freno completo (manilla, manguera y cáliper)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and v.label='Un freno completo (maneta, manguera, cáliper)')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='brake_presentation' and d.allowed_values @> to_jsonb(array['Un freno completo (manilla, manguera y cáliper)'::text]) and not d.allowed_values @> to_jsonb(array['Un freno completo (maneta, manguera, cáliper)'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='brake_presentation' and (p.value_text='Un freno completo (maneta, manguera, cáliper)' or p.value_option='Un freno completo (maneta, manguera, cáliper)' or p.display_value='Un freno completo (maneta, manguera, cáliper)'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='cable_head' and v.label='Barril (MTB / manillas planas)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='cable_head' and v.label='Barril (MTB / manetas planas)')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='cable_head' and d.allowed_values @> to_jsonb(array['Barril (MTB / manillas planas)'::text]) and not d.allowed_values @> to_jsonb(array['Barril (MTB / manetas planas)'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='cable_head' and (p.value_text='Barril (MTB / manetas planas)' or p.value_option='Barril (MTB / manetas planas)' or p.display_value='Barril (MTB / manetas planas)'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='cage_mount' and v.label='Amarras plásticas al tubo')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='cage_mount' and v.label='Bridas (cable ties) al tubo')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='cage_mount' and d.allowed_values @> to_jsonb(array['Amarras plásticas al tubo'::text]) and not d.allowed_values @> to_jsonb(array['Bridas (cable ties) al tubo'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='cage_mount' and (p.value_text='Bridas (cable ties) al tubo' or p.value_option='Bridas (cable ties) al tubo' or p.display_value='Bridas (cable ties) al tubo'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='cage_retention_system' and v.label='Portabotella convencional (de aro)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='cage_retention_system' and v.label='Convencional (portabidón de aro)')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='cage_retention_system' and d.allowed_values @> to_jsonb(array['Portabotella convencional (de aro)'::text]) and not d.allowed_values @> to_jsonb(array['Convencional (portabidón de aro)'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='cage_retention_system' and (p.value_text='Convencional (portabidón de aro)' or p.value_option='Convencional (portabidón de aro)' or p.display_value='Convencional (portabidón de aro)'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='carrier_mount_kind' and v.label='Abrazadera al poste de asiento')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='carrier_mount_kind' and v.label='Abrazadera a tija')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='carrier_mount_kind' and d.allowed_values @> to_jsonb(array['Abrazadera al poste de asiento'::text]) and not d.allowed_values @> to_jsonb(array['Abrazadera a tija'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='carrier_mount_kind' and (p.value_text='Abrazadera a tija' or p.value_option='Abrazadera a tija' or p.display_value='Abrazadera a tija'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='covering_kind' and v.label='Cinta de manubrio')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='covering_kind' and v.label='Cinta de manillar')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='covering_kind' and d.allowed_values @> to_jsonb(array['Cinta de manubrio'::text]) and not d.allowed_values @> to_jsonb(array['Cinta de manillar'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='covering_kind' and (p.value_text='Cinta de manillar' or p.value_option='Cinta de manillar' or p.display_value='Cinta de manillar'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='declared_purpose' and v.label='Perno de postiza')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='declared_purpose' and v.label='Perno de patilla')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='declared_purpose' and d.allowed_values @> to_jsonb(array['Perno de postiza'::text]) and not d.allowed_values @> to_jsonb(array['Perno de patilla'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='declared_purpose' and (p.value_text='Perno de patilla' or p.value_option='Perno de patilla' or p.display_value='Perno de patilla'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='declared_purpose' and v.label='Perno de portabotella')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='declared_purpose' and v.label='Perno de portacaramagiola')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='declared_purpose' and d.allowed_values @> to_jsonb(array['Perno de portabotella'::text]) and not d.allowed_values @> to_jsonb(array['Perno de portacaramagiola'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='declared_purpose' and (p.value_text='Perno de portacaramagiola' or p.value_option='Perno de portacaramagiola' or p.display_value='Perno de portacaramagiola'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='fender_mount_kind' and v.label='Correas a la horquilla o al poste de asiento')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='fender_mount_kind' and v.label='Correas a horquilla/tija')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='fender_mount_kind' and d.allowed_values @> to_jsonb(array['Correas a la horquilla o al poste de asiento'::text]) and not d.allowed_values @> to_jsonb(array['Correas a horquilla/tija'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='fender_mount_kind' and (p.value_text='Correas a horquilla/tija' or p.value_option='Correas a horquilla/tija' or p.display_value='Correas a horquilla/tija'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='fender_mount_kind' and v.label='Tornillos de tapabarros del cuadro')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='fender_mount_kind' and v.label='Tornillos de guardabarros del cuadro')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='fender_mount_kind' and d.allowed_values @> to_jsonb(array['Tornillos de tapabarros del cuadro'::text]) and not d.allowed_values @> to_jsonb(array['Tornillos de guardabarros del cuadro'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='fender_mount_kind' and (p.value_text='Tornillos de guardabarros del cuadro' or p.value_option='Tornillos de guardabarros del cuadro' or p.display_value='Tornillos de guardabarros del cuadro'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='hanger_interface' and v.label='Postiza estándar (M10x1)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='hanger_interface' and v.label='Patilla estándar (M10x1)')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='hanger_interface' and d.allowed_values @> to_jsonb(array['Postiza estándar (M10x1)'::text]) and not d.allowed_values @> to_jsonb(array['Patilla estándar (M10x1)'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='hanger_interface' and (p.value_text='Patilla estándar (M10x1)' or p.value_option='Patilla estándar (M10x1)' or p.display_value='Patilla estándar (M10x1)'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='light_mount_kind' and v.label='Abrazadera al poste de asiento')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='light_mount_kind' and v.label='Abrazadera de tija')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='light_mount_kind' and d.allowed_values @> to_jsonb(array['Abrazadera al poste de asiento'::text]) and not d.allowed_values @> to_jsonb(array['Abrazadera de tija'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='light_mount_kind' and (p.value_text='Abrazadera de tija' or p.value_option='Abrazadera de tija' or p.display_value='Abrazadera de tija'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='rear_derailleur_hanger_interface' and v.label='Postiza estándar (M10x1)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='rear_derailleur_hanger_interface' and v.label='Patilla estándar (M10x1)')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='rear_derailleur_hanger_interface' and d.allowed_values @> to_jsonb(array['Postiza estándar (M10x1)'::text]) and not d.allowed_values @> to_jsonb(array['Patilla estándar (M10x1)'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='rear_derailleur_hanger_interface' and (p.value_text='Patilla estándar (M10x1)' or p.value_option='Patilla estándar (M10x1)' or p.display_value='Patilla estándar (M10x1)'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='rear_derailleur_hanger_interface' and v.label='Sin postiza (una velocidad)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='rear_derailleur_hanger_interface' and v.label='Sin patilla (single speed)')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='rear_derailleur_hanger_interface' and d.allowed_values @> to_jsonb(array['Sin postiza (una velocidad)'::text]) and not d.allowed_values @> to_jsonb(array['Sin patilla (single speed)'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='rear_derailleur_hanger_interface' and (p.value_text='Sin patilla (single speed)' or p.value_option='Sin patilla (single speed)' or p.display_value='Sin patilla (single speed)'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='shifter_control_style' and v.label='Palanca en punta del manubrio (bar-end)')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='shifter_control_style' and v.label='Palanca en punta de manillar (bar-end)')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='shifter_control_style' and d.allowed_values @> to_jsonb(array['Palanca en punta del manubrio (bar-end)'::text]) and not d.allowed_values @> to_jsonb(array['Palanca en punta de manillar (bar-end)'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='shifter_control_style' and (p.value_text='Palanca en punta de manillar (bar-end)' or p.value_option='Palanca en punta de manillar (bar-end)' or p.display_value='Palanca en punta de manillar (bar-end)'))=0
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='shifter_control_style' and v.label='Integrado con la manilla de freno')=1
 and (select count(*) from public.spec_definition_values v join public.spec_definitions d on d.id=v.spec_definition_id where d.tenant_id is null and d.key='shifter_control_style' and v.label='Integrado con la maneta de freno')=0
 and (select count(*) from public.spec_definitions d where d.tenant_id is null and d.key='shifter_control_style' and d.allowed_values @> to_jsonb(array['Integrado con la manilla de freno'::text]) and not d.allowed_values @> to_jsonb(array['Integrado con la maneta de freno'::text]))=1
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and d.key='shifter_control_style' and (p.value_text='Integrado con la maneta de freno' or p.value_option='Integrado con la maneta de freno' or p.display_value='Integrado con la maneta de freno'))=0
 and (select count(*) from public.product_categories where id='060885f4-653e-4cdc-9b82-f1b223221439'::uuid and tenant_id='5443b130-cc28-45af-a420-cd500b288890'::uuid and name='Portabotellas' and full_path='Accesorios / Portabotellas')=1
 and (select count(*) from public.product_categories where id='47b4e4e2-df85-481e-b4a8-f362c4912630'::uuid and tenant_id='5443b130-cc28-45af-a420-cd500b288890'::uuid and name='Adaptadores para poste de asiento' and full_path='Accesorios / Asientos / Adaptadores para poste de asiento')=1
 and (select count(*) from public.product_categories where id='9a055a2e-25cc-46a3-b30a-7311936914e6'::uuid and tenant_id='5443b130-cc28-45af-a420-cd500b288890'::uuid and name='Postes de asiento' and full_path='Accesorios / Asientos / Postes de asiento')=1
 and (select count(*) from public.product_categories where id='8c5d15a3-df4b-4bc9-85ec-caa68c512252'::uuid and tenant_id='5443b130-cc28-45af-a420-cd500b288890'::uuid and name='Cintas de manubrio' and full_path='Accesorios / Cintas de manubrio')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Bajo sillín"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Bajo sillín"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Bajo sillín"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Bajo sillín"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Integrado manubrio + potencia"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Integrado manubrio + potencia"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Integrado manubrio + potencia"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Integrado manubrio + potencia"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Ruta (drop)"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Ruta (drop)"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Ruta (drop)"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Ruta (drop)"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Centro a centro en manetas (hoods)"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Centro a centro en manetas (hoods)"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Centro a centro en manetas (hoods)"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Centro a centro en manetas (hoods)"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Centro a centro en drops"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Centro a centro en drops"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Centro a centro en drops"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Centro a centro en drops"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Abrazadera de potencia / tija"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Abrazadera de potencia / tija"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Abrazadera de potencia / tija"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Abrazadera de potencia / tija"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Funda de bicicleta (cubierta)"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Funda de bicicleta (cubierta)"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Funda de bicicleta (cubierta)"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Funda de bicicleta (cubierta)"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Convencional (portabidón de aro)"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Convencional (portabidón de aro)"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Convencional (portabidón de aro)"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Convencional (portabidón de aro)"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Cáliper con manguera, sin maneta"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Cáliper con manguera, sin maneta"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Cáliper con manguera, sin maneta"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Cáliper con manguera, sin maneta"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Cáliper sin maneta"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Cáliper sin maneta"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Cáliper sin maneta"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Cáliper sin maneta"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Set con manetas y cables"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Set con manetas y cables"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Set con manetas y cables"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Set con manetas y cables"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Un freno completo (maneta, cable y funda, cáliper)"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Un freno completo (maneta, cable y funda, cáliper)"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Un freno completo (maneta, cable y funda, cáliper)"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Un freno completo (maneta, cable y funda, cáliper)"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Un freno completo (maneta, manguera, cáliper)"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Un freno completo (maneta, manguera, cáliper)"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Un freno completo (maneta, manguera, cáliper)"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Un freno completo (maneta, manguera, cáliper)"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Barril (MTB / manetas planas)"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Barril (MTB / manetas planas)"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Barril (MTB / manetas planas)"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Barril (MTB / manetas planas)"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Bridas (cable ties) al tubo"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Bridas (cable ties) al tubo"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Bridas (cable ties) al tubo"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Bridas (cable ties) al tubo"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Abrazadera a tija"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Abrazadera a tija"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Abrazadera a tija"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Abrazadera a tija"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Cinta de manillar"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Cinta de manillar"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Cinta de manillar"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Cinta de manillar"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Perno de patilla"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Perno de patilla"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Perno de patilla"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Perno de patilla"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Perno de portacaramagiola"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Perno de portacaramagiola"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Perno de portacaramagiola"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Perno de portacaramagiola"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Correas a horquilla/tija"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Correas a horquilla/tija"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Correas a horquilla/tija"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Correas a horquilla/tija"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Tornillos de guardabarros del cuadro"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Tornillos de guardabarros del cuadro"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Tornillos de guardabarros del cuadro"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Tornillos de guardabarros del cuadro"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Patilla estándar (M10x1)"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Patilla estándar (M10x1)"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Patilla estándar (M10x1)"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Patilla estándar (M10x1)"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Abrazadera de tija"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Abrazadera de tija"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Abrazadera de tija"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Abrazadera de tija"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Sin patilla (single speed)"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Sin patilla (single speed)"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Sin patilla (single speed)"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Sin patilla (single speed)"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Palanca en punta de manillar (bar-end)"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Palanca en punta de manillar (bar-end)"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Palanca en punta de manillar (bar-end)"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Palanca en punta de manillar (bar-end)"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Integrado con la maneta de freno"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Integrado con la maneta de freno"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Integrado con la maneta de freno"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Integrado con la maneta de freno"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Diámetro de manillar"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Diámetro de manillar"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Diámetro de manillar"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Diámetro de manillar"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"PCD de brida izquierda"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"PCD de brida izquierda"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"PCD de brida izquierda"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"PCD de brida izquierda"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"PCD de brida derecha"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"PCD de brida derecha"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"PCD de brida derecha"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"PCD de brida derecha"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Centro de maza a brida izquierda"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Centro de maza a brida izquierda"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Centro de maza a brida izquierda"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Centro de maza a brida izquierda"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Centro de maza a brida derecha"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Centro de maza a brida derecha"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Centro de maza a brida derecha"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Centro de maza a brida derecha"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Distancia entre bridas"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Distancia entre bridas"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Distancia entre bridas"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Distancia entre bridas"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"maneta"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"maneta"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"maneta"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"maneta"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"cubierta"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"cubierta"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"cubierta"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"cubierta"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Perímetro máx. (tija aero)"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Perímetro máx. (tija aero)"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Perímetro máx. (tija aero)"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Perímetro máx. (tija aero)"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Modelo/generación de tija cubiertos por la declaración"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Modelo/generación de tija cubiertos por la declaración"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Modelo/generación de tija cubiertos por la declaración"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Modelo/generación de tija cubiertos por la declaración"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Ancho de cubierta mínimo"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Ancho de cubierta mínimo"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Ancho de cubierta mínimo"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Ancho de cubierta mínimo"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Ancho de cubierta máximo"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Ancho de cubierta máximo"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Ancho de cubierta máximo"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Ancho de cubierta máximo"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Patilla o montaje objetivo"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Patilla o montaje objetivo"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Patilla o montaje objetivo"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Patilla o montaje objetivo"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Tija telescópica"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Tija telescópica"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Tija telescópica"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Tija telescópica"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Maneta"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Maneta"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Maneta"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Maneta"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Llanta de referencia de la cubierta"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Llanta de referencia de la cubierta"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Llanta de referencia de la cubierta"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Llanta de referencia de la cubierta"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Con guardabarros"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Con guardabarros"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Con guardabarros"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Con guardabarros"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Asiento de tija"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Asiento de tija"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Asiento de tija"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Asiento de tija"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Patilla de cambio"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Patilla de cambio"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Patilla de cambio"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Patilla de cambio"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Tubo de sillín"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Tubo de sillín"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Tubo de sillín"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Tubo de sillín"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Ángulo de sillín"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Ángulo de sillín"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Ángulo de sillín"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Ángulo de sillín"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Cubierta"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Cubierta"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Cubierta"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Cubierta"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_definitions where tenant_id is null and position('"Fila de la maneta"' in validation_rules::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and position('"Fila de la maneta"' in form_contract::text)>0)=0
 and (select count(*) from public.spec_facts f join public.spec_definitions d on d.id=f.spec_definition_id where d.tenant_id is null and f.value_json is not null and position('"Fila de la maneta"' in f.value_json::text)>0)=0
 and (select count(*) from public.product_spec_values p join public.spec_definitions d on d.id=p.spec_definition_id where d.tenant_id is null and p.value_json is not null and position('"Fila de la maneta"' in p.value_json::text)>0)=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='bottle_cage' and name='Portabotella' and coalesce(description,'')='')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='derailleur_hanger' and name='Postiza / fusible de cambio' and coalesce(description,'')='Pieza reemplazable que une el cambio trasero al cuadro; se confirma por cuadro, modelo y fijación.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='derailleur_hanger_extender' and name='Extensor de postiza' and coalesce(description,'')='Extensor que cambia la posición del cambio trasero.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='handlebar_covering' and name='Cinta o funda de manubrio' and coalesce(description,'')='')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='rim_brake' and name='Freno de aro / V-Brake' and coalesce(description,'')='Frenos tipo V-Brake o cantilever')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='seat_clamp' and name='Abrazadera del poste de asiento' and coalesce(description,'')='')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='seatpost' and name='Poste de asiento' and coalesce(description,'')='Poste que une el asiento al cuadro, fijo o telescópico.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='seatpost_shim' and name='Adaptador reductor para poste de asiento' and coalesce(description,'')='')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='shifter' and name='Manilla de cambio / shifter' and coalesce(description,'')='Manilla de cambio; compatibilidad por posición, velocidades e indexado.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='stem' and name='Tee / potencia' and coalesce(description,'')='')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='seatpost_shim' and form_contract->'labels'->>'shim_inner_diameter_mm'='Diámetro nominal del poste admitido')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='seatpost_shim' and form_contract->'labels'->>'shim_outer_diameter_mm'='Diámetro interior del tubo del cuadro')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='seatpost_shim' and form_contract->'labels'->>'seatpost_shim_length_mm'='Largo total del adaptador')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='bicycle' and form_contract->'helpers'->>'assembly_wheel_members'='Cada rueda conserva medidas y montajes propios. Compartir diámetro no aprueba neumático ni cassette. La posición delantera no prohíbe por sí sola una transmisión documentada; declarar el puerto que existe.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='bicycle' and form_contract->'helpers'->>'assembly_frame_fitment_claims'='Una holgura o un OLD admitido conserva rueda, montaje, tapabarros y fuente. El ancho propio del cuadro no es el conjunto de anchos de maza permitidos. Una declaración condicionada necesita sus condiciones.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='brake_lever' and form_contract->'helpers'->>'brake_actuation'='Cómo acciona esta manilla. Una manilla de cable que mueve un convertidor sigue siendo mecánica.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='brake_lever' and form_contract->'helpers'->>'lever_cable_pull'='El tiro que ESTA manilla entrega. Lo que un cáliper exige es otra celda en otra pieza, y una no implica la otra.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='brake_lever' and form_contract->'helpers'->>'brake_bleed_ports'='Sólo puertos que el procedimiento OEM identifica para purgar esta manilla. No convierte un tornillo de sellado en purgador.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='brake_lever' and form_contract->'helpers'->>'handlebar_clamp_mm'='Diámetro exterior de la sección donde se fija esta manilla. No se restringe a 22,2 o 23,8 ni se deduce del tiro.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='brake_lever' and form_contract->'helpers'->>'lever_hydraulic_role'='La manilla auxiliar en línea conecta con un mando principal y con el resto del circuito. No es un par de manillas.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='brake_lever' and form_contract->'helpers'->>'lever_cable_interface'='Una manilla en línea puede actuar sobre la funda con el cable pasante. Ambos usos requieren documentación del mismo modelo.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='brake_lever' and form_contract->'helpers'->>'lever_cable_head_profiles'='Describe el alojamiento de esta manilla. Doble cabeza describe un cable sin cortar, no un alojamiento universal.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='brake_lever' and form_contract->'helpers'->>'brake_piece_hydraulic_ports'='Salidas hidráulicas de la manilla principal. La auxiliar en línea tiene su propia tabla de conexiones.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='brake_shift_combined_control' and form_contract->'helpers'->>'combined_control_brake_configurations'='Una configuración completa por fila. El líquido, el tiro y el conector se declaran junto al accionamiento al que pertenecen, así que una manilla de cable no puede llevar un fluido y una hidráulica no puede llevar un tiro. Dos líquidos aprobados son dos filas completas, cada una con su sistema y su fuente: compartir clase de fluido no es una aprobación, y lo aprobado para un mando no vale para el otro por venir en la misma caja. El conector y su especificación describen el extremo externo, así que sólo se declaran donde se declaró que ese extremo existe. Si el cable termina en un conversor hidráulico externo, el mando sigue siendo de cable. El líquido y el conector hidráulico pertenecen al conversor o cáliper y se documentan en la ficha de esa pieza.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='derailleur_hanger' and form_contract->'helpers'->>'bolt_pattern'='Sujeción publicada, por ejemplo un perno M8. Dos patas de cambio distintas pueden compartir perno sin compartir código ni calce: el perno no identifica la pieza.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='derailleur_hanger' and form_contract->'helpers'->>'hanger_frame_interface'='Cómo se une esta pieza al cuadro. UDH es una postiza física sobre una unión estandarizada; un cambio Full Mount sustituye la postiza y por eso no es una opción de esta ficha.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='frame' and form_contract->'helpers'->>'assembly_frame_fitment_claims'='Una holgura o un OLD admitido conserva rueda, montaje, tapabarros y fuente. El ancho propio del cuadro no es el conjunto de anchos de maza permitidos. Una declaración condicionada necesita sus condiciones.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='hub_brake' and form_contract->'helpers'->>'brake_actuation'='Accionamiento del freno de esta rueda. No deducir el sistema de la otra rueda ni bloquear una manilla sólo porque existe contrapedal detrás.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='hydraulic_disc_brake' and form_contract->'helpers'->>'kit_members'='Una fila por pieza física incluida, con su perfil propio: cada manilla, cada cáliper, cada línea, rotor, adaptador o pastilla. Dos piezas del mismo modelo son dos filas. Las medidas y conexiones viven en el perfil de cada pieza, nunca en esta raíz.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='hydraulic_disc_brake' and form_contract->'helpers'->>'brake_circuits'='Un circuito por freno accionado: qué manilla mueve qué cáliper o mecanismo y por qué línea, apuntando a las filas de piezas. El líquido con que se entrega es del circuito; el que cada pieza admite es de esa pieza. Declararlo no verifica que las piezas calcen.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='mechanical_disc_brake' and form_contract->'helpers'->>'kit_members'='Una fila por pieza física incluida, con su perfil propio: cada manilla, cada cáliper, cada línea, rotor, adaptador o pastilla. Dos piezas del mismo modelo son dos filas. Las medidas y conexiones viven en el perfil de cada pieza, nunca en esta raíz.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='mechanical_disc_brake' and form_contract->'helpers'->>'brake_circuits'='Un circuito por freno accionado: qué manilla mueve qué cáliper o mecanismo y por qué línea, apuntando a las filas de piezas. El líquido con que se entrega es del circuito; el que cada pieza admite es de esa pieza. Declararlo no verifica que las piezas calcen.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='rim' and form_contract->'helpers'->>'bead_seat_diameter_mm'='Diámetro del apoyo del talón en un aro para neumático con talón. Coincidir en este dato es necesario, pero no resuelve ancho, perfil, presión y método de montaje.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='rim' and form_contract->'helpers'->>'rim_drilling_patterns'='Sólo patrones de esta pieza, con el punto de referencia y la convención de la fuente. No convertir otros taladrados ofertados en hechos de este SKU.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='rim' and form_contract->'helpers'->>'rim_internal_width_mm'='Ancho interno del apoyo del talón según la fuente. No convertir una etiqueta ISO textual en una medición física sin identificar el estándar y el punto de referencia.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='rim' and form_contract->'helpers'->>'rim_joint_designation'='Designación de construcción OEM: no obliga a asignar un método metálico a un aro de otra construcción.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='rim' and form_contract->'helpers'->>'rim_spoke_hole_diameter_mm'='Agujero del aro para el niple, publicado por el fabricante. No es el calibre del rayo ni la medida de la llave.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='rim_brake' and form_contract->'helpers'->>'kit_members'='Una fila por pieza física incluida, con su perfil propio: cada manilla, cada mecanismo, cada línea, rotor, adaptador o pastilla. Dos piezas del mismo modelo son dos filas. Las medidas y conexiones viven en el perfil de cada pieza, nunca en esta raíz.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='rim_brake' and form_contract->'helpers'->>'brake_circuits'='Un circuito por freno accionado: qué manilla mueve qué cáliper o mecanismo y por qué línea, apuntando a las filas de piezas. El líquido con que se entrega es del circuito; el que cada pieza admite es de esa pieza. Declararlo no verifica que las piezas calcen.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='rim_strip' and form_contract->'helpers'->>'strip_fit_internal_width_max_mm'='El rango de aro al que sirve esta tira, no su propio ancho.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='rim_strip' and form_contract->'helpers'->>'strip_fit_internal_width_min_mm'='El rango de aro al que sirve esta tira, no su propio ancho.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='seatpost' and form_contract->'helpers'->>'seatpost_kind'='Poste de asiento completo. Un adaptador reductor tiene su propia ficha.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='seatpost_shim' and form_contract->'helpers'->>'material'='Material del adaptador indicado por la fuente. No determina qué materiales de cuadro o poste de asiento admite.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='seatpost_shim' and form_contract->'helpers'->>'seatpost_shim_shape'='Una pieza concreta. No mezclar medidas de variantes ni juegos de adaptadores.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='seatpost_shim' and form_contract->'helpers'->>'shim_inner_diameter_mm'='Medida nominal del poste de asiento que acepta esta pieza; no un intervalo de diámetros.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='seatpost_shim' and form_contract->'helpers'->>'shim_outer_diameter_mm'='Medida nominal del ajuste interior del cuadro. No es el diámetro exterior del tubo ni el de su abrazadera.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='seatpost_shim' and form_contract->'helpers'->>'seatpost_shim_length_mm'='Largo físico de esta pieza cuando la fuente lo publica; no determina la inserción mínima del poste de asiento en el cuadro.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='seatpost_shim' and form_contract->'helpers'->>'seatpost_shim_support_length_mm'='Sólo la zona útil de apoyo declarada. No puede superar el largo total del adaptador.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='shifter' and form_contract->'helpers'->>'handlebar_clamp_mm'='Diámetro del manubrio que abraza este mando. En un par, cada mando declara el suyo en la tabla de unidades.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='shifter' and form_contract->'helpers'->>'shifter_control_style'='Cómo se opera la palanca. Es una forma de mando, no una compatibilidad: dos gatillos distintos no son intercambiables por ser gatillos. Un mando integrado con la manilla de freno pertenece a la familia de mando combinado, y esa reasignación se hace con evidencia del producto, no por el título.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='spoke' and form_contract->'helpers'->>'spoke_length_mm'='Largo del producto según su referencia y punto de medición OEM. El cálculo para una rueda depende de maza, aro y patrón de radiado; no es una propiedad universal de un rayo de esta longitud.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='tire' and form_contract->'helpers'->>'tire_general_max_pressures'='Una fila por máximo que la fuente declara para esta variante sin condicionarlo a un perfil de aro. Conserva unidad, alcance y documento; no conviertas cifras. Los límites condicionados van en las declaraciones de montaje. Fuentes discrepantes requieren revisión antes de usar sus límites.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='tubeless_tape' and form_contract->'helpers'->>'tape_width_mm'='Ancho de esta cinta, no ancho interno del aro. La elección, vueltas y preparación siguen las instrucciones del fabricante para ese aro; no se añade automáticamente una diferencia universal de milímetros.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='tubeless_tape' and form_contract->'helpers'->>'tubeless_tape_application'='Aro, ancho, vueltas y condiciones que el fabricante declara para esta cinta; no inferirlos del ancho.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='wheel' and form_contract->'helpers'->>'assembly_wheel_members'='Cada rueda conserva medidas y montajes propios. Compartir diámetro no aprueba neumático ni cassette. La posición delantera no prohíbe por sí sola una transmisión documentada; declarar el puerto que existe.')=1
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and key='wheel' and form_contract->'helpers'->>'wheel_compatible_claims'='Lo que el fabricante declara que esta rueda acepta. No es lo que viene en la caja, que va en los miembros del conjunto, y ninguna de las dos cosas implica la otra: una rueda puede venir con un neumático que no es el único que acepta, y aceptar uno que no incluye. Un diámetro igual no es una declaración de compatibilidad.')=1
 and (select count(*) from pg_catalog.pg_trigger g where g.tgrelid='public.spec_definitions'::regclass and g.tgname='spec_rows_definition_guard' and not g.tgisinternal and g.tgenabled='O')=1
 and (select count(*) from pg_catalog.pg_trigger g where g.tgrelid='public.spec_facts'::regclass and g.tgname='spec_rows_fact_guard' and not g.tgisinternal and g.tgenabled='O')=1
 and (select count(*) from pg_catalog.pg_trigger g where g.tgrelid='public.spec_templates'::regclass and g.tgname='spec_coherence_publication_guard' and not g.tgisinternal and g.tgenabled='O')=1
 and (select count(*) from public.spec_definitions where tenant_id is null and (label~*'\m(brida|bridas|tija|tijas|sillín|sillines|patilla|patillas|portabidón|portacaramagiola|manillar|manillares|maneta|manetas|guardabarros)\M' or coalesce(description,'')~*'\m(brida|bridas|tija|tijas|sillín|sillines|patilla|patillas|portabidón|portacaramagiola|manillar|manillares|maneta|manetas|guardabarros)\M' or allowed_values::text~*'\m(brida|bridas|tija|tijas|sillín|sillines|patilla|patillas|portabidón|portacaramagiola|manillar|manillares|maneta|manetas|guardabarros)\M' or validation_rules::text~*'\m(brida|bridas|tija|tijas|sillín|sillines|patilla|patillas|portabidón|portacaramagiola|manillar|manillares|maneta|manetas|guardabarros)\M'))=0
 and (select count(*) from public.spec_templates where tenant_id is null and is_active and (name~*'\m(brida|bridas|tija|tijas|sillín|sillines|patilla|patillas|portabidón|portacaramagiola|manillar|manillares|maneta|manetas|guardabarros)\M' or coalesce(description,'')~*'\m(brida|bridas|tija|tijas|sillín|sillines|patilla|patillas|portabidón|portacaramagiola|manillar|manillares|maneta|manetas|guardabarros)\M' or form_contract::text~*'\m(brida|bridas|tija|tijas|sillín|sillines|patilla|patillas|portabidón|portacaramagiola|manillar|manillares|maneta|manetas|guardabarros)\M'))=0 then 1 else 0 end) as chilean_bicycle_option_language_ok;
