#!/usr/bin/env python3
"""Sync spec_definitions.allowed_values with the renamed option labels.

An option label lives in two places: the `spec_definition_values` row (what a
fact references by id) and the `allowed_values` array of its definition (what
the validator checks a value against). 20260916180000 and 20260916181000
renamed the row labels only; the validator then flagged every fact holding a
renamed option as «no pertenece a las opciones del campo» and the storefront
hid those rows. This migration replaces the old labels inside the arrays,
element by element, and its verifier fails until no renamed label is left.

Usage: compile_allowed_values_sync.py [--version 20260916182000]
"""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'scripts/inventory'))
from compile_customer_labels import OPTION_LABELS, q  # noqa: E402

RENAMES = [(k, o, n) for k, o, n in OPTION_LABELS if n != 'Llave y clave'] + [
    ('locking_mechanism', 'Llave + combinación', 'Llave y combinación'),
]


def migration(version):
    lines = [
        '-- Sync allowed_values with the option labels renamed by 20260916180000 and',
        '-- 20260916181000: the validator checks facts against this array, so a renamed',
        '-- option was reported as outside the field and hidden from the storefront.',
        '-- Rerunnable: each update only touches arrays that still hold the old label.',
        f'-- Generated by scripts/inventory/compile_allowed_values_sync.py --version {version}.',
        'begin;',
        "set local lock_timeout='5s';",
        "set local statement_timeout='120s';",
    ]
    for key, old, new in RENAMES:
        lines.append(
            'update public.spec_definitions d set allowed_values=(select jsonb_agg(case when e=to_jsonb('
            + q(old) + '::text) then to_jsonb(' + q(new) + '::text) else e end order by ord)'
            ' from jsonb_array_elements(d.allowed_values) with ordinality as t(e, ord)), updated_at=now()'
            ' where d.tenant_id is null and d.key=' + q(key)
            + " and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array[" + q(old) + '::text]);')
    lines.append('commit;')
    return '\n'.join(lines) + '\n'


def verifier():
    checks = ['(select count(*) from public.spec_definitions d where d.tenant_id is null and d.key=' + q(k)
              + " and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array[" + q(o) + '::text]))=0'
              for k, o, _ in RENAMES]
    checks += ['(select count(*) from public.spec_definitions d where d.tenant_id is null and d.key=' + q(k)
               + " and jsonb_typeof(d.allowed_values)='array' and d.allowed_values @> to_jsonb(array[" + q(n) + '::text]))=1'
               for k, _, n in RENAMES]
    return ('-- Verifier: fails (division by zero) while any renamed option label is still in allowed_values.\n'
            'select 1/(case when ' + '\n and '.join(checks) + ' then 1 else 0 end) as allowed_values_ok;\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--version', default='20260916182000')
    args = parser.parse_args()
    mig = ROOT / f'supabase/migrations/{args.version}_allowed_values_label_sync.sql'
    ver = ROOT / f'supabase/manual_checks/verification/{args.version}_allowed_values_label_sync.sql'
    mig.write_text(migration(args.version))
    ver.write_text(verifier())
    print(mig, len(RENAMES), 'renames')
    print(ver)


if __name__ == '__main__':
    main()
