/// Supabase project configuration.
///
/// Provide your Supabase project URL and public anon key here or via
/// Dart-define values when launching the app.
class SupabaseConfig {
  const SupabaseConfig._();

  /// Base URL of your Supabase project, e.g. https://xyzcompany.supabase.co
  static const String url = String.fromEnvironment(
    'SUPABASE_URL',
    defaultValue: 'https://xzdvtzdqjeyqxnkqprtf.supabase.co',
  );

  /// Public anon key generated by Supabase for client access.
  static const String anonKey = String.fromEnvironment(
    'SUPABASE_ANON_KEY',
    defaultValue:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6ZHZ0emRxamV5cXhua3FwcnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNjQyMzUsImV4cCI6MjA3NTY0MDIzNX0.q5OswWMx6C00dbSHlFSOKlv6BA6GKx36VtVSy8ohxAM',
  );

  /// Modern public API key. New server boundaries use this value and never
  /// require the legacy anon JWT. Launches that have not migrated yet keep the
  /// legacy public key for existing services, while the gateway stays disabled.
  static const String publishableKey = String.fromEnvironment(
    'SUPABASE_PUBLISHABLE_KEY',
  );

  /// Indicates whether both URL and anon key look configured.
  static bool get isConfigured => url.isNotEmpty && anonKey.isNotEmpty;
}
