/// Supabase project configuration.
///
/// Provide your Supabase project URL and public anon key here or via
/// Dart-define values when launching the app.
class SupabaseConfig {
  const SupabaseConfig._();

  /// Base URL of your Supabase project
  /// STAGING (default): https://kyvgmapifacpzuyreasy.supabase.co
  /// PRODUCTION: https://xzdvtzdqjeyqxnkqprtf.supabase.co
  static const String url = String.fromEnvironment(
    'SUPABASE_URL',
    defaultValue: 'https://kyvgmapifacpzuyreasy.supabase.co', // ⚠️ STAGING (safe default)
  );

  /// Public anon key generated by Supabase for client access.
  /// STAGING (default): eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...kyvgmapifacpzuyreasy...
  /// PRODUCTION: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...xzdvtzdqjeyqxnkqprtf...
  static const String anonKey = String.fromEnvironment(
    'SUPABASE_ANON_KEY',
    defaultValue:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dmdtYXBpZmFjcHp1eXJlYXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4MzcxNjcsImV4cCI6MjA3OTQxMzE2N30.D9o18KmFC_L0LvtoQYSyspZubFPvieIjRrlTnSTPGuw', // ⚠️ STAGING (safe default)
  );

  /// Indicates whether both URL and anon key look configured.
  static bool get isConfigured => url.isNotEmpty && anonKey.isNotEmpty;
}
