/// Supabase project configuration.
///
/// Provide your Supabase project URL and public anon key here or via
/// Dart-define values when launching the app.
class SupabaseConfig {
  const SupabaseConfig._();

  /// Base URL of your Supabase project, e.g. https://xyzcompany.supabase.co
  static const String url = String.fromEnvironment(
    'SUPABASE_URL',
    defaultValue: 'https://xzdvtzdqjeyqxnkqprtf.supabase.co',
  );

  /// Public anon key generated by Supabase for client access.
  static const String anonKey = String.fromEnvironment(
    'SUPABASE_ANON_KEY',
    defaultValue:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6ZHZ0emRxamV5cXhua3FwcnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNjQyMzUsImV4cCI6MjA3NTY0MDIzNX0.q5OswWMx6C00dbSHlFSOKlv6BA6GKx36VtVSy8ohxAM',
  );

  /// Indicates whether both URL and anon key look configured.
  static bool get isConfigured =>
    url.isNotEmpty && anonKey.isNotEmpty;
}
