-- Seed SEO Data for standard pages
-- Generated by Antigravity Agent
DO $$
DECLARE
    v_tenant_id UUID;
    v_home_page_id UUID;
BEGIN
    -- 1. Find the tenant (prioritize 'vinabike', fallback to any)
    SELECT id INTO v_tenant_id FROM public.tenants WHERE subdomain = 'vinabike' LIMIT 1;
    IF v_tenant_id IS NULL THEN
        SELECT id INTO v_tenant_id FROM public.tenants LIMIT 1;
    END IF;

    IF v_tenant_id IS NOT NULL THEN
        RAISE NOTICE 'Seeding SEO for tenant: %', v_tenant_id;

        -- 2. Upsert Home Page ('home' or 'inicio')
        -- We try to find existing home page first
        SELECT id INTO v_home_page_id FROM public.website_pages 
        WHERE tenant_id = v_tenant_id AND (is_home = true OR slug = 'home' OR slug = 'inicio') LIMIT 1;

        IF v_home_page_id IS NULL THEN
            -- Create Home Page if missing
            INSERT INTO public.website_pages (
                tenant_id, slug, title, is_home, is_published, is_system, template, 
                meta_title, meta_description
            ) VALUES (
                v_tenant_id, 'home', 'Inicio', true, true, true, 'default',
                'Vinabike - Bicicletas y Taller en Viña del Mar | Venta y Reparación',
                'Descubre la mejor tienda de bicicletas en Viña del Mar. Venta de bicicletas, accesorios, repuestos y servicio técnico especializado. ¡Visítanos!'
            );
        ELSE
            -- Update existing Home Page
            UPDATE public.website_pages SET
                meta_title = 'Vinabike - Bicicletas y Taller en Viña del Mar | Venta y Reparación',
                meta_description = 'Descubre la mejor tienda de bicicletas en Viña del Mar. Venta de bicicletas, accesorios, repuestos y servicio técnico especializado. ¡Visítanos!'
            WHERE id = v_home_page_id;
        END IF;

        -- 3. Upsert Products Page ('productos')
        INSERT INTO public.website_pages (
            tenant_id, slug, title, is_home, is_published, is_system, template,
            meta_title, meta_description
        ) VALUES (
            v_tenant_id, 'productos', 'Productos', false, true, true, 'product-list',
            'Catálogo de Bicicletas y Accesorios - Vinabike Viña del Mar',
            'Explora nuestro catálogo completo de bicicletas de montaña, ruta y accesorios. Las mejores marcas y precios en Vinabike.'
        ) ON CONFLICT (tenant_id, slug) DO UPDATE SET
            meta_title = EXCLUDED.meta_title,
            meta_description = EXCLUDED.meta_description;

        -- 4. Upsert Contact Page ('contacto')
        INSERT INTO public.website_pages (
            tenant_id, slug, title, is_home, is_published, is_system, template,
            meta_title, meta_description
        ) VALUES (
            v_tenant_id, 'contacto', 'Contacto', false, true, true, 'default',
            'Contacto y Ubicación - Vinabike Taller de Bicicletas',
            'Ubícanos en Viña del Mar. Teléfono, horario de atención y dirección de nuestra tienda y taller de bicicletas. ¡Contáctanos!'
        ) ON CONFLICT (tenant_id, slug) DO UPDATE SET
            meta_title = EXCLUDED.meta_title,
            meta_description = EXCLUDED.meta_description;

        -- 5. Upsert Services Page ('servicios')
        INSERT INTO public.website_pages (
            tenant_id, slug, title, is_home, is_published, is_system, template,
            meta_title, meta_description
        ) VALUES (
            v_tenant_id, 'servicios', 'Servicios', false, true, false, 'default',
            'Servicio Técnico de Bicicletas en Viña del Mar | Taller Vinabike',
            'Taller profesional de bicicletas en Viña del Mar. Mantenciones, reparaciones y ajustes por mecánicos expertos. Agenda tu hora hoy.'
        ) ON CONFLICT (tenant_id, slug) DO UPDATE SET
            meta_title = EXCLUDED.meta_title,
            meta_description = EXCLUDED.meta_description;
            
        -- 6. Upsert About Us Page ('nosotros')
        INSERT INTO public.website_pages (
            tenant_id, slug, title, is_home, is_published, is_system, template,
            meta_title, meta_description
        ) VALUES (
            v_tenant_id, 'nosotros', 'Sobre Nosotros', false, true, false, 'default',
            'Sobre Nosotros - Vinabike | Pasión por el Ciclismo',
            'Conoce la historia de Vinabike, tu tienda de bicicletas de confianza en Viña del Mar. Expertos y apasionados por el ciclismo a tu servicio.'
        ) ON CONFLICT (tenant_id, slug) DO UPDATE SET
            meta_title = EXCLUDED.meta_title,
            meta_description = EXCLUDED.meta_description;

    ELSE
        RAISE WARNING 'No tenant found for seeding SEO data.';
    END IF;
END $$;
