-- Deployment status: DEPLOYED 2026-07-11. Blocks posted invoice deletion and archives
-- every posted journal header plus lines before legacy replacement/deletion.
begin;

create table if not exists public.journal_supersession_evidence(
 id bigint generated by default as identity primary key,
 tenant_id uuid not null references public.tenants(id) on delete cascade,
 journal_entry_id uuid not null,
 operation_id uuid,
 source_module text,
 source_reference text,
 header_snapshot jsonb not null,
 lines_snapshot jsonb not null,
 captured_reason text not null,
 captured_by uuid references auth.users(id),
 captured_at timestamptz not null default clock_timestamp(),
 unique(tenant_id,journal_entry_id),
 foreign key(tenant_id,operation_id)
  references public.inventory_accounting_operations(tenant_id,id) on delete restrict
);
create index if not exists idx_journal_supersession_operation
 on public.journal_supersession_evidence(tenant_id,operation_id,captured_at)
 where operation_id is not null;
create index if not exists idx_journal_supersession_source
 on public.journal_supersession_evidence(tenant_id,source_module,source_reference,captured_at);
alter table public.journal_supersession_evidence enable row level security;
drop policy if exists journal_supersession_evidence_select on public.journal_supersession_evidence;
create policy journal_supersession_evidence_select on public.journal_supersession_evidence
 for select to authenticated using(tenant_id=public.user_tenant_id());
revoke insert,update,delete on public.journal_supersession_evidence from public,anon,authenticated;
grant select on public.journal_supersession_evidence to authenticated;

create or replace function public.capture_posted_journal_supersession_evidence()
returns trigger language plpgsql security definer set search_path=public as $$
declare
 v_operation_id uuid;
 v_operation_text text:=nullif(current_setting('app.inventory_operation_id',true),'');
 v_lines jsonb;
begin
 if lower(coalesce(old.status,'draft'))<>'posted'then return old;end if;
 v_operation_id:=coalesce(case when v_operation_text is null then null else v_operation_text::uuid end,old.operation_id);
 select coalesce(jsonb_agg(to_jsonb(line)order by line.created_at,line.id),'[]'::jsonb)
  into v_lines from public.journal_lines line where line.entry_id=old.id;
 insert into public.journal_supersession_evidence(
  tenant_id,journal_entry_id,operation_id,source_module,source_reference,
  header_snapshot,lines_snapshot,captured_reason,captured_by
 )values(
  old.tenant_id,old.id,v_operation_id,old.source_module,old.source_reference,
  to_jsonb(old),v_lines,coalesce(nullif(current_setting('app.journal_supersession_reason',true),''),'legacy_posted_journal_replacement'),auth.uid()
 )on conflict(tenant_id,journal_entry_id)do nothing;
 if v_operation_id is not null then
  perform public.append_inventory_accounting_checkpoint(
   v_operation_id,'journal_reversed','completed','journal_entry',old.id,
   jsonb_build_object('evidence','immutable_full_snapshot','header',to_jsonb(old),'lines',v_lines)
  );
 end if;
 return old;
end;$$;
drop trigger if exists trg_capture_posted_journal_supersession on public.journal_entries;
create trigger trg_capture_posted_journal_supersession before delete on public.journal_entries
 for each row execute function public.capture_posted_journal_supersession_evidence();

create or replace function public.guard_posted_invoice_delete()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_status text:=lower(coalesce(old.status,'draft'));
begin
 if current_user in('postgres','service_role')
    and current_setting('app.allow_posted_document_purge',true)='true'then return old;end if;
 if v_status not in('draft','borrador')then
  raise exception 'Posted invoices cannot be deleted; use the documented cancellation, return, credit-note, or void workflow'
   using errcode='check_violation';
 end if;
 if tg_table_name='sales_invoices'and exists(
  select 1 from public.sales_payments payment where payment.invoice_id=old.id and payment.deleted_at is null
 )then raise exception 'Invoice with active payments cannot be deleted'using errcode='check_violation';end if;
 if tg_table_name='purchase_invoices'and exists(
  select 1 from public.purchase_payments payment where payment.invoice_id=old.id and payment.deleted_at is null
 )then raise exception 'Invoice with active payments cannot be deleted'using errcode='check_violation';end if;
 return old;
end;$$;
drop trigger if exists aaa_guard_posted_sales_invoice_delete on public.sales_invoices;
create trigger aaa_guard_posted_sales_invoice_delete before delete on public.sales_invoices
 for each row execute function public.guard_posted_invoice_delete();
drop trigger if exists aaa_guard_posted_purchase_invoice_delete on public.purchase_invoices;
create trigger aaa_guard_posted_purchase_invoice_delete before delete on public.purchase_invoices
 for each row execute function public.guard_posted_invoice_delete();

commit;
