-- Make purchase-receipt shadow mode observable without changing the legacy
-- writer or any inventory/accounting behavior.
begin;

create table if not exists public.purchase_receipt_compatibility_events(
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  purchase_invoice_id uuid not null references public.purchase_invoices(id) on delete restrict,
  operation_id uuid,
  event_type text not null check(event_type in('legacy_status_received')),
  old_status text,
  new_status text not null,
  control_mode text not null check(control_mode in('shadow')),
  actor_id uuid references auth.users(id) on delete set null,
  transaction_id bigint not null,
  client_context jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default clock_timestamp(),
  foreign key(tenant_id,operation_id)
    references public.inventory_accounting_operations(tenant_id,id) on delete restrict
);

create index if not exists idx_purchase_receipt_compatibility_tenant_time
  on public.purchase_receipt_compatibility_events(tenant_id,occurred_at desc);
create index if not exists idx_purchase_receipt_compatibility_invoice
  on public.purchase_receipt_compatibility_events(tenant_id,purchase_invoice_id,occurred_at desc);
create index if not exists idx_purchase_receipt_compatibility_operation
  on public.purchase_receipt_compatibility_events(tenant_id,operation_id)
  where operation_id is not null;

alter table public.purchase_receipt_compatibility_events enable row level security;
drop policy if exists purchase_receipt_compatibility_events_select
  on public.purchase_receipt_compatibility_events;
create policy purchase_receipt_compatibility_events_select
  on public.purchase_receipt_compatibility_events
  for select to authenticated
  using(tenant_id=public.user_tenant_id());
revoke insert,update,delete on public.purchase_receipt_compatibility_events
  from public,anon,authenticated;
grant select on public.purchase_receipt_compatibility_events to authenticated;

create or replace function public.prevent_purchase_receipt_compatibility_event_mutation()
returns trigger
language plpgsql
set search_path=public
as $$
begin
  raise exception 'Purchase receipt compatibility events are append-only'
    using errcode='check_violation';
end;
$$;

drop trigger if exists trg_purchase_receipt_compatibility_events_immutable
  on public.purchase_receipt_compatibility_events;
create trigger trg_purchase_receipt_compatibility_events_immutable
before update or delete on public.purchase_receipt_compatibility_events
for each row execute function public.prevent_purchase_receipt_compatibility_event_mutation();

create or replace function public.observe_legacy_purchase_receipt_transition()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_mode text:='disabled';
  v_operation_text text:=nullif(current_setting('app.inventory_operation_id',true),'');
  v_operation_id uuid;
begin
  if lower(coalesce(new.status,''))<>'received'
     or lower(coalesce(old.status,''))='received'then
    return new;
  end if;

  select coalesce(setting.control_mode,'disabled') into v_mode
    from (select 1) seed
    left join public.purchase_receipt_control_settings setting
      on setting.tenant_id=new.tenant_id;
  if v_mode<>'shadow'then return new;end if;

  if v_operation_text is not null and exists(
    select 1 from public.inventory_accounting_operations operation
     where operation.id=v_operation_text::uuid and operation.tenant_id=new.tenant_id
  )then v_operation_id:=v_operation_text::uuid;end if;

  insert into public.purchase_receipt_compatibility_events(
    tenant_id,purchase_invoice_id,operation_id,event_type,old_status,new_status,
    control_mode,actor_id,transaction_id,client_context
  )values(
    new.tenant_id,new.id,v_operation_id,'legacy_status_received',old.status,new.status,
    'shadow',auth.uid(),txid_current(),jsonb_build_object(
      'application_name',current_setting('application_name',true),
      'database_role',current_user,
      'invoice_number',new.invoice_number,
      'received_date',new.received_date
    )
  );
  return new;
end;
$$;

revoke all on function public.observe_legacy_purchase_receipt_transition()
  from public,anon,authenticated;

drop trigger if exists zzy_observe_legacy_purchase_receipt_transition
  on public.purchase_invoices;
create trigger zzy_observe_legacy_purchase_receipt_transition
after update of status on public.purchase_invoices
for each row execute function public.observe_legacy_purchase_receipt_transition();

comment on table public.purchase_receipt_compatibility_events is
  'Append-only shadow evidence of legacy invoice-status receiving, used to gate professional receipt enforcement.';

commit;
