-- Deployment status: DEPLOYED and registered on production
-- xzdvtzdqjeyqxnkqprtf on 2026-08-16; exact catalog/ATP read-back passed.
--
-- Purpose:
--   Add workshop stock commitments without replacing the proven online-order
--   reservation lifecycle. Both ledgers feed one ATP authority, share the same
--   tenant advisory lock, and are protected by one capacity check. A workshop
--   commitment never changes physical stock; a linked posted sales invoice
--   remains the sole owner of inventory movements and atomically consumes the
--   commitment that belongs to its job.
--
-- Forward behavior:
--   Additive workshop ledger/read models/commands plus compatible replacements
--   of the existing availability and reservation-floor functions. The public
--   catalog and set availability keep their signatures and inherit common ATP.
-- Recovery behavior:
--   Disable workshop assignment entry points while preserving commitment and
--   event evidence. Replacing online_product_available_quantity with its prior
--   body restores online-only reads without deleting workshop rows.

begin;

set local lock_timeout = '750ms';
set local statement_timeout = '30s';

create table if not exists public.workshop_inventory_commitments (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete restrict,
  supply_need_id uuid not null,
  source_product_id uuid not null,
  product_id uuid not null,
  quantity integer not null check (quantity > 0),
  state text not null default 'active' check (
    state in ('active', 'consuming', 'consumed', 'released')
  ),
  cycle integer not null default 1 check (cycle > 0),
  version bigint not null default 1 check (version > 0),
  assigned_at timestamptz not null default clock_timestamp(),
  review_due_at timestamptz not null default (
    clock_timestamp() + interval '30 days'
  ),
  consumption_started_at timestamptz,
  consumed_at timestamptz,
  released_at timestamptz,
  release_reason text,
  sales_invoice_id uuid references public.sales_invoices(id) on delete restrict,
  stock_movement_ids uuid[] not null default array[]::uuid[],
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default clock_timestamp(),
  unique (tenant_id, id),
  unique (tenant_id, supply_need_id, product_id),
  foreign key (tenant_id, supply_need_id)
    references public.supply_needs(tenant_id, id) on delete restrict,
  foreign key (tenant_id, source_product_id)
    references public.products(tenant_id, id) on delete restrict,
  foreign key (tenant_id, product_id)
    references public.products(tenant_id, id) on delete restrict,
  check (state <> 'consuming' or consumption_started_at is not null),
  check (state <> 'consumed' or consumed_at is not null),
  check (
    state <> 'released'
    or (released_at is not null and btrim(coalesce(release_reason, '')) <> '')
  )
);

create index if not exists idx_workshop_inventory_commitments_product_active
  on public.workshop_inventory_commitments(
    tenant_id, product_id, review_due_at, supply_need_id
  ) where state = 'active';
create index if not exists idx_workshop_inventory_commitments_need
  on public.workshop_inventory_commitments(
    tenant_id, supply_need_id, state, product_id
  );
create index if not exists idx_workshop_inventory_commitments_invoice
  on public.workshop_inventory_commitments(tenant_id, sales_invoice_id)
  where sales_invoice_id is not null;

create table if not exists public.workshop_inventory_commitment_events (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete restrict,
  commitment_id uuid not null,
  supply_need_id uuid not null,
  source_product_id uuid not null,
  product_id uuid not null,
  event_type text not null check (event_type in (
    'assigned', 'reassigned', 'released',
    'consumption_started', 'consumed', 'reactivated'
  )),
  from_state text,
  to_state text not null,
  quantity integer not null check (quantity > 0),
  cycle integer not null check (cycle > 0),
  actor_id uuid references auth.users(id) on delete set null,
  executor text not null check (btrim(executor) <> ''),
  operation_key text not null check (
    btrim(operation_key) <> '' and octet_length(operation_key) <= 200
  ),
  payload jsonb not null default '{}'::jsonb check (
    jsonb_typeof(payload) = 'object'
    and not public.jsonb_contains_sensitive_key(payload)
  ),
  occurred_at timestamptz not null default clock_timestamp(),
  unique (tenant_id, operation_key),
  foreign key (tenant_id, commitment_id)
    references public.workshop_inventory_commitments(tenant_id, id)
      on delete restrict,
  foreign key (tenant_id, supply_need_id)
    references public.supply_needs(tenant_id, id) on delete restrict,
  foreign key (tenant_id, source_product_id)
    references public.products(tenant_id, id) on delete restrict,
  foreign key (tenant_id, product_id)
    references public.products(tenant_id, id) on delete restrict
);

create index if not exists idx_workshop_inventory_commitment_events_need
  on public.workshop_inventory_commitment_events(
    tenant_id, supply_need_id, occurred_at desc, id desc
  );
create index if not exists idx_workshop_inventory_commitment_events_commitment
  on public.workshop_inventory_commitment_events(commitment_id, id);

alter table public.workshop_inventory_commitments enable row level security;
alter table public.workshop_inventory_commitment_events enable row level security;

drop policy if exists workshop_inventory_commitments_select
  on public.workshop_inventory_commitments;
create policy workshop_inventory_commitments_select
  on public.workshop_inventory_commitments
  for select to authenticated
  using (tenant_id = public.user_tenant_id());

drop policy if exists workshop_inventory_commitment_events_select
  on public.workshop_inventory_commitment_events;
create policy workshop_inventory_commitment_events_select
  on public.workshop_inventory_commitment_events
  for select to authenticated
  using (tenant_id = public.user_tenant_id());

revoke all on public.workshop_inventory_commitments
  from public, anon, authenticated, service_role;
revoke all on public.workshop_inventory_commitment_events
  from public, anon, authenticated, service_role;
grant select on public.workshop_inventory_commitments to authenticated;
grant select on public.workshop_inventory_commitment_events to authenticated;

drop trigger if exists trg_workshop_inventory_commitment_events_immutable
  on public.workshop_inventory_commitment_events;
create trigger trg_workshop_inventory_commitment_events_immutable
  before update or delete on public.workshop_inventory_commitment_events
  for each row execute function public.prevent_supply_kernel_evidence_mutation();

create or replace function public.append_workshop_inventory_commitment_event_v1(
  p_commitment public.workshop_inventory_commitments,
  p_event_type text,
  p_from_state text,
  p_to_state text,
  p_executor text,
  p_operation_key text,
  p_payload jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if p_commitment.id is null
     or btrim(coalesce(p_executor, '')) = ''
     or btrim(coalesce(p_operation_key, '')) = '' then
    raise exception 'La identidad del evento de compromiso es obligatoria.'
      using errcode = '22023';
  end if;

  insert into public.workshop_inventory_commitment_events (
    tenant_id, commitment_id, supply_need_id, source_product_id, product_id,
    event_type, from_state, to_state, quantity, cycle, actor_id, executor,
    operation_key, payload, occurred_at
  ) values (
    p_commitment.tenant_id, p_commitment.id, p_commitment.supply_need_id,
    p_commitment.source_product_id, p_commitment.product_id,
    p_event_type, p_from_state, p_to_state, p_commitment.quantity,
    p_commitment.cycle, auth.uid(), btrim(p_executor),
    btrim(p_operation_key), coalesce(p_payload, '{}'::jsonb), clock_timestamp()
  ) on conflict (tenant_id, operation_key) do nothing
  returning id into v_id;

  if v_id is null then
    select event.id into v_id
    from public.workshop_inventory_commitment_events event
    where event.tenant_id = p_commitment.tenant_id
      and event.operation_key = btrim(p_operation_key)
      and event.commitment_id = p_commitment.id
      and event.event_type = p_event_type;
    if not found then
      raise exception 'La clave del evento pertenece a otro compromiso.'
        using errcode = '23505';
    end if;
  end if;
  return v_id;
end;
$$;

revoke all on function public.append_workshop_inventory_commitment_event_v1(
  public.workshop_inventory_commitments,
  text, text, text, text, text, jsonb
) from public, anon, authenticated, service_role;

create or replace view public.active_inventory_commitments_v1
with (security_invoker = true)
as
select
  reservation.tenant_id,
  'online_order'::text as source_kind,
  reservation.id as commitment_id,
  reservation.order_id as source_id,
  reservation.product_id,
  reservation.quantity,
  reservation.reserved_at as committed_at,
  reservation.expires_at as review_or_expiry_at
from public.online_order_inventory_reservations reservation
where reservation.state = 'active'
  and reservation.expires_at > clock_timestamp()
union all
select
  commitment.tenant_id,
  'workshop_need'::text as source_kind,
  commitment.id as commitment_id,
  commitment.supply_need_id as source_id,
  commitment.product_id,
  commitment.quantity,
  commitment.assigned_at as committed_at,
  commitment.review_due_at as review_or_expiry_at
from public.workshop_inventory_commitments commitment
where commitment.state = 'active';

revoke all on public.active_inventory_commitments_v1
  from public, anon, authenticated, service_role;
grant select on public.active_inventory_commitments_v1 to authenticated;

create or replace function public.inventory_available_quantity_v1(
  p_tenant_id uuid,
  p_product_id uuid
)
returns integer
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_product public.products%rowtype;
  v_available integer;
begin
  select product.* into v_product
  from public.products product
  where product.tenant_id = p_tenant_id and product.id = p_product_id;
  if not found then
    return 0;
  end if;

  if coalesce(v_product.is_service, false)
     or coalesce(v_product.product_type, 'product') = 'service'
     or not coalesce(v_product.track_stock, true) then
    return greatest(
      coalesce(v_product.stock_quantity, v_product.inventory_qty, 0), 0
    );
  end if;

  if coalesce(v_product.is_set, false) then
    select min(greatest(floor(
      (
        coalesce(component.stock_quantity, component.inventory_qty, 0)
        - coalesce(committed.quantity, 0)
      )::numeric / set_component.quantity_in_set
    ), 0))::integer
    into v_available
    from public.product_set_components set_component
    join public.products component
      on component.tenant_id = set_component.tenant_id
     and component.id = set_component.component_product_id
    left join lateral (
      select coalesce(sum(active.quantity), 0)::integer as quantity
      from public.active_inventory_commitments_v1 active
      where active.tenant_id = component.tenant_id
        and active.product_id = component.id
    ) committed on true
    where set_component.tenant_id = p_tenant_id
      and set_component.set_product_id = p_product_id;
    return greatest(coalesce(v_available, 0), 0);
  end if;

  select greatest(
    coalesce(v_product.stock_quantity, v_product.inventory_qty, 0)
      - coalesce(sum(active.quantity), 0),
    0
  )::integer
  into v_available
  from public.active_inventory_commitments_v1 active
  where active.tenant_id = p_tenant_id
    and active.product_id = p_product_id;

  return greatest(coalesce(
    v_available,
    coalesce(v_product.stock_quantity, v_product.inventory_qty, 0)
  ), 0);
end;
$$;

revoke all on function public.inventory_available_quantity_v1(uuid, uuid)
  from public, anon, authenticated, service_role;

-- Preserve every existing caller while changing the implementation from
-- online-only availability to the common commitment authority.
create or replace function public.online_product_available_quantity(
  p_tenant_id uuid,
  p_product_id uuid
)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select public.inventory_available_quantity_v1(p_tenant_id, p_product_id)
$$;

revoke all on function public.online_product_available_quantity(uuid, uuid)
  from public, anon, authenticated, service_role;

create or replace function public.assert_inventory_commitment_capacity_v1(
  p_tenant_id uuid,
  p_product_id uuid,
  p_quantity integer,
  p_exclude_online_id uuid default null,
  p_exclude_workshop_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
set lock_timeout = '750ms'
as $$
declare
  v_product public.products%rowtype;
  v_online integer;
  v_workshop integer;
  v_physical integer;
  v_available integer;
begin
  if p_tenant_id is null or p_product_id is null
     or p_quantity is null or p_quantity <= 0 then
    raise exception 'El producto, tenant y cantidad del compromiso son obligatorios.'
      using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'online_inventory_reservation:' || p_tenant_id::text,
    0
  ));

  select product.* into v_product
  from public.products product
  where product.tenant_id = p_tenant_id and product.id = p_product_id
  for update;
  if not found then
    raise exception 'Producto físico no encontrado.' using errcode = 'P0002';
  end if;
  if coalesce(v_product.is_set, false)
     or coalesce(v_product.is_service, false)
     or coalesce(v_product.product_type, 'product') = 'service'
     or not coalesce(v_product.track_stock, true)
     or coalesce(v_product.purchase_treatment, 'inventory') <> 'inventory' then
    raise exception 'El compromiso requiere un producto físico inventariable.'
      using errcode = '23514';
  end if;
  if coalesce(v_product.inventory_qty, 0)
     <> coalesce(v_product.stock_quantity, 0) then
    raise exception 'Las columnas de stock no coinciden para %.', v_product.name
      using errcode = '23514';
  end if;

  select coalesce(sum(reservation.quantity), 0)::integer into v_online
  from public.online_order_inventory_reservations reservation
  where reservation.tenant_id = p_tenant_id
    and reservation.product_id = p_product_id
    and reservation.state = 'active'
    and reservation.expires_at > clock_timestamp()
    and (p_exclude_online_id is null or reservation.id <> p_exclude_online_id);

  select coalesce(sum(commitment.quantity), 0)::integer into v_workshop
  from public.workshop_inventory_commitments commitment
  where commitment.tenant_id = p_tenant_id
    and commitment.product_id = p_product_id
    and commitment.state = 'active'
    and (
      p_exclude_workshop_id is null
      or commitment.id <> p_exclude_workshop_id
    );

  v_physical := coalesce(
    v_product.stock_quantity, v_product.inventory_qty, 0
  );
  v_available := v_physical - v_online - v_workshop;
  if v_available < p_quantity then
    raise exception
      'Stock disponible insuficiente para %: solicitado %, ATP %.',
      v_product.name, p_quantity, greatest(v_available, 0)
      using errcode = '23514';
  end if;

  return jsonb_build_object(
    'product_id', v_product.id,
    'on_hand', v_physical,
    'online_committed', v_online,
    'workshop_committed', v_workshop,
    'atp_before', greatest(v_available, 0),
    'atp_after', greatest(v_available - p_quantity, 0)
  );
end;
$$;

revoke all on function public.assert_inventory_commitment_capacity_v1(
  uuid, uuid, integer, uuid, uuid
) from public, anon, authenticated, service_role;

create or replace function public.guard_online_inventory_common_capacity_v1()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.state = 'active' and new.expires_at > clock_timestamp()
     and (
       tg_op = 'INSERT'
       or old.state is distinct from new.state
       or old.quantity is distinct from new.quantity
       or old.product_id is distinct from new.product_id
       or old.expires_at is distinct from new.expires_at
     ) then
    perform public.assert_inventory_commitment_capacity_v1(
      new.tenant_id,
      new.product_id,
      new.quantity,
      case when tg_op = 'UPDATE' then old.id else null end,
      null
    );
  end if;
  return new;
end;
$$;

revoke all on function public.guard_online_inventory_common_capacity_v1()
  from public, anon, authenticated, service_role;

drop trigger if exists a0_guard_online_inventory_common_capacity_v1
  on public.online_order_inventory_reservations;
create trigger a0_guard_online_inventory_common_capacity_v1
  before insert or update of state, quantity, product_id, expires_at
  on public.online_order_inventory_reservations
  for each row execute function public.guard_online_inventory_common_capacity_v1();

create or replace function public.guard_workshop_inventory_common_capacity_v1()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.state = 'active'
     and (
       tg_op = 'INSERT'
       or old.state is distinct from new.state
       or old.quantity is distinct from new.quantity
       or old.product_id is distinct from new.product_id
     ) then
    perform public.assert_inventory_commitment_capacity_v1(
      new.tenant_id,
      new.product_id,
      new.quantity,
      null,
      case when tg_op = 'UPDATE' then old.id else null end
    );
  end if;
  return new;
end;
$$;

revoke all on function public.guard_workshop_inventory_common_capacity_v1()
  from public, anon, authenticated, service_role;

drop trigger if exists a0_guard_workshop_inventory_common_capacity_v1
  on public.workshop_inventory_commitments;
create trigger a0_guard_workshop_inventory_common_capacity_v1
  before insert or update of state, quantity, product_id
  on public.workshop_inventory_commitments
  for each row execute function public.guard_workshop_inventory_common_capacity_v1();

create or replace view public.inventory_availability_v1
with (security_invoker = true)
as
select
  product.tenant_id,
  product.id as product_id,
  product.name as product_name,
  product.sku,
  coalesce(product.stock_quantity, product.inventory_qty, 0)::integer
    as physical_quantity,
  coalesce(online.quantity, 0)::integer as online_committed_quantity,
  coalesce(workshop.quantity, 0)::integer as workshop_committed_quantity,
  (
    coalesce(online.quantity, 0) + coalesce(workshop.quantity, 0)
  )::integer as total_committed_quantity,
  public.inventory_available_quantity_v1(product.tenant_id, product.id)
    as available_to_promise,
  coalesce(product.track_stock, true) as track_stock,
  coalesce(product.is_set, false) as is_set,
  product.updated_at
from public.products product
left join lateral (
  select coalesce(sum(reservation.quantity), 0)::integer as quantity
  from public.online_order_inventory_reservations reservation
  where reservation.tenant_id = product.tenant_id
    and reservation.product_id = product.id
    and reservation.state = 'active'
    and reservation.expires_at > clock_timestamp()
) online on true
left join lateral (
  select coalesce(sum(commitment.quantity), 0)::integer as quantity
  from public.workshop_inventory_commitments commitment
  where commitment.tenant_id = product.tenant_id
    and commitment.product_id = product.id
    and commitment.state = 'active'
) workshop on true;

revoke all on public.inventory_availability_v1
  from public, anon, authenticated, service_role;
grant select on public.inventory_availability_v1 to authenticated;

create or replace view public.supply_need_inventory_resolution_v1
with (security_invoker = true)
as
select
  need.tenant_id,
  need.id as supply_need_id,
  need.product_id as source_product_id,
  need.quantity as requested_quantity,
  need.unit,
  need.supply_state,
  need.version as need_version,
  coalesce(sum(commitment.quantity) filter (
    where commitment.state = 'active'
  ), 0)::integer as active_physical_quantity,
  coalesce(count(commitment.id) filter (
    where commitment.state = 'active'
  ), 0)::integer as active_component_count,
  min(commitment.review_due_at) filter (
    where commitment.state = 'active'
  ) as next_review_at,
  bool_or(
    commitment.state = 'active'
    and commitment.review_due_at <= clock_timestamp()
  ) as review_overdue
from public.supply_needs need
left join public.workshop_inventory_commitments commitment
  on commitment.tenant_id = need.tenant_id
 and commitment.supply_need_id = need.id
group by need.tenant_id, need.id, need.product_id, need.quantity,
  need.unit, need.supply_state, need.version;

revoke all on public.supply_need_inventory_resolution_v1
  from public, anon, authenticated, service_role;
grant select on public.supply_need_inventory_resolution_v1 to authenticated;

create or replace function public.get_supply_need_inventory_snapshot_v1(
  p_need_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_tenant_id uuid := public.user_tenant_id();
  v_actor_id uuid := auth.uid();
  v_need public.supply_needs%rowtype;
  v_product public.products%rowtype;
  v_components jsonb;
begin
  if v_tenant_id is null or v_actor_id is null then
    raise exception 'No hay una sesión de negocio activa.' using errcode = '42501';
  end if;
  select need.* into v_need
  from public.supply_needs need
  where need.tenant_id = v_tenant_id and need.id = p_need_id;
  if not found then
    raise exception 'Necesidad no encontrada.' using errcode = 'P0002';
  end if;
  if v_need.product_id is null then
    return jsonb_build_object(
      'need_id', v_need.id,
      'identity_state', v_need.identity_state,
      'assignable', false,
      'reason', 'identity_unresolved',
      'components', '[]'::jsonb
    );
  end if;

  select product.* into v_product
  from public.products product
  where product.tenant_id = v_tenant_id and product.id = v_need.product_id;

  select coalesce(jsonb_agg(jsonb_build_object(
    'product_id', requirement.product_id,
    'name', component.name,
    'sku', component.sku,
    'quantity_in_set', requirement.quantity_in_set,
    'required_quantity', requirement.required_quantity,
    'on_hand', coalesce(component.stock_quantity, component.inventory_qty, 0),
    'online_committed', coalesce(online.quantity, 0),
    'workshop_committed', coalesce(workshop.quantity, 0),
    'atp', public.inventory_available_quantity_v1(
      v_tenant_id, requirement.product_id
    )
  ) order by requirement.product_id), '[]'::jsonb)
  into v_components
  from (
    select v_product.id as product_id,
           1::integer as quantity_in_set,
           v_need.quantity::integer as required_quantity
    where not coalesce(v_product.is_set, false)
    union all
    select map.component_product_id,
           map.quantity_in_set,
           (v_need.quantity::integer * map.quantity_in_set)::integer
    from public.product_set_components map
    where map.tenant_id = v_tenant_id
      and map.set_product_id = v_product.id
      and coalesce(v_product.is_set, false)
  ) requirement
  join public.products component
    on component.tenant_id = v_tenant_id
   and component.id = requirement.product_id
  left join lateral (
    select coalesce(sum(reservation.quantity), 0)::integer as quantity
    from public.online_order_inventory_reservations reservation
    where reservation.tenant_id = v_tenant_id
      and reservation.product_id = requirement.product_id
      and reservation.state = 'active'
      and reservation.expires_at > clock_timestamp()
  ) online on true
  left join lateral (
    select coalesce(sum(commitment.quantity), 0)::integer as quantity
    from public.workshop_inventory_commitments commitment
    where commitment.tenant_id = v_tenant_id
      and commitment.product_id = requirement.product_id
      and commitment.state = 'active'
  ) workshop on true;

  return jsonb_build_object(
    'need_id', v_need.id,
    'need_version', v_need.version,
    'source_product_id', v_product.id,
    'source_product_name', v_product.name,
    'is_set', coalesce(v_product.is_set, false),
    'requested_quantity', v_need.quantity,
    'unit', v_need.unit,
    'available_to_promise', public.inventory_available_quantity_v1(
      v_tenant_id, v_product.id
    ),
    'assignable', (
      v_need.unit = 'unit'
      and v_need.quantity = trunc(v_need.quantity)
      and public.inventory_available_quantity_v1(v_tenant_id, v_product.id)
          >= v_need.quantity
    ),
    'components', v_components
  );
end;
$$;

revoke all on function public.get_supply_need_inventory_snapshot_v1(uuid)
  from public, anon, authenticated, service_role;
grant execute on function public.get_supply_need_inventory_snapshot_v1(uuid)
  to authenticated;

create or replace function public.assign_supply_need_from_stock_v1(
  p_need_id uuid,
  p_expected_version bigint,
  p_operation_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
set lock_timeout = '750ms'
as $$
declare
  v_tenant_id uuid := public.user_tenant_id();
  v_actor_id uuid := auth.uid();
  v_operation_key text := btrim(coalesce(p_operation_key, ''));
  v_request jsonb;
  v_response jsonb;
  v_receipt public.supply_need_events%rowtype;
  v_need public.supply_needs%rowtype;
  v_source public.products%rowtype;
  v_target record;
  v_target_product public.products%rowtype;
  v_commitment public.workshop_inventory_commitments%rowtype;
  v_existing public.workshop_inventory_commitments%rowtype;
  v_was_existing boolean;
  v_capacity jsonb;
  v_components jsonb := '[]'::jsonb;
  v_target_count integer := 0;
begin
  if v_tenant_id is null or v_actor_id is null then
    raise exception 'No hay una sesión de negocio activa.' using errcode = '42501';
  end if;
  if p_need_id is null or p_expected_version is null
     or v_operation_key = '' or octet_length(v_operation_key) > 200 then
    raise exception 'La necesidad, versión y clave son obligatorias.'
      using errcode = '22023';
  end if;

  v_request := jsonb_build_object(
    'need_id', p_need_id,
    'expected_version', p_expected_version
  );
  select event.* into v_receipt
  from public.supply_need_events event
  where event.tenant_id = v_tenant_id
    and event.operation_key = v_operation_key;
  if found then
    if v_receipt.action <> 'stock_assigned'
       or v_receipt.supply_need_id <> p_need_id
       or v_receipt.request_snapshot is distinct from v_request then
      raise exception 'La clave de operación pertenece a otra asignación.'
        using errcode = '23505';
    end if;
    return to_jsonb(v_receipt) || v_receipt.response_snapshot
      || jsonb_build_object('replay', true);
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'online_inventory_reservation:' || v_tenant_id::text,
    0
  ));

  select need.* into v_need
  from public.supply_needs need
  where need.tenant_id = v_tenant_id and need.id = p_need_id
  for update;
  if not found then
    raise exception 'Necesidad no encontrada.' using errcode = 'P0002';
  end if;
  if v_need.version <> p_expected_version then
    raise exception 'La necesidad cambió; vuelve a cargarla antes de asignar.'
      using errcode = '40001';
  end if;
  if v_need.supply_state <> 'open' then
    raise exception 'La necesidad no está disponible para asignar stock.'
      using errcode = '55000';
  end if;
  if v_need.product_id is null or v_need.identity_state <> 'confirmed' then
    raise exception 'Confirma primero la identidad del producto.'
      using errcode = '23514';
  end if;
  if v_need.unit <> 'unit' or v_need.quantity <> trunc(v_need.quantity) then
    raise exception 'El stock inventariable se asigna en unidades enteras.'
      using errcode = '23514';
  end if;

  select product.* into v_source
  from public.products product
  where product.tenant_id = v_tenant_id
    and product.id = v_need.product_id
    and product.is_active is true
  for share;
  if not found
     or coalesce(v_source.is_service, false)
     or coalesce(v_source.product_type, 'product') = 'service'
     or not coalesce(v_source.track_stock, true)
     or coalesce(v_source.purchase_treatment, 'inventory') <> 'inventory' then
    raise exception 'El producto confirmado no es inventariable.'
      using errcode = '23514';
  end if;
  if coalesce(v_source.is_set, false) and not exists (
    select 1 from public.product_set_components map
    where map.tenant_id = v_tenant_id and map.set_product_id = v_source.id
  ) then
    raise exception 'El set confirmado no tiene componentes canónicos.'
      using errcode = '23514';
  end if;

  for v_target in
    select requirement.product_id, requirement.required_quantity
    from (
      select v_source.id as product_id,
             v_need.quantity::integer as required_quantity
      where not coalesce(v_source.is_set, false)
      union all
      select map.component_product_id,
             (v_need.quantity::integer * map.quantity_in_set)::integer
      from public.product_set_components map
      where map.tenant_id = v_tenant_id
        and map.set_product_id = v_source.id
        and coalesce(v_source.is_set, false)
    ) requirement
    order by requirement.product_id
  loop
    v_target_count := v_target_count + 1;
    select product.* into v_target_product
    from public.products product
    where product.tenant_id = v_tenant_id
      and product.id = v_target.product_id
      and product.is_active is true
    for update;
    if not found then
      raise exception 'Un componente físico no existe o está inactivo.'
        using errcode = '23514';
    end if;

    select commitment.* into v_existing
    from public.workshop_inventory_commitments commitment
    where commitment.tenant_id = v_tenant_id
      and commitment.supply_need_id = v_need.id
      and commitment.product_id = v_target.product_id
    for update;
    v_was_existing := found;
    if v_was_existing and v_existing.state in ('active', 'consuming', 'consumed') then
      raise exception 'La necesidad ya conserva un compromiso vigente o consumido.'
        using errcode = '55000';
    end if;

    v_capacity := public.assert_inventory_commitment_capacity_v1(
      v_tenant_id,
      v_target.product_id,
      v_target.required_quantity,
      null,
      case when v_was_existing then v_existing.id else null end
    );

    if v_was_existing then
      update public.workshop_inventory_commitments commitment
      set source_product_id = v_source.id,
          quantity = v_target.required_quantity,
          state = 'active',
          cycle = commitment.cycle + 1,
          version = commitment.version + 1,
          assigned_at = clock_timestamp(),
          review_due_at = clock_timestamp() + interval '30 days',
          consumption_started_at = null,
          consumed_at = null,
          released_at = null,
          release_reason = null,
          sales_invoice_id = null,
          stock_movement_ids = array[]::uuid[],
          updated_by = v_actor_id,
          updated_at = clock_timestamp()
      where commitment.tenant_id = v_tenant_id
        and commitment.id = v_existing.id
      returning commitment.* into v_commitment;
    else
      insert into public.workshop_inventory_commitments (
        tenant_id, supply_need_id, source_product_id, product_id, quantity,
        state, assigned_at, review_due_at, created_by, updated_by
      ) values (
        v_tenant_id, v_need.id, v_source.id, v_target.product_id,
        v_target.required_quantity, 'active', clock_timestamp(),
        clock_timestamp() + interval '30 days', v_actor_id, v_actor_id
      ) returning * into v_commitment;
    end if;

    perform public.append_workshop_inventory_commitment_event_v1(
      v_commitment,
      case when v_was_existing then 'reassigned' else 'assigned' end,
      case when v_was_existing then v_existing.state else null end,
      'active',
      'supply_need_command',
      'workshop-commitment-assigned:' || v_commitment.id::text || ':'
        || v_commitment.cycle::text,
      v_capacity || jsonb_build_object('source_product_id', v_source.id)
    );
    v_components := v_components || jsonb_build_array(jsonb_build_object(
      'commitment_id', v_commitment.id,
      'product_id', v_commitment.product_id,
      'quantity', v_commitment.quantity,
      'capacity', v_capacity
    ));
  end loop;

  if v_target_count = 0 then
    raise exception 'No se pudo resolver ningún componente físico.'
      using errcode = '23514';
  end if;

  update public.supply_needs need
  set supply_state = 'committed',
      version = need.version + 1,
      internal_stock_rejection_reason = null,
      internal_stock_rejected_at = null,
      internal_stock_rejected_by = null,
      updated_by = v_actor_id,
      updated_at = clock_timestamp()
  where need.tenant_id = v_tenant_id and need.id = v_need.id
  returning * into v_need;

  v_response := jsonb_build_object(
    'need_id', v_need.id,
    'changed', true,
    'version', v_need.version,
    'need', to_jsonb(v_need),
    'commitments', v_components
  );
  insert into public.supply_need_events (
    tenant_id, supply_need_id, action, changed, actor_id, operation_key,
    request_snapshot, response_snapshot, occurred_at
  ) values (
    v_tenant_id, v_need.id, 'stock_assigned', true, v_actor_id,
    v_operation_key, v_request, v_response, clock_timestamp()
  ) returning * into v_receipt;

  return to_jsonb(v_receipt) || v_response
    || jsonb_build_object('replay', false);
end;
$$;

create or replace function public.release_supply_need_stock_v1(
  p_need_id uuid,
  p_expected_version bigint,
  p_reason text,
  p_operation_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
set lock_timeout = '750ms'
as $$
declare
  v_tenant_id uuid := public.user_tenant_id();
  v_actor_id uuid := auth.uid();
  v_operation_key text := btrim(coalesce(p_operation_key, ''));
  v_reason text := btrim(coalesce(p_reason, ''));
  v_request jsonb;
  v_response jsonb;
  v_receipt public.supply_need_events%rowtype;
  v_need public.supply_needs%rowtype;
  v_commitment public.workshop_inventory_commitments%rowtype;
  v_released integer := 0;
begin
  if v_tenant_id is null or v_actor_id is null then
    raise exception 'No hay una sesión de negocio activa.' using errcode = '42501';
  end if;
  if p_need_id is null or p_expected_version is null
     or v_reason = '' or octet_length(v_reason) > 500
     or v_operation_key = '' or octet_length(v_operation_key) > 200 then
    raise exception 'La liberación requiere necesidad, versión, motivo y clave.'
      using errcode = '22023';
  end if;
  v_request := jsonb_build_object(
    'need_id', p_need_id,
    'expected_version', p_expected_version,
    'reason', v_reason
  );

  select event.* into v_receipt
  from public.supply_need_events event
  where event.tenant_id = v_tenant_id
    and event.operation_key = v_operation_key;
  if found then
    if v_receipt.action <> 'stock_released'
       or v_receipt.supply_need_id <> p_need_id
       or v_receipt.request_snapshot is distinct from v_request then
      raise exception 'La clave de operación pertenece a otra liberación.'
        using errcode = '23505';
    end if;
    return to_jsonb(v_receipt) || v_receipt.response_snapshot
      || jsonb_build_object('replay', true);
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'online_inventory_reservation:' || v_tenant_id::text,
    0
  ));
  select need.* into v_need
  from public.supply_needs need
  where need.tenant_id = v_tenant_id and need.id = p_need_id
  for update;
  if not found then
    raise exception 'Necesidad no encontrada.' using errcode = 'P0002';
  end if;
  if v_need.version <> p_expected_version then
    raise exception 'La necesidad cambió; vuelve a cargarla antes de liberar.'
      using errcode = '40001';
  end if;
  if v_need.supply_state in ('in_purchase', 'received', 'covered', 'cancelled') then
    raise exception 'La resolución actual no permite liberar stock.'
      using errcode = '55000';
  end if;

  for v_commitment in
    update public.workshop_inventory_commitments commitment
    set state = 'released',
        released_at = clock_timestamp(),
        release_reason = v_reason,
        version = commitment.version + 1,
        updated_by = v_actor_id,
        updated_at = clock_timestamp()
    where commitment.tenant_id = v_tenant_id
      and commitment.supply_need_id = v_need.id
      and commitment.state = 'active'
    returning commitment.*
  loop
    perform public.append_workshop_inventory_commitment_event_v1(
      v_commitment, 'released', 'active', 'released',
      'supply_need_command',
      'workshop-commitment-released:' || v_commitment.id::text || ':'
        || v_commitment.cycle::text,
      jsonb_build_object('reason', v_reason)
    );
    v_released := v_released + 1;
  end loop;

  if v_released > 0 then
    update public.supply_needs need
    set supply_state = 'open',
        version = need.version + 1,
        updated_by = v_actor_id,
        updated_at = clock_timestamp()
    where need.tenant_id = v_tenant_id and need.id = v_need.id
    returning * into v_need;
  end if;

  v_response := jsonb_build_object(
    'need_id', v_need.id,
    'changed', v_released > 0,
    'released_count', v_released,
    'version', v_need.version,
    'need', to_jsonb(v_need)
  );
  insert into public.supply_need_events (
    tenant_id, supply_need_id, action, changed, actor_id, operation_key,
    request_snapshot, response_snapshot, occurred_at
  ) values (
    v_tenant_id, v_need.id, 'stock_released', v_released > 0, v_actor_id,
    v_operation_key, v_request, v_response, clock_timestamp()
  ) returning * into v_receipt;
  return to_jsonb(v_receipt) || v_response
    || jsonb_build_object('replay', false);
end;
$$;

create or replace function public.reject_supply_need_internal_stock_v1(
  p_need_id uuid,
  p_expected_version bigint,
  p_reason text,
  p_operation_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
set lock_timeout = '750ms'
as $$
declare
  v_tenant_id uuid := public.user_tenant_id();
  v_actor_id uuid := auth.uid();
  v_operation_key text := btrim(coalesce(p_operation_key, ''));
  v_reason text := btrim(coalesce(p_reason, ''));
  v_request jsonb;
  v_response jsonb;
  v_receipt public.supply_need_events%rowtype;
  v_need public.supply_needs%rowtype;
  v_atp integer;
  v_changed boolean;
begin
  if v_tenant_id is null or v_actor_id is null then
    raise exception 'No hay una sesión de negocio activa.' using errcode = '42501';
  end if;
  if p_need_id is null or p_expected_version is null
     or v_reason = '' or octet_length(v_reason) > 500
     or v_operation_key = '' or octet_length(v_operation_key) > 200 then
    raise exception 'El rechazo requiere necesidad, versión, motivo y clave.'
      using errcode = '22023';
  end if;
  v_request := jsonb_build_object(
    'need_id', p_need_id,
    'expected_version', p_expected_version,
    'reason', v_reason
  );
  select event.* into v_receipt
  from public.supply_need_events event
  where event.tenant_id = v_tenant_id
    and event.operation_key = v_operation_key;
  if found then
    if v_receipt.action <> 'internal_stock_rejected'
       or v_receipt.supply_need_id <> p_need_id
       or v_receipt.request_snapshot is distinct from v_request then
      raise exception 'La clave de operación pertenece a otro rechazo.'
        using errcode = '23505';
    end if;
    return to_jsonb(v_receipt) || v_receipt.response_snapshot
      || jsonb_build_object('replay', true);
  end if;

  select need.* into v_need
  from public.supply_needs need
  where need.tenant_id = v_tenant_id and need.id = p_need_id
  for update;
  if not found then
    raise exception 'Necesidad no encontrada.' using errcode = 'P0002';
  end if;
  if v_need.version <> p_expected_version then
    raise exception 'La necesidad cambió; vuelve a cargarla antes de rechazar.'
      using errcode = '40001';
  end if;
  if v_need.supply_state <> 'open' or v_need.product_id is null
     or v_need.identity_state <> 'confirmed'
     or v_need.unit <> 'unit' or v_need.quantity <> trunc(v_need.quantity) then
    raise exception 'No existe una alternativa interna confirmada para rechazar.'
      using errcode = '55000';
  end if;
  v_atp := public.inventory_available_quantity_v1(
    v_tenant_id, v_need.product_id
  );
  if v_atp < v_need.quantity then
    raise exception 'No hay stock interno asignable; no requiere rechazo.'
      using errcode = '23514';
  end if;

  v_changed := v_need.internal_stock_rejection_reason is distinct from v_reason;
  if v_changed then
    update public.supply_needs need
    set internal_stock_rejection_reason = v_reason,
        internal_stock_rejected_at = clock_timestamp(),
        internal_stock_rejected_by = v_actor_id,
        version = need.version + 1,
        updated_by = v_actor_id,
        updated_at = clock_timestamp()
    where need.tenant_id = v_tenant_id and need.id = v_need.id
    returning * into v_need;
  end if;

  v_response := jsonb_build_object(
    'need_id', v_need.id,
    'changed', v_changed,
    'available_to_promise', v_atp,
    'version', v_need.version,
    'need', to_jsonb(v_need)
  );
  insert into public.supply_need_events (
    tenant_id, supply_need_id, action, changed, actor_id, operation_key,
    request_snapshot, response_snapshot, occurred_at
  ) values (
    v_tenant_id, v_need.id, 'internal_stock_rejected', v_changed, v_actor_id,
    v_operation_key, v_request, v_response, clock_timestamp()
  ) returning * into v_receipt;
  return to_jsonb(v_receipt) || v_response
    || jsonb_build_object('replay', false);
end;
$$;

revoke all on function public.assign_supply_need_from_stock_v1(
  uuid, bigint, text
) from public, anon, authenticated, service_role;
revoke all on function public.release_supply_need_stock_v1(
  uuid, bigint, text, text
) from public, anon, authenticated, service_role;
revoke all on function public.reject_supply_need_internal_stock_v1(
  uuid, bigint, text, text
) from public, anon, authenticated, service_role;
grant execute on function public.assign_supply_need_from_stock_v1(
  uuid, bigint, text
) to authenticated;
grant execute on function public.release_supply_need_stock_v1(
  uuid, bigint, text, text
) to authenticated;
grant execute on function public.reject_supply_need_internal_stock_v1(
  uuid, bigint, text, text
) to authenticated;

-- Cancellation now releases any active workshop commitment in the same
-- transaction. The signature remains compatible with the kernel migration.
create or replace function public.cancel_supply_need_v1(
  p_need_id uuid,
  p_expected_version bigint,
  p_reason text,
  p_operation_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
set lock_timeout = '750ms'
as $$
declare
  v_tenant_id uuid := public.user_tenant_id();
  v_actor_id uuid := auth.uid();
  v_operation_key text := btrim(coalesce(p_operation_key, ''));
  v_reason text := btrim(coalesce(p_reason, ''));
  v_request jsonb;
  v_response jsonb;
  v_event public.supply_need_events%rowtype;
  v_need public.supply_needs%rowtype;
  v_commitment public.workshop_inventory_commitments%rowtype;
  v_released integer := 0;
  v_changed boolean;
begin
  if v_tenant_id is null or v_actor_id is null then
    raise exception 'No hay una sesión de negocio activa.' using errcode = '42501';
  end if;
  if p_need_id is null or p_expected_version is null
     or v_reason = '' or octet_length(v_reason) > 500
     or v_operation_key = '' or octet_length(v_operation_key) > 200 then
    raise exception 'La cancelación requiere necesidad, versión y motivo.'
      using errcode = '22023';
  end if;
  v_request := jsonb_build_object(
    'need_id', p_need_id,
    'expected_version', p_expected_version,
    'reason', v_reason
  );
  select receipt.* into v_event
  from public.supply_need_events receipt
  where receipt.tenant_id = v_tenant_id
    and receipt.operation_key = v_operation_key;
  if found then
    if v_event.action <> 'cancelled'
       or v_event.supply_need_id <> p_need_id
       or v_event.request_snapshot is distinct from v_request then
      raise exception 'La clave de operación ya pertenece a otra cancelación.'
        using errcode = '23505';
    end if;
    return to_jsonb(v_event) || v_event.response_snapshot
      || jsonb_build_object('replay', true);
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'online_inventory_reservation:' || v_tenant_id::text,
    0
  ));
  select need.* into v_need
  from public.supply_needs need
  where need.tenant_id = v_tenant_id and need.id = p_need_id
  for update;
  if not found then
    raise exception 'Necesidad no encontrada.' using errcode = 'P0002';
  end if;
  if v_need.version <> p_expected_version then
    raise exception 'La necesidad cambió; vuelve a cargarla antes de cancelar.'
      using errcode = '40001';
  end if;
  if v_need.supply_state in ('in_purchase', 'received', 'covered') then
    raise exception 'La necesidad ya tiene evidencia posterior; corrígela desde su flujo.'
      using errcode = '55000';
  end if;

  for v_commitment in
    update public.workshop_inventory_commitments commitment
    set state = 'released',
        released_at = clock_timestamp(),
        release_reason = 'Necesidad cancelada: ' || v_reason,
        version = commitment.version + 1,
        updated_by = v_actor_id,
        updated_at = clock_timestamp()
    where commitment.tenant_id = v_tenant_id
      and commitment.supply_need_id = v_need.id
      and commitment.state = 'active'
    returning commitment.*
  loop
    perform public.append_workshop_inventory_commitment_event_v1(
      v_commitment, 'released', 'active', 'released',
      'supply_need_cancellation',
      'workshop-commitment-cancelled:' || v_commitment.id::text || ':'
        || v_commitment.cycle::text,
      jsonb_build_object('reason', v_reason)
    );
    v_released := v_released + 1;
  end loop;

  v_changed := v_need.supply_state <> 'cancelled';
  if v_changed then
    update public.supply_needs need
    set supply_state = 'cancelled',
        version = need.version + 1,
        updated_by = v_actor_id,
        updated_at = clock_timestamp(),
        cancelled_at = clock_timestamp(),
        cancelled_by = v_actor_id,
        cancellation_reason = v_reason
    where need.tenant_id = v_tenant_id and need.id = v_need.id
    returning * into v_need;
  end if;

  v_response := jsonb_build_object(
    'need_id', v_need.id,
    'changed', v_changed,
    'released_commitment_count', v_released,
    'version', v_need.version,
    'need', to_jsonb(v_need)
  );
  insert into public.supply_need_events (
    tenant_id, supply_need_id, action, changed, actor_id, operation_key,
    request_snapshot, response_snapshot, occurred_at
  ) values (
    v_tenant_id, v_need.id, 'cancelled', v_changed, v_actor_id,
    v_operation_key, v_request, v_response, clock_timestamp()
  ) returning * into v_event;
  return to_jsonb(v_event) || v_response
    || jsonb_build_object('replay', false);
end;
$$;

revoke all on function public.cancel_supply_need_v1(
  uuid, bigint, text, text
) from public, anon, authenticated, service_role;
grant execute on function public.cancel_supply_need_v1(
  uuid, bigint, text, text
) to authenticated;

create or replace function public.prepare_workshop_commitment_consumption_v1()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_non_posted constant text[] := array[
    'draft', 'borrador', 'sent', 'enviado', 'enviada',
    'issued', 'emitido', 'emitida',
    'cancelled', 'cancelado', 'cancelada', 'anulado', 'anulada'
  ];
  v_old_posted boolean := false;
  v_new_posted boolean;
  v_job public.mechanic_jobs%rowtype;
  v_group record;
  v_invoice_quantity integer;
  v_commitment public.workshop_inventory_commitments%rowtype;
begin
  v_new_posted := not (lower(coalesce(new.status, 'draft')) = any(v_non_posted));
  if tg_op = 'UPDATE' then
    v_old_posted := not (
      lower(coalesce(old.status, 'draft')) = any(v_non_posted)
    );
  end if;

  if tg_op = 'UPDATE' and v_old_posted and v_new_posted
     and public.invoice_inventory_signature(old.items)
         is distinct from public.invoice_inventory_signature(new.items)
     and exists (
       select 1 from public.workshop_inventory_commitments commitment
       where commitment.tenant_id = new.tenant_id
         and commitment.sales_invoice_id = new.id
         and commitment.state = 'consumed'
     ) then
    raise exception
      'La factura consumió stock comprometido del taller. Vuelve a borrador antes de editar sus productos.'
      using errcode = '55000';
  end if;

  if not v_new_posted or v_old_posted then
    return new;
  end if;

  select job.* into v_job
  from public.mechanic_jobs job
  where job.tenant_id = new.tenant_id
    and job.invoice_id = new.id
    and job.deleted_at is null
  order by job.created_at, job.id
  limit 1
  for update;
  if not found then
    return new;
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'online_inventory_reservation:' || new.tenant_id::text,
    0
  ));

  for v_group in
    select commitment.product_id,
           sum(commitment.quantity)::integer as committed_quantity
    from public.workshop_inventory_commitments commitment
    join public.supply_needs need
      on need.tenant_id = commitment.tenant_id
     and need.id = commitment.supply_need_id
    where commitment.tenant_id = new.tenant_id
      and need.mechanic_job_id = v_job.id
      and commitment.state = 'active'
    group by commitment.product_id
    order by commitment.product_id
  loop
    select coalesce(requirement.quantity, 0)::integer into v_invoice_quantity
    from public.sales_invoice_stock_requirements(new.tenant_id, new.items)
      requirement
    where requirement.product_id = v_group.product_id;
    v_invoice_quantity := coalesce(v_invoice_quantity, 0);
    if v_invoice_quantity = 0 then
      continue;
    end if;
    if v_invoice_quantity < v_group.committed_quantity then
      raise exception
        'La factura incluye menos unidades que el compromiso del taller para el producto %: factura %, compromiso %.',
        v_group.product_id, v_invoice_quantity, v_group.committed_quantity
        using errcode = '23514';
    end if;

    for v_commitment in
      update public.workshop_inventory_commitments commitment
      set state = 'consuming',
          consumption_started_at = clock_timestamp(),
          sales_invoice_id = case
            when tg_op = 'INSERT' then commitment.sales_invoice_id
            else new.id
          end,
          version = commitment.version + 1,
          updated_by = auth.uid(),
          updated_at = clock_timestamp()
      from public.supply_needs need
      where need.tenant_id = commitment.tenant_id
        and need.id = commitment.supply_need_id
        and commitment.tenant_id = new.tenant_id
        and need.mechanic_job_id = v_job.id
        and commitment.product_id = v_group.product_id
        and commitment.state = 'active'
      returning commitment.*
    loop
      perform public.append_workshop_inventory_commitment_event_v1(
        v_commitment, 'consumption_started', 'active', 'consuming',
        'sales_invoice_posting',
        'workshop-commitment-consume-start:' || v_commitment.id::text || ':'
          || new.id::text || ':' || v_commitment.cycle::text,
        jsonb_build_object('sales_invoice_id', new.id)
      );
    end loop;
  end loop;
  return new;
end;
$$;

revoke all on function public.prepare_workshop_commitment_consumption_v1()
  from public, anon, authenticated, service_role;

drop trigger if exists a1_workshop_commitment_prepare
  on public.sales_invoices;
create trigger a1_workshop_commitment_prepare
  before insert or update of status, items on public.sales_invoices
  for each row execute function public.prepare_workshop_commitment_consumption_v1();

create or replace function public.finalize_workshop_commitment_consumption_v1()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_non_posted constant text[] := array[
    'draft', 'borrador', 'sent', 'enviado', 'enviada',
    'issued', 'emitido', 'emitida',
    'cancelled', 'cancelado', 'cancelada', 'anulado', 'anulada'
  ];
  v_old_posted boolean := false;
  v_new_posted boolean;
  v_group record;
  v_moved integer;
  v_movement_ids uuid[];
  v_commitment public.workshop_inventory_commitments%rowtype;
  v_need public.supply_needs%rowtype;
  v_from_state text;
begin
  v_new_posted := not (lower(coalesce(new.status, 'draft')) = any(v_non_posted));
  if tg_op = 'UPDATE' then
    v_old_posted := not (
      lower(coalesce(old.status, 'draft')) = any(v_non_posted)
    );
  end if;

  if v_new_posted and not v_old_posted then
    for v_group in
      select commitment.product_id,
             sum(commitment.quantity)::integer as committed_quantity,
             array_agg(commitment.id order by commitment.id) as commitment_ids
      from public.workshop_inventory_commitments commitment
      where commitment.tenant_id = new.tenant_id
        and commitment.state = 'consuming'
        and (
          commitment.sales_invoice_id = new.id
          or commitment.sales_invoice_id is null
        )
      group by commitment.product_id
      order by commitment.product_id
    loop
      select greatest(coalesce(-sum(movement.quantity), 0), 0)::integer,
             coalesce(
               array_agg(movement.id order by movement.id)
                 filter (where movement.quantity < 0),
               array[]::uuid[]
             )
      into v_moved, v_movement_ids
      from public.stock_movements movement
      where movement.tenant_id = new.tenant_id
        and movement.product_id = v_group.product_id
        and movement.reference = 'sales_invoice:' || new.id::text;
      if v_moved < v_group.committed_quantity then
        raise exception
          'El movimiento de la factura no cubre el compromiso del taller para el producto %: compromiso %, movimiento %.',
          v_group.product_id, v_group.committed_quantity, v_moved
          using errcode = '23514';
      end if;

      for v_commitment in
        update public.workshop_inventory_commitments commitment
        set state = 'consumed',
            consumed_at = clock_timestamp(),
            sales_invoice_id = new.id,
            stock_movement_ids = v_movement_ids,
            version = commitment.version + 1,
            updated_by = auth.uid(),
            updated_at = clock_timestamp()
        where commitment.tenant_id = new.tenant_id
          and commitment.id = any(v_group.commitment_ids)
          and commitment.state = 'consuming'
        returning commitment.*
      loop
        perform public.append_workshop_inventory_commitment_event_v1(
          v_commitment, 'consumed', 'consuming', 'consumed',
          'sales_invoice_posting',
          'workshop-commitment-consumed:' || v_commitment.id::text || ':'
            || new.id::text || ':' || v_commitment.cycle::text,
          jsonb_build_object(
            'sales_invoice_id', new.id,
            'stock_movement_ids', to_jsonb(v_movement_ids)
          )
        );
      end loop;
    end loop;

    for v_need in
      update public.supply_needs need
      set supply_state = 'covered',
          version = need.version + 1,
          updated_by = auth.uid(),
          updated_at = clock_timestamp()
      where need.tenant_id = new.tenant_id
        and need.supply_state = 'committed'
        and exists (
          select 1 from public.workshop_inventory_commitments commitment
          where commitment.tenant_id = need.tenant_id
            and commitment.supply_need_id = need.id
            and commitment.state = 'consumed'
            and commitment.sales_invoice_id = new.id
        )
        and not exists (
          select 1 from public.workshop_inventory_commitments commitment
          where commitment.tenant_id = need.tenant_id
            and commitment.supply_need_id = need.id
            and commitment.state in ('active', 'consuming')
        )
      returning need.*
    loop
      insert into public.supply_need_events (
        tenant_id, supply_need_id, action, changed, actor_id, operation_key,
        request_snapshot, response_snapshot, occurred_at
      ) values (
        v_need.tenant_id, v_need.id, 'covered', true, auth.uid(),
        'workshop-invoice-covered:' || new.id::text || ':' || v_need.id::text,
        jsonb_build_object('sales_invoice_id', new.id),
        jsonb_build_object(
          'need_id', v_need.id,
          'changed', true,
          'version', v_need.version,
          'need', to_jsonb(v_need)
        ),
        clock_timestamp()
      ) on conflict (tenant_id, operation_key) do nothing;
    end loop;
  elsif not v_new_posted and v_old_posted then
    perform pg_advisory_xact_lock(hashtextextended(
      'online_inventory_reservation:' || new.tenant_id::text,
      0
    ));
    for v_commitment in
      update public.workshop_inventory_commitments commitment
      set state = 'active',
          cycle = commitment.cycle + 1,
          version = commitment.version + 1,
          assigned_at = clock_timestamp(),
          review_due_at = clock_timestamp() + interval '30 days',
          consumption_started_at = null,
          consumed_at = null,
          sales_invoice_id = null,
          stock_movement_ids = array[]::uuid[],
          updated_by = auth.uid(),
          updated_at = clock_timestamp()
      where commitment.tenant_id = new.tenant_id
        and commitment.sales_invoice_id = new.id
        and commitment.state = 'consumed'
      returning commitment.*
    loop
      perform public.append_workshop_inventory_commitment_event_v1(
        v_commitment, 'reactivated', 'consumed', 'active',
        'sales_invoice_reopened',
        'workshop-commitment-reactivated:' || v_commitment.id::text || ':'
          || new.id::text || ':' || v_commitment.cycle::text,
        jsonb_build_object('sales_invoice_id', new.id)
      );
    end loop;

    for v_need in
      update public.supply_needs need
      set supply_state = 'committed',
          version = need.version + 1,
          updated_by = auth.uid(),
          updated_at = clock_timestamp()
      where need.tenant_id = new.tenant_id
        and need.supply_state = 'covered'
        and exists (
          select 1 from public.workshop_inventory_commitments commitment
          where commitment.tenant_id = need.tenant_id
            and commitment.supply_need_id = need.id
            and commitment.state = 'active'
        )
      returning need.*
    loop
      insert into public.supply_need_events (
        tenant_id, supply_need_id, action, changed, actor_id, operation_key,
        request_snapshot, response_snapshot, occurred_at
      ) values (
        v_need.tenant_id, v_need.id, 'stock_reactivated', true, auth.uid(),
        'workshop-invoice-reactivated:' || new.id::text || ':' || v_need.id::text,
        jsonb_build_object('sales_invoice_id', new.id),
        jsonb_build_object(
          'need_id', v_need.id,
          'changed', true,
          'version', v_need.version,
          'need', to_jsonb(v_need)
        ),
        clock_timestamp()
      ) on conflict (tenant_id, operation_key) do nothing;
    end loop;
  end if;
  return new;
end;
$$;

revoke all on function public.finalize_workshop_commitment_consumption_v1()
  from public, anon, authenticated, service_role;

drop trigger if exists x_workshop_commitment_finalize
  on public.sales_invoices;
create trigger x_workshop_commitment_finalize
  after insert or update of status on public.sales_invoices
  for each row execute function public.finalize_workshop_commitment_consumption_v1();

-- Every physical consumer now protects the union of online and workshop
-- commitments. The established negative-stock policy remains unchanged when
-- that protected floor is zero.
create or replace function public.guard_product_reserved_inventory_balance()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_committed integer;
  v_online integer;
  v_workshop integer;
  v_new_stock integer;
begin
  select coalesce(sum(reservation.quantity), 0)::integer into v_online
  from public.online_order_inventory_reservations reservation
  where reservation.tenant_id = old.tenant_id
    and reservation.product_id = old.id
    and reservation.state = 'active'
    and reservation.expires_at > clock_timestamp();
  select coalesce(sum(commitment.quantity), 0)::integer into v_workshop
  from public.workshop_inventory_commitments commitment
  where commitment.tenant_id = old.tenant_id
    and commitment.product_id = old.id
    and commitment.state = 'active';
  v_committed := v_online + v_workshop;

  v_new_stock := least(
    coalesce(new.inventory_qty, 0),
    coalesce(new.stock_quantity, 0)
  );
  if v_committed > 0 and v_new_stock < v_committed then
    if v_workshop = 0 then
      -- Preserve the established online-only error contract byte-for-byte.
      raise exception
        'Stock update would consume % units reserved for online orders; available floor is %',
        v_online, v_online using errcode = '23514';
    end if;
    raise exception
      'La actualización consumiría unidades comprometidas; el piso protegido es %.',
      v_committed using errcode = '23514';
  end if;
  return new;
end;
$$;

revoke all on function public.guard_product_reserved_inventory_balance()
  from public, anon, authenticated, service_role;

create or replace function public.guard_reserved_product_classification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if row(
    old.track_stock, old.is_service, old.product_type,
    old.purchase_treatment, old.is_set
  ) is distinct from row(
    new.track_stock, new.is_service, new.product_type,
    new.purchase_treatment, new.is_set
  ) and (
    exists (
      select 1
      from public.online_order_inventory_reservations reservation
      join public.online_order_items item
        on item.id = reservation.order_item_id
       and item.tenant_id = reservation.tenant_id
      where reservation.tenant_id = old.tenant_id
        and reservation.state in ('active', 'consuming')
        and (
          reservation.state = 'consuming'
          or reservation.expires_at > clock_timestamp()
        )
        and (reservation.product_id = old.id or item.product_id = old.id)
    )
    or exists (
      select 1 from public.workshop_inventory_commitments commitment
      where commitment.tenant_id = old.tenant_id
        and commitment.state in ('active', 'consuming')
        and (
          commitment.product_id = old.id
          or commitment.source_product_id = old.id
        )
    )
  ) then
    raise exception
      'La clasificación del producto está bloqueada por un compromiso de inventario.'
      using errcode = '23514';
  end if;
  return new;
end;
$$;

revoke all on function public.guard_reserved_product_classification()
  from public, anon, authenticated, service_role;

create or replace function public.guard_reserved_product_set_components()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant_id uuid := coalesce(new.tenant_id, old.tenant_id);
  v_set_product_id uuid := coalesce(new.set_product_id, old.set_product_id);
begin
  if exists (
    select 1
    from public.online_order_inventory_reservations reservation
    join public.online_order_items item
      on item.id = reservation.order_item_id
     and item.tenant_id = reservation.tenant_id
    where reservation.tenant_id = v_tenant_id
      and item.product_id = v_set_product_id
      and reservation.state in ('active', 'consuming')
      and (
        reservation.state = 'consuming'
        or reservation.expires_at > clock_timestamp()
      )
  ) or exists (
    select 1 from public.workshop_inventory_commitments commitment
    where commitment.tenant_id = v_tenant_id
      and commitment.source_product_id = v_set_product_id
      and commitment.state in ('active', 'consuming')
  ) then
    raise exception
      'Los componentes del set están bloqueados por un compromiso de inventario.'
      using errcode = '23514';
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

revoke all on function public.guard_reserved_product_set_components()
  from public, anon, authenticated, service_role;

comment on table public.workshop_inventory_commitments is
  'Workshop stock commitments by physical product. They reduce common ATP but never move stock; only linked invoice posting consumes them.';
comment on view public.active_inventory_commitments_v1 is
  'Single active commitment projection for online checkout and workshop demand.';
comment on function public.inventory_available_quantity_v1(uuid, uuid) is
  'Common ATP authority: physical on-hand minus live online and active workshop commitments, with canonical set-component resolution.';
comment on function public.assign_supply_need_from_stock_v1(uuid, bigint, text) is
  'Atomic, replay-safe workshop assignment. Competes for the last unit under the same tenant lock as online checkout.';

notify pgrst, 'reload schema';

commit;
