-- Deployment status: DEPLOYED 2026-07-11.
begin;
create or replace function public.void_sales_credit_note(p_credit_note_id uuid,p_reason text,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_tenant uuid:=public.user_tenant_id();v_actor uuid:=auth.uid();v_note public.sales_credit_notes%rowtype;v_operation uuid:=gen_random_uuid();v_journal uuid:=gen_random_uuid();v_line record;
begin
 if v_actor is null or v_tenant is null then raise exception'Authenticated employee tenant is required';end if;if nullif(btrim(p_reason),'')is null or nullif(btrim(p_idempotency_key),'')is null then raise exception'Sales credit void reason and idempotency key are required';end if;
 select * into v_note from public.sales_credit_notes where id=p_credit_note_id and tenant_id=v_tenant for update;if not found then raise exception'Sales credit note not found';end if;
 if v_note.status='voided'then if v_note.void_idempotency_key=btrim(p_idempotency_key)then return jsonb_build_object('sales_credit_note_id',v_note.id,'operation_id',v_note.void_operation_id,'replayed',true);end if;raise exception'Sales credit note already voided';end if;
 if v_note.official_dte_status='issued'then raise exception'Issued tax credit notes require an official reversal document';end if;
 insert into public.inventory_accounting_operations(id,tenant_id,operation_key,source_channel,action,document_type,document_id,actor_id,executor,old_status,new_status,context)values(v_operation,v_tenant,format('sales_credit_void:%s:%s',p_credit_note_id,btrim(p_idempotency_key)),'sales_credit_note','void','sales_credit_note',p_credit_note_id,v_actor,'database_command','posted','voided',jsonb_build_object('reason',btrim(p_reason)));
 insert into public.journal_entries(id,tenant_id,entry_number,entry_date,description,type,source_module,source_reference,status,total_debit,total_credit,operation_id,source_document_type,source_document_id,created_by,reversal_of_id,created_at,updated_at)
 values(v_journal,v_tenant,public.get_next_document_number(v_tenant,'journal_entry'),now(),format('Anulación %s: %s',v_note.credit_note_number,btrim(p_reason)),'credit_note_void','sales_credit_notes',p_credit_note_id::text,'posted',v_note.total_amount+v_note.cost_amount,v_note.total_amount+v_note.cost_amount,v_operation,'sales_credit_note',p_credit_note_id,v_actor,v_note.journal_entry_id,now(),now());
 for v_line in select * from public.journal_lines where entry_id=v_note.journal_entry_id loop insert into public.journal_lines(id,tenant_id,entry_id,account_id,account_code,account_name,description,debit_amount,credit_amount,created_at,updated_at)values(gen_random_uuid(),v_tenant,v_journal,v_line.account_id,v_line.account_code,v_line.account_name,'Anulación '||v_note.credit_note_number,v_line.credit_amount,v_line.debit_amount,now(),now());end loop;
 update public.sales_credit_notes set status='voided',void_operation_id=v_operation,void_journal_entry_id=v_journal,void_idempotency_key=btrim(p_idempotency_key),voided_at=now(),voided_by=v_actor,void_reason=btrim(p_reason)where id=p_credit_note_id;
 perform public.recalculate_sales_invoice_settlement(v_note.sales_invoice_id);perform public.append_inventory_accounting_checkpoint(v_operation,'inventory_applied','completed','sales_credit_note',p_credit_note_id,jsonb_build_object('movement_count',0));perform public.append_inventory_accounting_checkpoint(v_operation,'journal_reversed','completed','journal_entry',v_journal,jsonb_build_object('reversal_of_id',v_note.journal_entry_id));perform public.append_inventory_accounting_checkpoint(v_operation,'invariants_verified','completed','sales_credit_note',p_credit_note_id,jsonb_build_object('balanced',true));update public.inventory_accounting_operations set outcome='completed',completed_at=now(),after_snapshot=jsonb_build_object('status','voided')where id=v_operation;perform public.append_inventory_accounting_checkpoint(v_operation,'completed','completed','sales_credit_note',p_credit_note_id,jsonb_build_object('status','voided'));
 return jsonb_build_object('sales_credit_note_id',p_credit_note_id,'operation_id',v_operation,'replayed',false);
end;$$;
create or replace function public.prevent_sales_return_void_with_credit()returns trigger language plpgsql set search_path=public as $$begin if new.document_type='sales_return'and new.action='void'and exists(select 1 from public.sales_return_lines returned join public.sales_credit_note_lines credited on credited.sales_return_line_id=returned.id join public.sales_credit_notes note on note.id=credited.sales_credit_note_id where returned.sales_return_id=new.document_id and note.status='posted')then raise exception'Void linked sales credit notes before voiding this sales return';end if;return new;end;$$;
drop trigger if exists trg_prevent_sales_return_void_with_credit on public.inventory_accounting_operations;create trigger trg_prevent_sales_return_void_with_credit before insert on public.inventory_accounting_operations for each row execute function public.prevent_sales_return_void_with_credit();
create or replace function public.prevent_sales_invoice_edit_with_credit()returns trigger language plpgsql set search_path=public as $$begin if exists(select 1 from public.sales_credit_notes where sales_invoice_id=old.id and status='posted')and(new.items is distinct from old.items or new.subtotal is distinct from old.subtotal or new.iva_amount is distinct from old.iva_amount or new.total is distinct from old.total or new.net_amount is distinct from old.net_amount or new.tax_treatment is distinct from old.tax_treatment)then raise exception'Void posted sales credit notes before editing invoice financial lines';end if;return new;end;$$;
drop trigger if exists trg_prevent_sales_invoice_edit_with_credit on public.sales_invoices;create trigger trg_prevent_sales_invoice_edit_with_credit before update on public.sales_invoices for each row execute function public.prevent_sales_invoice_edit_with_credit();
revoke all on function public.void_sales_credit_note(uuid,text,text)from public,anon;grant execute on function public.void_sales_credit_note(uuid,text,text)to authenticated;
commit;
