-- Deployment status: DEPLOYED to production xzdvtzdqjeyqxnkqprtf on 2026-07-10
-- Phase 2: tenant-scoped inventory/accounting operation trace and checkpoints.
-- Canonical mirror: supabase/sql/core_schema.sql

begin;

alter table public.sales_invoices
  add column if not exists source text;

do $$
begin
  alter table public.sales_invoices
    drop constraint if exists sales_invoices_source_check;
  alter table public.sales_invoices
    add constraint sales_invoices_source_check
    check (source in ('pos', 'quick_sale', 'manual_sale', 'ecommerce', 'mechanic_job'));
end $$;

-- INVENTORY AND ACCOUNTING TRACE KERNEL (PHASE 1)
-- Connects source-document actions, stock movements, adjustments, and journals.
-- Historical rows remain nullable and are classified separately by audit tools.
-- ============================================================================

create table if not exists inventory_accounting_operations (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references tenants(id) on delete cascade not null,
  operation_key text not null,
  source_channel text not null,
  action text not null,
  document_type text not null,
  document_id uuid not null,
  actor_id uuid references auth.users(id) on delete set null,
  executor text not null default 'database_trigger',
  old_status text,
  new_status text,
  before_snapshot jsonb,
  after_snapshot jsonb,
  context jsonb not null default '{}'::jsonb,
  outcome text not null default 'started'
    check (outcome in ('started', 'completed', 'failed', 'reversed', 'superseded')),
  error_code text,
  error_message text,
  started_at timestamp with time zone not null default clock_timestamp(),
  completed_at timestamp with time zone,
  created_at timestamp with time zone not null default clock_timestamp(),
  unique (tenant_id, id),
  unique (tenant_id, operation_key)
);

create table if not exists inventory_accounting_checkpoints (
  id bigint generated by default as identity primary key,
  tenant_id uuid references tenants(id) on delete cascade not null,
  operation_id uuid not null,
  phase text not null check (phase in (
    'accepted',
    'source_snapshotted',
    'inventory_planned',
    'inventory_applied',
    'movement_recorded',
    'accounting_planned',
    'journal_posted',
    'journal_reversed',
    'invariants_verified',
    'completed'
  )),
  outcome text not null default 'completed'
    check (outcome in ('started', 'completed', 'warning', 'failed')),
  entity_type text,
  entity_id uuid,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default clock_timestamp(),
  foreign key (tenant_id, operation_id)
    references inventory_accounting_operations(tenant_id, id) on delete restrict
);

create index if not exists idx_inventory_operations_tenant_created
  on inventory_accounting_operations(tenant_id, created_at desc);
create index if not exists idx_inventory_operations_document
  on inventory_accounting_operations(tenant_id, document_type, document_id, created_at desc);
create index if not exists idx_inventory_operations_actor
  on inventory_accounting_operations(actor_id, created_at desc);
create index if not exists idx_inventory_checkpoints_operation
  on inventory_accounting_checkpoints(operation_id, id);

alter table inventory_accounting_operations enable row level security;
alter table inventory_accounting_checkpoints enable row level security;

drop policy if exists inventory_accounting_operations_select
  on inventory_accounting_operations;
create policy inventory_accounting_operations_select
  on inventory_accounting_operations
  for select to authenticated
  using (tenant_id = public.user_tenant_id());

drop policy if exists inventory_accounting_checkpoints_select
  on inventory_accounting_checkpoints;
create policy inventory_accounting_checkpoints_select
  on inventory_accounting_checkpoints
  for select to authenticated
  using (tenant_id = public.user_tenant_id());

revoke all on inventory_accounting_operations from anon, authenticated;
revoke all on inventory_accounting_checkpoints from anon, authenticated;
grant select on inventory_accounting_operations to authenticated;
grant select on inventory_accounting_checkpoints to authenticated;

create or replace function public.prevent_inventory_checkpoint_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if current_setting('app.allow_inventory_trace_mutation', true) <> 'true' then
    raise exception 'Inventory/accounting checkpoints are append-only'
      using errcode = 'check_violation';
  end if;
  return case when TG_OP = 'DELETE' then OLD else NEW end;
end;
$$;

drop trigger if exists trg_inventory_checkpoints_immutable
  on inventory_accounting_checkpoints;
create trigger trg_inventory_checkpoints_immutable
  before update or delete on inventory_accounting_checkpoints
  for each row execute function public.prevent_inventory_checkpoint_mutation();

create or replace function public.inventory_trace_document_snapshot(p_row jsonb)
returns jsonb
language sql
immutable
set search_path = public
as $$
  select jsonb_strip_nulls(jsonb_build_object(
    'id', p_row->'id',
    'status', p_row->'status',
    'source', p_row->'source',
    'invoice_number', p_row->'invoice_number',
    'items', coalesce(p_row->'items', '[]'::jsonb),
    'subtotal', p_row->'subtotal',
    'net_amount', p_row->'net_amount',
    'tax', coalesce(p_row->'tax', p_row->'iva_amount'),
    'total', p_row->'total',
    'paid_amount', p_row->'paid_amount',
    'balance', p_row->'balance',
    'prepayment_model', p_row->'prepayment_model',
    'updated_at', p_row->'updated_at'
  ));
$$;

create or replace function public.append_inventory_accounting_checkpoint(
  p_operation_id uuid,
  p_phase text,
  p_outcome text default 'completed',
  p_entity_type text default null,
  p_entity_id uuid default null,
  p_payload jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_checkpoint_id bigint;
begin
  insert into inventory_accounting_checkpoints (
    tenant_id,
    operation_id,
    phase,
    outcome,
    entity_type,
    entity_id,
    payload
  )
  select
    operation.tenant_id,
    operation.id,
    p_phase,
    coalesce(p_outcome, 'completed'),
    p_entity_type,
    p_entity_id,
    coalesce(p_payload, '{}'::jsonb)
  from inventory_accounting_operations operation
  where operation.id = p_operation_id
  returning id into v_checkpoint_id;

  if v_checkpoint_id is null then
    raise exception 'Inventory/accounting operation % does not exist', p_operation_id
      using errcode = 'foreign_key_violation';
  end if;

  return v_checkpoint_id;
end;
$$;

revoke all on function public.append_inventory_accounting_checkpoint(
  uuid, text, text, text, uuid, jsonb
) from public, anon, authenticated;

create or replace function public.begin_invoice_inventory_accounting_trace()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old_row jsonb;
  v_new_row jsonb;
  v_effective_row jsonb;
  v_before_snapshot jsonb;
  v_after_snapshot jsonb;
  v_operation_id uuid;
  v_operation_key text;
  v_existing_operation text;
  v_tenant_id uuid;
  v_document_id uuid;
  v_document_type text;
  v_source_channel text;
begin
  v_existing_operation := nullif(
    current_setting('app.inventory_operation_id', true),
    ''
  );

  -- Nested invoice updates caused by payment recalculation or sync belong to
  -- the already-active operation and must not start a disconnected trace.
  if pg_trigger_depth() > 1 and v_existing_operation is not null then
    return case when TG_OP = 'DELETE' then OLD else NEW end;
  end if;

  if TG_OP = 'INSERT' then
    v_new_row := to_jsonb(NEW);
    v_effective_row := v_new_row;
  elsif TG_OP = 'UPDATE' then
    v_old_row := to_jsonb(OLD);
    v_new_row := to_jsonb(NEW);
    v_effective_row := v_new_row;
  else
    v_old_row := to_jsonb(OLD);
    v_effective_row := v_old_row;
  end if;

  v_tenant_id := nullif(v_effective_row->>'tenant_id', '')::uuid;
  v_document_id := nullif(v_effective_row->>'id', '')::uuid;

  if v_tenant_id is null or v_document_id is null then
    raise exception 'Inventory/accounting trace requires tenant_id and document id';
  end if;

  if TG_TABLE_NAME = 'sales_invoices' then
    v_document_type := 'sales_invoice';
    v_source_channel := coalesce(nullif(v_effective_row->>'source', ''), 'manual_sale');
  elsif TG_TABLE_NAME = 'purchase_invoices' then
    v_document_type := 'purchase_invoice';
    v_source_channel := 'purchase_invoice';
  else
    raise exception 'Unsupported trace source table: %', TG_TABLE_NAME;
  end if;

  v_before_snapshot := case
    when v_old_row is null then null
    else public.inventory_trace_document_snapshot(v_old_row)
  end;
  v_after_snapshot := case
    when v_new_row is null then null
    else public.inventory_trace_document_snapshot(v_new_row)
  end;

  v_operation_key := coalesce(
    nullif(current_setting('app.inventory_idempotency_key', true), ''),
    gen_random_uuid()::text
  );

  insert into inventory_accounting_operations (
    tenant_id,
    operation_key,
    source_channel,
    action,
    document_type,
    document_id,
    actor_id,
    executor,
    old_status,
    new_status,
    before_snapshot,
    after_snapshot,
    context
  ) values (
    v_tenant_id,
    format('%s:%s:%s:%s', v_document_type, v_document_id, lower(TG_OP), v_operation_key),
    v_source_channel,
    lower(TG_OP),
    v_document_type,
    v_document_id,
    auth.uid(),
    'database_trigger',
    v_old_row->>'status',
    v_new_row->>'status',
    v_before_snapshot,
    v_after_snapshot,
    jsonb_build_object(
      'table', TG_TABLE_SCHEMA || '.' || TG_TABLE_NAME,
      'trigger_depth', pg_trigger_depth(),
      'transaction_id', txid_current()::text,
      'before_hash', case when v_before_snapshot is null then null else md5(v_before_snapshot::text) end,
      'after_hash', case when v_after_snapshot is null then null else md5(v_after_snapshot::text) end
    )
  )
  returning id into v_operation_id;

  perform set_config('app.inventory_operation_id', v_operation_id::text, true);
  perform set_config('app.inventory_source_document_type', v_document_type, true);
  perform set_config('app.inventory_source_document_id', v_document_id::text, true);
  perform set_config('app.inventory_source_channel', v_source_channel, true);

  perform public.append_inventory_accounting_checkpoint(
    v_operation_id,
    'accepted',
    'started',
    v_document_type,
    v_document_id,
    jsonb_build_object(
      'action', lower(TG_OP),
      'old_status', v_old_row->>'status',
      'new_status', v_new_row->>'status'
    )
  );

  perform public.append_inventory_accounting_checkpoint(
    v_operation_id,
    'source_snapshotted',
    'completed',
    v_document_type,
    v_document_id,
    jsonb_build_object(
      'before', v_before_snapshot,
      'after', v_after_snapshot
    )
  );

  return case when TG_OP = 'DELETE' then OLD else NEW end;
end;
$$;

alter table stock_movements
  add column if not exists operation_id uuid,
  add column if not exists source_document_type text,
  add column if not exists source_document_id uuid,
  add column if not exists created_by uuid references auth.users(id),
  add column if not exists stock_before numeric(12,2),
  add column if not exists stock_after numeric(12,2),
  add column if not exists reversal_of_id uuid references stock_movements(id);

alter table stock_adjustments
  add column if not exists operation_id uuid,
  add column if not exists source_document_type text,
  add column if not exists source_document_id uuid;

alter table journal_entries
  add column if not exists operation_id uuid,
  add column if not exists source_document_type text,
  add column if not exists source_document_id uuid,
  add column if not exists created_by uuid references auth.users(id),
  add column if not exists reversal_of_id uuid references journal_entries(id);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'stock_movements_inventory_operation_fkey'
      and conrelid = 'public.stock_movements'::regclass
  ) then
    alter table stock_movements
      add constraint stock_movements_inventory_operation_fkey
      foreign key (tenant_id, operation_id)
      references inventory_accounting_operations(tenant_id, id) on delete restrict;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'stock_adjustments_inventory_operation_fkey'
      and conrelid = 'public.stock_adjustments'::regclass
  ) then
    alter table stock_adjustments
      add constraint stock_adjustments_inventory_operation_fkey
      foreign key (tenant_id, operation_id)
      references inventory_accounting_operations(tenant_id, id) on delete restrict;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'journal_entries_inventory_operation_fkey'
      and conrelid = 'public.journal_entries'::regclass
  ) then
    alter table journal_entries
      add constraint journal_entries_inventory_operation_fkey
      foreign key (tenant_id, operation_id)
      references inventory_accounting_operations(tenant_id, id) on delete restrict;
  end if;
end $$;

create index if not exists idx_stock_movements_operation
  on stock_movements(tenant_id, operation_id) where operation_id is not null;
create index if not exists idx_stock_movements_source_document
  on stock_movements(tenant_id, source_document_type, source_document_id)
  where source_document_id is not null;
create index if not exists idx_stock_adjustments_operation
  on stock_adjustments(tenant_id, operation_id) where operation_id is not null;
create index if not exists idx_journal_entries_operation
  on journal_entries(tenant_id, operation_id) where operation_id is not null;
create index if not exists idx_journal_entries_source_document
  on journal_entries(tenant_id, source_document_type, source_document_id)
  where source_document_id is not null;

create or replace function public.stamp_stock_movement_trace_context()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_operation_text text;
  v_document_text text;
  v_stock_after numeric(12,2);
  v_signed_delta numeric(12,2);
begin
  v_operation_text := nullif(current_setting('app.inventory_operation_id', true), '');
  if v_operation_text is null then
    return NEW;
  end if;

  v_document_text := nullif(current_setting('app.inventory_source_document_id', true), '');
  NEW.operation_id := coalesce(NEW.operation_id, v_operation_text::uuid);
  NEW.source_document_type := coalesce(
    NEW.source_document_type,
    nullif(current_setting('app.inventory_source_document_type', true), '')
  );
  NEW.source_document_id := coalesce(
    NEW.source_document_id,
    case when v_document_text is null then null else v_document_text::uuid end
  );
  NEW.created_by := coalesce(NEW.created_by, auth.uid());

  select coalesce(p.stock_quantity, p.inventory_qty, 0)::numeric(12,2)
    into v_stock_after
    from products p
   where p.id = NEW.product_id
     and p.tenant_id = NEW.tenant_id;

  v_signed_delta := case
    when NEW.type in ('OUT', 'TRANSFER_OUT') then -abs(NEW.quantity)
    when NEW.type in ('IN', 'TRANSFER_IN') then abs(NEW.quantity)
    else NEW.quantity
  end;

  NEW.stock_after := coalesce(NEW.stock_after, v_stock_after);
  NEW.stock_before := coalesce(NEW.stock_before, v_stock_after - v_signed_delta);
  return NEW;
end;
$$;

create or replace function public.stamp_document_trace_context()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_operation_text text;
  v_document_text text;
begin
  v_operation_text := nullif(current_setting('app.inventory_operation_id', true), '');
  if v_operation_text is null then
    return NEW;
  end if;

  v_document_text := nullif(current_setting('app.inventory_source_document_id', true), '');
  NEW.operation_id := coalesce(NEW.operation_id, v_operation_text::uuid);
  NEW.source_document_type := coalesce(
    NEW.source_document_type,
    nullif(current_setting('app.inventory_source_document_type', true), '')
  );
  NEW.source_document_id := coalesce(
    NEW.source_document_id,
    case when v_document_text is null then null else v_document_text::uuid end
  );
  NEW.created_by := coalesce(NEW.created_by, auth.uid());
  return NEW;
end;
$$;

drop trigger if exists trg_stock_movements_trace_context on stock_movements;
create trigger trg_stock_movements_trace_context
  before insert on stock_movements
  for each row execute function public.stamp_stock_movement_trace_context();

drop trigger if exists trg_stock_adjustments_trace_context on stock_adjustments;
create trigger trg_stock_adjustments_trace_context
  before insert on stock_adjustments
  for each row execute function public.stamp_document_trace_context();

drop trigger if exists trg_journal_entries_trace_context on journal_entries;
create trigger trg_journal_entries_trace_context
  before insert on journal_entries
  for each row execute function public.stamp_document_trace_context();

create or replace function public.checkpoint_stock_movement_trace()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if NEW.operation_id is null then
    return NEW;
  end if;

  perform public.append_inventory_accounting_checkpoint(
    NEW.operation_id,
    'inventory_applied',
    'completed',
    'product',
    NEW.product_id,
    jsonb_build_object(
      'stock_before', NEW.stock_before,
      'stock_after', NEW.stock_after,
      'movement_type', NEW.movement_type
    )
  );

  perform public.append_inventory_accounting_checkpoint(
    NEW.operation_id,
    'movement_recorded',
    'completed',
    'stock_movement',
    NEW.id,
    jsonb_build_object(
      'product_id', NEW.product_id,
      'type', NEW.type,
      'quantity', NEW.quantity,
      'stock_before', NEW.stock_before,
      'stock_after', NEW.stock_after,
      'reference', NEW.reference,
      'reversal_of_id', NEW.reversal_of_id
    )
  );
  return NEW;
end;
$$;

drop trigger if exists trg_stock_movements_trace_checkpoint on stock_movements;
create trigger trg_stock_movements_trace_checkpoint
  after insert on stock_movements
  for each row execute function public.checkpoint_stock_movement_trace();

create or replace function public.checkpoint_journal_entry_trace()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_operation_id uuid;
  v_original_operation_id uuid;
  v_context_operation_text text;
  v_payload jsonb;
begin
  if TG_OP = 'DELETE' then
    v_original_operation_id := OLD.operation_id;
    v_context_operation_text := nullif(
      current_setting('app.inventory_operation_id', true),
      ''
    );
    v_operation_id := coalesce(
      case
        when v_context_operation_text is null then null
        else v_context_operation_text::uuid
      end,
      v_original_operation_id
    );
  else
    v_operation_id := NEW.operation_id;
  end if;

  if v_operation_id is null then
    return case when TG_OP = 'DELETE' then OLD else NEW end;
  end if;

  v_payload := case
    when TG_OP = 'DELETE' then jsonb_build_object(
      'entry_number', OLD.entry_number,
      'source_module', OLD.source_module,
      'source_reference', OLD.source_reference,
      'total_debit', OLD.total_debit,
      'total_credit', OLD.total_credit,
      'reversed_journal_operation_id', v_original_operation_id,
      'deleted_snapshot', to_jsonb(OLD)
    )
    else jsonb_build_object(
      'entry_number', NEW.entry_number,
      'source_module', NEW.source_module,
      'source_reference', NEW.source_reference,
      'total_debit', NEW.total_debit,
      'total_credit', NEW.total_credit,
      'reversal_of_id', NEW.reversal_of_id
    )
  end;

  perform public.append_inventory_accounting_checkpoint(
    v_operation_id,
    case when TG_OP = 'DELETE' then 'journal_reversed' else 'journal_posted' end,
    'completed',
    'journal_entry',
    case when TG_OP = 'DELETE' then OLD.id else NEW.id end,
    v_payload
  );

  -- Preserve the backward link on the original posting as well as the forward
  -- link on the operation that caused the replacement.
  if TG_OP = 'DELETE'
     and v_original_operation_id is not null
     and v_original_operation_id is distinct from v_operation_id then
    perform public.append_inventory_accounting_checkpoint(
      v_original_operation_id,
      'journal_reversed',
      'completed',
      'journal_entry',
      OLD.id,
      jsonb_build_object(
        'entry_number', OLD.entry_number,
        'reversed_by_operation_id', v_operation_id
      )
    );
  end if;

  return case when TG_OP = 'DELETE' then OLD else NEW end;
end;
$$;

drop trigger if exists trg_journal_entries_trace_checkpoint_insert on journal_entries;
create trigger trg_journal_entries_trace_checkpoint_insert
  after insert on journal_entries
  for each row execute function public.checkpoint_journal_entry_trace();

drop trigger if exists trg_journal_entries_trace_checkpoint_delete on journal_entries;
create trigger trg_journal_entries_trace_checkpoint_delete
  after delete on journal_entries
  for each row execute function public.checkpoint_journal_entry_trace();

create or replace function public.complete_invoice_inventory_accounting_trace()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_operation_text text;
  v_operation_id uuid;
  v_tenant_id uuid;
  v_stock_column_drift integer := 0;
  v_movement_arithmetic_errors integer := 0;
  v_unbalanced_journals integer := 0;
begin
  if pg_trigger_depth() > 1 then
    return case when TG_OP = 'DELETE' then OLD else NEW end;
  end if;

  v_operation_text := nullif(current_setting('app.inventory_operation_id', true), '');
  if v_operation_text is null then
    return case when TG_OP = 'DELETE' then OLD else NEW end;
  end if;
  v_operation_id := v_operation_text::uuid;
  v_tenant_id := case when TG_OP = 'DELETE' then OLD.tenant_id else NEW.tenant_id end;

  select count(*)::integer
    into v_stock_column_drift
    from products p
   where p.tenant_id = v_tenant_id
     and p.id in (
       select sm.product_id
       from stock_movements sm
       where sm.operation_id = v_operation_id
     )
     and coalesce(p.inventory_qty, 0) <> coalesce(p.stock_quantity, 0);

  select count(*)::integer
    into v_movement_arithmetic_errors
    from stock_movements sm
   where sm.operation_id = v_operation_id
     and (
       sm.stock_before is null
       or sm.stock_after is null
       or round(
         sm.stock_before + case
           when sm.type in ('OUT', 'TRANSFER_OUT') then -abs(sm.quantity)
           when sm.type in ('IN', 'TRANSFER_IN') then abs(sm.quantity)
           else sm.quantity
         end,
         2
       ) <> round(sm.stock_after, 2)
     );

  select count(*)::integer
    into v_unbalanced_journals
    from (
      select je.id
      from journal_entries je
      left join journal_lines jl
        on jl.entry_id = je.id and jl.tenant_id = je.tenant_id
      where je.operation_id = v_operation_id
      group by je.id
      having round(coalesce(sum(jl.debit_amount), 0), 2)
          <> round(coalesce(sum(jl.credit_amount), 0), 2)
    ) broken;

  perform public.append_inventory_accounting_checkpoint(
    v_operation_id,
    'invariants_verified',
    case
      when v_stock_column_drift = 0
       and v_movement_arithmetic_errors = 0
       and v_unbalanced_journals = 0 then 'completed'
      else 'failed'
    end,
    null,
    null,
    jsonb_build_object(
      'stock_column_drift', v_stock_column_drift,
      'movement_arithmetic_errors', v_movement_arithmetic_errors,
      'unbalanced_journals', v_unbalanced_journals
    )
  );

  if v_stock_column_drift > 0
     or v_movement_arithmetic_errors > 0
     or v_unbalanced_journals > 0 then
    raise exception
      'Inventory/accounting invariants failed for operation % (stock drift %, movement errors %, unbalanced journals %)',
      v_operation_id,
      v_stock_column_drift,
      v_movement_arithmetic_errors,
      v_unbalanced_journals
      using errcode = 'check_violation';
  end if;

  update inventory_accounting_operations
     set outcome = 'completed',
         completed_at = clock_timestamp()
   where id = v_operation_id;

  perform public.append_inventory_accounting_checkpoint(
    v_operation_id,
    'completed',
    'completed',
    null,
    null,
    jsonb_build_object('trigger_operation', lower(TG_OP))
  );

  perform set_config('app.inventory_operation_id', '', true);
  perform set_config('app.inventory_source_document_type', '', true);
  perform set_config('app.inventory_source_document_id', '', true);
  perform set_config('app.inventory_source_channel', '', true);
  return case when TG_OP = 'DELETE' then OLD else NEW end;
exception
  when others then
    perform set_config('app.inventory_operation_id', '', true);
    perform set_config('app.inventory_source_document_type', '', true);
    perform set_config('app.inventory_source_document_id', '', true);
    perform set_config('app.inventory_source_channel', '', true);
    raise;
end;
$$;

drop trigger if exists zz_inventory_trace_begin_sales_invoice on sales_invoices;
create trigger zz_inventory_trace_begin_sales_invoice
  before insert or update or delete on sales_invoices
  for each row execute function public.begin_invoice_inventory_accounting_trace();

drop trigger if exists zzz_inventory_trace_complete_sales_invoice on sales_invoices;
create trigger zzz_inventory_trace_complete_sales_invoice
  after insert or update or delete on sales_invoices
  for each row execute function public.complete_invoice_inventory_accounting_trace();

drop trigger if exists zz_inventory_trace_begin_purchase_invoice on purchase_invoices;
create trigger zz_inventory_trace_begin_purchase_invoice
  before insert or update or delete on purchase_invoices
  for each row execute function public.begin_invoice_inventory_accounting_trace();

drop trigger if exists zzz_inventory_trace_complete_purchase_invoice on purchase_invoices;
create trigger zzz_inventory_trace_complete_purchase_invoice
  after insert or update or delete on purchase_invoices
  for each row execute function public.complete_invoice_inventory_accounting_trace();

comment on table inventory_accounting_operations is
  'One tenant-scoped trace root per inventory/accounting source-document action.';
comment on table inventory_accounting_checkpoints is
  'Append-only ordered checkpoints connecting source actions, stock movements, and accounting effects.';

drop view if exists public.inventory_accounting_operation_trace_view cascade;
create view public.inventory_accounting_operation_trace_view
with (security_invoker = on)
as
select
  operation.id as operation_id,
  operation.tenant_id,
  operation.operation_key,
  operation.source_channel,
  operation.action,
  operation.document_type,
  operation.document_id,
  operation.actor_id,
  operation.executor,
  operation.old_status,
  operation.new_status,
  operation.before_snapshot,
  operation.after_snapshot,
  operation.outcome,
  operation.error_code,
  operation.error_message,
  operation.started_at,
  operation.completed_at,
  operation.created_at,
  coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'id', checkpoint.id,
        'phase', checkpoint.phase,
        'outcome', checkpoint.outcome,
        'entity_type', checkpoint.entity_type,
        'entity_id', checkpoint.entity_id,
        'payload', checkpoint.payload,
        'created_at', checkpoint.created_at
      )
      order by checkpoint.id
    )
    from inventory_accounting_checkpoints checkpoint
    where checkpoint.operation_id = operation.id
  ), '[]'::jsonb) as checkpoints,
  coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'id', movement.id,
        'product_id', movement.product_id,
        'type', movement.type,
        'movement_type', movement.movement_type,
        'quantity', movement.quantity,
        'stock_before', movement.stock_before,
        'stock_after', movement.stock_after,
        'reference', movement.reference,
        'reversal_of_id', movement.reversal_of_id,
        'created_at', movement.created_at
      )
      order by movement.created_at, movement.id
    )
    from stock_movements movement
    where movement.operation_id = operation.id
  ), '[]'::jsonb) as stock_movements,
  coalesce((
    select jsonb_agg(
      to_jsonb(entry) || jsonb_build_object(
        'lines', coalesce((
          select jsonb_agg(to_jsonb(line) order by line.created_at, line.id)
          from journal_lines line
          where line.entry_id = entry.id
        ), '[]'::jsonb)
      )
      order by entry.created_at, entry.id
    )
    from journal_entries entry
    where entry.operation_id = operation.id
  ), '[]'::jsonb) as journal_entries
from inventory_accounting_operations operation;

grant select on public.inventory_accounting_operation_trace_view to authenticated;

drop view if exists public.inventory_accounting_inconsistencies_view cascade;
create view public.inventory_accounting_inconsistencies_view
with (security_invoker = on)
as
select
  operation.tenant_id,
  operation.id as operation_id,
  'operation_incomplete'::text as inconsistency_type,
  'high'::text as severity,
  operation.document_type as entity_type,
  operation.document_id as entity_id,
  'completed'::text as expected_value,
  operation.outcome::text as actual_value,
  operation.created_at as occurred_at
from inventory_accounting_operations operation
where operation.outcome = 'started'
  and operation.created_at < clock_timestamp() - interval '5 minutes'

union all

select
  movement.tenant_id,
  movement.operation_id,
  'movement_arithmetic'::text,
  'critical'::text,
  'stock_movement'::text,
  movement.id,
  round(
    movement.stock_before + case
      when movement.type in ('OUT', 'TRANSFER_OUT') then -abs(movement.quantity)
      when movement.type in ('IN', 'TRANSFER_IN') then abs(movement.quantity)
      else movement.quantity
    end,
    2
  )::text,
  movement.stock_after::text,
  movement.created_at
from stock_movements movement
where movement.operation_id is not null
  and (
    movement.stock_before is null
    or movement.stock_after is null
    or round(
      movement.stock_before + case
        when movement.type in ('OUT', 'TRANSFER_OUT') then -abs(movement.quantity)
        when movement.type in ('IN', 'TRANSFER_IN') then abs(movement.quantity)
        else movement.quantity
      end,
      2
    ) <> round(movement.stock_after, 2)
  )

union all

select
  product.tenant_id,
  null::uuid,
  'stock_column_drift'::text,
  'critical'::text,
  'product'::text,
  product.id,
  product.inventory_qty::text,
  product.stock_quantity::text,
  product.updated_at
from products product
where coalesce(product.track_stock, true)
  and coalesce(product.product_type, 'product') <> 'service'
  and coalesce(product.inventory_qty, 0) <> coalesce(product.stock_quantity, 0)

union all

select
  entry.tenant_id,
  entry.operation_id,
  'journal_unbalanced'::text,
  'critical'::text,
  'journal_entry'::text,
  entry.id,
  round(coalesce(sum(line.debit_amount), 0), 2)::text,
  round(coalesce(sum(line.credit_amount), 0), 2)::text,
  entry.created_at
from journal_entries entry
left join journal_lines line
  on line.entry_id = entry.id and line.tenant_id = entry.tenant_id
group by
  entry.tenant_id,
  entry.operation_id,
  entry.id,
  entry.created_at
having round(coalesce(sum(line.debit_amount), 0), 2)
    <> round(coalesce(sum(line.credit_amount), 0), 2);

grant select on public.inventory_accounting_inconsistencies_view to authenticated;

-- END INVENTORY AND ACCOUNTING TRACE KERNEL (PHASE 1)

drop view if exists stock_movements_view cascade;

-- Helper: safe lookup (avoids hard dependency when bootstrapping from scratch)
create or replace function public.get_mechanic_job_number(p_job_id uuid, p_tenant_id uuid)
returns text
language plpgsql
stable
set search_path = public
as $$
declare
  v_job_number text;
begin
  if p_job_id is null then
    return null;
  end if;

  if to_regclass('public.mechanic_jobs') is null then
    return null;
  end if;

  execute 'select job_number from public.mechanic_jobs where id = $1 and tenant_id = $2'
    into v_job_number
    using p_job_id, p_tenant_id;

  return v_job_number;
exception
  when others then
    return null;
end;
$$;

create view stock_movements_view as
with movement_documents as (
  select
    sm.id,
    sm.product_id,
    p.name as product_name,
    p.sku as product_sku,
    sm.date as transaction_date,
    sm.type,
    sm.movement_type as raw_movement_type,
    sm.reference,
    case
      when sm.type = 'OUT' then -abs(sm.quantity)
      when sm.type = 'IN' then abs(sm.quantity)
      else sm.quantity
    end as quantity,
    sm.notes,
    sm.created_by,
    sm.stock_before as persisted_stock_before,
    sm.stock_after as persisted_stock_after,
    sm.created_at,
    sm.tenant_id,
    case
      when sm.source_document_id is not null then sm.source_document_id
      when coalesce(sm.reference, '') ~ '^sales_invoice:[0-9a-fA-F-]{36}$'
        then split_part(sm.reference, ':', 2)::uuid
      when coalesce(sm.reference, '') ~ '^purchase_invoice:[0-9a-fA-F-]{36}$'
        then split_part(sm.reference, ':', 2)::uuid
      when coalesce(sm.reference, '') ~ '^mechanic_job:[0-9a-fA-F-]{36}$'
        then split_part(sm.reference, ':', 2)::uuid
      else null::uuid
    end as document_id,
    case
      when nullif(sm.source_document_type, '') is not null then sm.source_document_type
      when coalesce(sm.reference, '') like 'sales_invoice:%' then 'sales_invoice'
      when coalesce(sm.reference, '') like 'purchase_invoice:%' then 'purchase_invoice'
      when coalesce(sm.reference, '') like 'mechanic_job:%' then 'mechanic_job'
      else null::text
    end as document_type
  from stock_movements sm
  left join products p
    on nullif(sm.product_id::text, '')::uuid = p.id
   and sm.tenant_id = p.tenant_id
),
movements_with_resolution as (
  select
    md.id,
    md.product_id,
    md.product_name,
    md.product_sku,
    md.transaction_date,
    case
      when md.document_type = 'sales_invoice' then 'sale'
      when md.document_type = 'purchase_invoice' then 'purchase'
      when md.document_type = 'mechanic_job' then 'sale'
      when coalesce(md.raw_movement_type, '') in ('purchase', 'purchase_invoice', 'purchase_invoice_reversal', 'manual_purchase') then 'purchase'
      when coalesce(md.raw_movement_type, '') in ('sale', 'sales_invoice', 'sales_invoice_component', 'sales_invoice_reversal', 'manual_sale') then 'sale'
      when coalesce(md.raw_movement_type, '') in ('transfer', 'transfer_in', 'transfer_out') then 'transfer'
      when coalesce(md.raw_movement_type, '') in ('manual', 'correction', 'initial', 'damage', 'loss', 'found', 'import', 'adjustment', 'inventory_adjust', 'inventory_adjustment', 'count_gain', 'count_loss', 'theft', 'internal_use') then 'adjustment'
      else 'adjustment'
    end as movement_type,
    case
      when md.document_type = 'sales_invoice' and coalesce(md.raw_movement_type, '') = 'sales_invoice_reversal' then 'sales_invoice_reversal'
      when md.document_type = 'sales_invoice' then coalesce(si.source, 'sale')
      when md.document_type = 'purchase_invoice' and coalesce(md.raw_movement_type, '') = 'purchase_invoice_reversal' then 'purchase_invoice_reversal'
      when md.document_type = 'purchase_invoice' then 'purchase_invoice'
      when md.document_type = 'mechanic_job' then 'mechanic_job'
      when nullif(trim(coalesce(md.raw_movement_type, '')), '') is not null then md.raw_movement_type
      else 'manual'
    end as source,
    case
      when md.document_type in ('sales_invoice', 'purchase_invoice', 'mechanic_job') then md.document_id
      when sa.id is not null then sa.id
      else null::uuid
    end as reference_id,
    case
      when md.document_type = 'sales_invoice' then coalesce(nullif(si.invoice_number, ''), md.reference)
      when md.document_type = 'purchase_invoice' then coalesce(nullif(pi.invoice_number, ''), md.reference)
      when md.document_type = 'mechanic_job' then coalesce(
        nullif(public.get_mechanic_job_number(md.document_id, md.tenant_id), ''),
        md.reference
      )
      when sa.id is not null then coalesce(
        nullif(sa.reference, ''),
        nullif(trim(coalesce(md.reference, '')), ''),
        nullif(trim(coalesce(md.notes, '')), ''),
        null::text
      )
      when nullif(trim(coalesce(md.reference, '')), '') is not null then md.reference
      when nullif(trim(coalesce(md.notes, '')), '') is not null then md.notes
      else null::text
    end as reference_number,
    md.quantity,
    md.notes,
    md.persisted_stock_before,
    md.persisted_stock_after,
    sa.adjustment_origin,
    coalesce(md.created_by, sa.created_by) as created_by,
    md.created_at,
    md.tenant_id
  from movement_documents md
  left join sales_invoices si
    on md.document_type = 'sales_invoice'
   and md.document_id = si.id
   and md.tenant_id = si.tenant_id
  left join purchase_invoices pi
    on md.document_type = 'purchase_invoice'
   and md.document_id = pi.id
   and md.tenant_id = pi.tenant_id
  left join stock_adjustments sa
    on md.document_type is null
   and md.tenant_id = sa.tenant_id
   and md.product_id = sa.product_id
   and md.created_at = sa.created_at
   and md.quantity = sa.quantity
   and coalesce(md.raw_movement_type, '') = sa.adjustment_type
),
movements_with_running_stock as (
  select
    m.*,
    greatest(coalesce(p.stock_quantity, 0), coalesce(p.inventory_qty, 0)) as current_stock,
    greatest(coalesce(p.stock_quantity, 0), coalesce(p.inventory_qty, 0)) - coalesce(
      sum(m.quantity) over (
        partition by m.product_id, m.tenant_id
        order by m.transaction_date desc nulls last, m.created_at desc, m.id desc
        rows between unbounded preceding and 1 preceding
      ),
      0
    )::integer as calculated_stock_after
  from movements_with_resolution m
  left join products p
    on nullif(m.product_id::text, '')::uuid = p.id
   and m.tenant_id = p.tenant_id
)
select
  id,
  product_id,
  product_name,
  product_sku,
  transaction_date,
  movement_type,
  source,
  reference_id,
  reference_number,
  quantity,
  coalesce(persisted_stock_before, calculated_stock_after - quantity)::integer as stock_before,
  coalesce(persisted_stock_after, calculated_stock_after)::integer as stock_after,
  notes,
  adjustment_origin,
  created_by,
  created_at,
  tenant_id
from movements_with_running_stock;

alter view stock_movements_view set (security_invoker = on);

commit;
