-- Online inventory reservations are a commitment ledger, not a stock movement.
-- Physical stock changes exactly once through the existing sales-invoice posting
-- kernel. This migration prevents concurrent checkout/POS/manual adjustments from
-- consuming units already committed to an unpaid online order, then converts the
-- commitment to immutable consumption evidence only after invoice stock movements
-- exist in the same transaction.
--
-- Forward plan: additive tables/functions/triggers plus a wrapper around the
-- existing public catalog RPC. Existing physical stock and historical movements
-- are not rewritten.
-- Recovery: roll back callers/triggers while preserving reservation/event rows.
-- Do not drop the ledgers after production data exists.

begin;

create unique index if not exists uq_products_tenant_id_id
  on public.products(tenant_id, id);
create unique index if not exists uq_online_order_items_tenant_id_id
  on public.online_order_items(tenant_id, id);

create table if not exists public.online_order_inventory_reservations (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete restrict,
  order_id uuid not null,
  order_item_id uuid not null,
  product_id uuid not null,
  quantity integer not null check (quantity > 0),
  state text not null default 'active' check (
    state in ('active', 'consuming', 'consumed', 'released', 'expired')
  ),
  cycle integer not null default 1 check (cycle > 0),
  version bigint not null default 0 check (version >= 0),
  reserved_at timestamptz not null default clock_timestamp(),
  expires_at timestamptz not null,
  consumption_started_at timestamptz,
  consumed_at timestamptz,
  released_at timestamptz,
  expired_at timestamptz,
  release_reason text,
  sales_invoice_id uuid references public.sales_invoices(id) on delete restrict,
  stock_movement_ids uuid[] not null default array[]::uuid[],
  created_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default clock_timestamp(),
  unique (tenant_id, id),
  unique (tenant_id, order_item_id, product_id),
  foreign key (tenant_id, order_id)
    references public.online_orders(tenant_id, id) on delete restrict,
  foreign key (tenant_id, order_item_id)
    references public.online_order_items(tenant_id, id) on delete restrict,
  foreign key (tenant_id, product_id)
    references public.products(tenant_id, id) on delete restrict,
  check (expires_at > reserved_at),
  check (state <> 'consuming' or consumption_started_at is not null),
  check (state <> 'consumed' or consumed_at is not null),
  check (state <> 'released' or released_at is not null),
  check (state <> 'expired' or expired_at is not null)
);

create index if not exists idx_online_inventory_reservations_product_active
  on public.online_order_inventory_reservations(
    tenant_id, product_id, expires_at, order_id
  ) where state = 'active';
create index if not exists idx_online_inventory_reservations_order
  on public.online_order_inventory_reservations(
    tenant_id, order_id, state, product_id
  );
create index if not exists idx_online_inventory_reservations_expiry
  on public.online_order_inventory_reservations(expires_at, tenant_id, id)
  where state = 'active';
create index if not exists idx_online_inventory_reservations_invoice
  on public.online_order_inventory_reservations(tenant_id, sales_invoice_id)
  where sales_invoice_id is not null;

create table if not exists public.online_order_inventory_reservation_events (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete restrict,
  reservation_id uuid not null,
  order_id uuid not null,
  order_item_id uuid not null,
  product_id uuid not null,
  event_type text not null check (event_type in (
    'reserved', 're_reserved', 'consumption_started',
    'consumed', 'released', 'expired'
  )),
  from_state text,
  to_state text not null,
  quantity integer not null check (quantity > 0),
  cycle integer not null check (cycle > 0),
  actor_id uuid references auth.users(id) on delete set null,
  executor text not null,
  operation_key text not null,
  payload jsonb not null default '{}'::jsonb check (
    jsonb_typeof(payload) = 'object'
  ),
  occurred_at timestamptz not null default clock_timestamp(),
  unique (tenant_id, operation_key),
  foreign key (tenant_id, reservation_id)
    references public.online_order_inventory_reservations(tenant_id, id)
      on delete restrict,
  foreign key (tenant_id, order_id)
    references public.online_orders(tenant_id, id) on delete restrict,
  foreign key (tenant_id, order_item_id)
    references public.online_order_items(tenant_id, id) on delete restrict,
  foreign key (tenant_id, product_id)
    references public.products(tenant_id, id) on delete restrict
);

create index if not exists idx_online_inventory_reservation_events_order
  on public.online_order_inventory_reservation_events(
    tenant_id, order_id, occurred_at desc, id desc
  );
create index if not exists idx_online_inventory_reservation_events_reservation
  on public.online_order_inventory_reservation_events(reservation_id, id);

alter table public.online_order_inventory_reservations enable row level security;
alter table public.online_order_inventory_reservation_events enable row level security;

drop policy if exists online_inventory_reservations_select
  on public.online_order_inventory_reservations;
create policy online_inventory_reservations_select
  on public.online_order_inventory_reservations
  for select to authenticated
  using (tenant_id = public.user_tenant_id());

drop policy if exists online_inventory_reservation_events_select
  on public.online_order_inventory_reservation_events;
create policy online_inventory_reservation_events_select
  on public.online_order_inventory_reservation_events
  for select to authenticated
  using (tenant_id = public.user_tenant_id());

revoke all on public.online_order_inventory_reservations
  from public, anon, authenticated, service_role;
revoke all on public.online_order_inventory_reservation_events
  from public, anon, authenticated, service_role;
grant select on public.online_order_inventory_reservations to authenticated;
grant select on public.online_order_inventory_reservation_events to authenticated;

create or replace function public.prevent_online_inventory_reservation_event_mutation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  raise exception 'Online inventory reservation events are append-only'
    using errcode = '55000';
end;
$$;

revoke all on function public.prevent_online_inventory_reservation_event_mutation()
  from public, anon, authenticated, service_role;

drop trigger if exists trg_online_inventory_reservation_events_immutable
  on public.online_order_inventory_reservation_events;
create trigger trg_online_inventory_reservation_events_immutable
  before update or delete
  on public.online_order_inventory_reservation_events
  for each row execute function
    public.prevent_online_inventory_reservation_event_mutation();

create or replace function public.append_online_inventory_reservation_event(
  p_reservation public.online_order_inventory_reservations,
  p_event_type text,
  p_from_state text,
  p_to_state text,
  p_executor text,
  p_operation_key text,
  p_payload jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if p_reservation.id is null
     or nullif(btrim(coalesce(p_operation_key, '')), '') is null
     or nullif(btrim(coalesce(p_executor, '')), '') is null then
    raise exception 'Reservation event identity is required'
      using errcode = '22023';
  end if;

  insert into public.online_order_inventory_reservation_events (
    tenant_id, reservation_id, order_id, order_item_id, product_id,
    event_type, from_state, to_state, quantity, cycle, actor_id,
    executor, operation_key, payload
  ) values (
    p_reservation.tenant_id,
    p_reservation.id,
    p_reservation.order_id,
    p_reservation.order_item_id,
    p_reservation.product_id,
    p_event_type,
    p_from_state,
    p_to_state,
    p_reservation.quantity,
    p_reservation.cycle,
    auth.uid(),
    btrim(p_executor),
    btrim(p_operation_key),
    coalesce(p_payload, '{}'::jsonb)
  )
  on conflict (tenant_id, operation_key) do nothing
  returning id into v_id;

  if v_id is null then
    select event.id into v_id
      from public.online_order_inventory_reservation_events event
     where event.tenant_id = p_reservation.tenant_id
       and event.operation_key = btrim(p_operation_key)
       and event.reservation_id = p_reservation.id
       and event.event_type = p_event_type;
    if not found then
      raise exception 'Reservation event operation key conflicts with another event'
        using errcode = '23505';
    end if;
  end if;

  return v_id;
end;
$$;

revoke all on function public.append_online_inventory_reservation_event(
  public.online_order_inventory_reservations,
  text, text, text, text, text, jsonb
) from public, anon, authenticated, service_role;

create or replace function public.online_order_inventory_reservation_ttl(
  p_tenant_id uuid,
  p_payment_method text
)
returns interval
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_method text := lower(btrim(coalesce(p_payment_method, 'transfer')));
  v_key text;
  v_default_minutes integer;
  v_max_minutes integer;
  v_raw text;
  v_minutes integer;
begin
  if p_tenant_id is null then
    raise exception 'Reservation tenant is required' using errcode = '22023';
  end if;

  if v_method in ('mercadopago', 'mercado_pago') then
    v_key := 'online_order_reservation_minutes_mercadopago';
    v_default_minutes := 30;
    v_max_minutes := 60;
  else
    v_key := 'online_order_reservation_minutes_transfer';
    v_default_minutes := 1440;
    v_max_minutes := 10080;
  end if;

  select setting.value into v_raw
    from public.website_settings setting
   where setting.tenant_id = p_tenant_id
     and setting.key = v_key
   limit 1;

  v_minutes := case
    when btrim(coalesce(v_raw, '')) ~ '^[0-9]{1,5}$'
      then btrim(v_raw)::integer
    else v_default_minutes
  end;
  v_minutes := greatest(5, least(v_minutes, v_max_minutes));
  return make_interval(mins => v_minutes);
end;
$$;

revoke all on function public.online_order_inventory_reservation_ttl(uuid, text)
  from public, anon, authenticated, service_role;

create or replace function public.expire_online_order_inventory_reservations(
  p_tenant_id uuid default null,
  p_limit integer default 500
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reservation public.online_order_inventory_reservations%rowtype;
  v_expired integer := 0;
begin
  for v_reservation in
    select reservation.*
      from public.online_order_inventory_reservations reservation
     where reservation.state = 'active'
       and reservation.expires_at <= clock_timestamp()
       and (p_tenant_id is null or reservation.tenant_id = p_tenant_id)
     order by reservation.expires_at, reservation.id
     for update skip locked
     limit greatest(1, least(coalesce(p_limit, 500), 5000))
  loop
    update public.online_order_inventory_reservations reservation
       set state = 'expired',
           expired_at = clock_timestamp(),
           updated_at = clock_timestamp(),
           version = reservation.version + 1
     where reservation.id = v_reservation.id
       and reservation.tenant_id = v_reservation.tenant_id
       and reservation.state = 'active'
     returning reservation.* into v_reservation;

    if found then
      perform public.append_online_inventory_reservation_event(
        v_reservation,
        'expired',
        'active',
        'expired',
        case when p_tenant_id is null then 'system_cron' else 'database_rpc' end,
        'reservation-expire:' || v_reservation.id::text || ':'
          || v_reservation.cycle::text,
        jsonb_build_object('expires_at', v_reservation.expires_at)
      );
      v_expired := v_expired + 1;
    end if;
  end loop;

  return v_expired;
end;
$$;

revoke all on function public.expire_online_order_inventory_reservations(uuid, integer)
  from public, anon, authenticated, service_role;

create or replace function public.online_product_available_quantity(
  p_tenant_id uuid,
  p_product_id uuid
)
returns integer
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_product public.products%rowtype;
  v_available integer;
begin
  select product.* into v_product
    from public.products product
   where product.id = p_product_id
     and product.tenant_id = p_tenant_id;
  if not found then
    return 0;
  end if;

  if coalesce(v_product.is_service, false)
     or v_product.product_type = 'service'
     or not coalesce(v_product.track_stock, true) then
    return greatest(
      coalesce(v_product.stock_quantity, v_product.inventory_qty, 0),
      0
    );
  end if;

  if coalesce(v_product.is_set, false) then
    select min(greatest(floor(
      (
        coalesce(component.stock_quantity, component.inventory_qty, 0)
        - coalesce(reserved.quantity, 0)
      )::numeric / set_component.quantity_in_set
    ), 0))::integer
      into v_available
      from public.product_set_components set_component
      join public.products component
        on component.id = set_component.component_product_id
       and component.tenant_id = set_component.tenant_id
      left join lateral (
        select coalesce(sum(reservation.quantity), 0)::integer as quantity
          from public.online_order_inventory_reservations reservation
         where reservation.tenant_id = component.tenant_id
           and reservation.product_id = component.id
           and reservation.state = 'active'
           and reservation.expires_at > clock_timestamp()
      ) reserved on true
     where set_component.tenant_id = p_tenant_id
       and set_component.set_product_id = p_product_id;
    return greatest(coalesce(v_available, 0), 0);
  end if;

  select greatest(
    coalesce(v_product.stock_quantity, v_product.inventory_qty, 0)
      - coalesce(sum(reservation.quantity), 0),
    0
  )::integer
    into v_available
    from public.online_order_inventory_reservations reservation
   where reservation.tenant_id = p_tenant_id
     and reservation.product_id = p_product_id
     and reservation.state = 'active'
     and reservation.expires_at > clock_timestamp();

  return greatest(coalesce(v_available,
    coalesce(v_product.stock_quantity, v_product.inventory_qty, 0)), 0);
end;
$$;

revoke all on function public.online_product_available_quantity(uuid, uuid)
  from public, anon, authenticated, service_role;

create or replace function public.get_online_order_inventory_reservation_deadline(
  p_order_id uuid
)
returns timestamptz
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_tenant_id uuid;
  v_deadline timestamptz;
begin
  select orders.tenant_id into v_tenant_id
    from public.online_orders orders
   where orders.id = p_order_id;
  if not found then
    return null;
  end if;

  if coalesce(auth.role(), '') <> 'service_role'
     and (
       auth.uid() is null
       or public.user_tenant_id() is distinct from v_tenant_id
     ) then
    raise exception 'Order not found or access denied'
      using errcode = '42501';
  end if;

  select min(reservation.expires_at) into v_deadline
    from public.online_order_inventory_reservations reservation
   where reservation.tenant_id = v_tenant_id
     and reservation.order_id = p_order_id
     and reservation.state = 'active'
     and reservation.expires_at > clock_timestamp();

  return v_deadline;
end;
$$;

revoke all on function public.get_online_order_inventory_reservation_deadline(uuid)
  from public, anon, authenticated, service_role;
grant execute on function public.get_online_order_inventory_reservation_deadline(uuid)
  to authenticated, service_role;

create or replace function public.reserve_online_order_item_inventory(
  p_order_item_id uuid,
  p_executor text default 'database_rpc'
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item public.online_order_items%rowtype;
  v_order public.online_orders%rowtype;
  v_source public.products%rowtype;
  v_target record;
  v_target_product public.products%rowtype;
  v_reservation public.online_order_inventory_reservations%rowtype;
  v_existing public.online_order_inventory_reservations%rowtype;
  v_deadline timestamptz;
  v_reserved_other integer;
  v_physical integer;
  v_target_count integer := 0;
  v_was_existing boolean;
begin
  if p_order_item_id is null then
    raise exception 'Online order item is required' using errcode = '22023';
  end if;

  select item.* into v_item
    from public.online_order_items item
   where item.id = p_order_item_id;
  if not found then
    raise exception 'Online order item not found' using errcode = '23503';
  end if;

  select orders.* into v_order
    from public.online_orders orders
   where orders.id = v_item.order_id
     and orders.tenant_id = v_item.tenant_id
   for update;
  if not found then
    raise exception 'Online order item tenant mismatch' using errcode = '42501';
  end if;
  if v_order.status in ('cancelled', 'delivered') then
    raise exception 'Inventory cannot be reserved for terminal online order %',
      v_order.order_number using errcode = '23514';
  end if;

  select product.* into v_source
    from public.products product
   where product.id = v_item.product_id
     and product.tenant_id = v_item.tenant_id;
  if not found then
    raise exception 'Online order product is missing from its tenant'
      using errcode = '23503';
  end if;

  if coalesce(v_item.is_service, v_source.is_service, false)
     or coalesce(v_item.product_type, v_source.product_type) = 'service'
     or coalesce(v_item.purchase_treatment, v_source.purchase_treatment, 'inventory')
          = 'workshop_consumable'
     or not coalesce(v_source.track_stock, true) then
    return 0;
  end if;

  if v_item.quantity <= 0 or v_item.quantity <> trunc(v_item.quantity) then
    raise exception 'Tracked online order quantities must be whole units'
      using errcode = '23514';
  end if;

  -- A tenant-scoped advisory lock keeps differently ordered carts from
  -- deadlocking while product row locks serialize them with POS/adjustments.
  perform pg_advisory_xact_lock(hashtextextended(
    'online_inventory_reservation:' || v_item.tenant_id::text,
    0
  ));
  perform public.expire_online_order_inventory_reservations(
    v_item.tenant_id,
    5000
  );

  v_deadline := clock_timestamp()
    + public.online_order_inventory_reservation_ttl(
        v_item.tenant_id,
        v_order.payment_method
      );

  for v_target in
    select requirement.product_id, requirement.required_quantity
      from (
        select v_source.id as product_id,
               v_item.quantity::integer as required_quantity
         where not coalesce(v_source.is_set, false)
        union all
        select component.component_product_id,
               (v_item.quantity::integer * component.quantity_in_set)::integer
          from public.product_set_components component
         where component.tenant_id = v_item.tenant_id
           and component.set_product_id = v_source.id
           and coalesce(v_source.is_set, false)
      ) requirement
     order by requirement.product_id
  loop
    v_target_count := v_target_count + 1;

    select product.* into v_target_product
      from public.products product
     where product.id = v_target.product_id
       and product.tenant_id = v_item.tenant_id
     for update;
    if not found then
      raise exception 'Set component is missing from the online-order tenant'
        using errcode = '23503';
    end if;
    if coalesce(v_target_product.is_service, false)
       or v_target_product.product_type = 'service'
       or not coalesce(v_target_product.track_stock, true) then
      raise exception 'Tracked online set contains a non-stock component: %',
        v_target_product.name using errcode = '23514';
    end if;
    if coalesce(v_target_product.inventory_qty, 0)
       <> coalesce(v_target_product.stock_quantity, 0) then
      raise exception 'Product stock columns disagree; reservation blocked for %',
        v_target_product.name using errcode = '23514';
    end if;
    if v_target.required_quantity <= 0 then
      raise exception 'Online set contains an invalid component quantity'
        using errcode = '23514';
    end if;

    select reservation.* into v_existing
      from public.online_order_inventory_reservations reservation
     where reservation.tenant_id = v_item.tenant_id
       and reservation.order_item_id = v_item.id
       and reservation.product_id = v_target.product_id
     for update;
    v_was_existing := found;

    if v_was_existing
       and v_existing.state in ('consuming', 'consumed') then
      if v_existing.quantity <> v_target.required_quantity then
        raise exception 'Consumed reservation no longer matches its order item'
          using errcode = '23514';
      end if;
      continue;
    end if;
    if v_was_existing
       and v_existing.state = 'active'
       and v_existing.expires_at > clock_timestamp() then
      if v_existing.quantity <> v_target.required_quantity then
        raise exception 'Active reservation no longer matches its order item'
          using errcode = '23514';
      end if;
      continue;
    end if;

    select coalesce(sum(reservation.quantity), 0)::integer
      into v_reserved_other
      from public.online_order_inventory_reservations reservation
     where reservation.tenant_id = v_item.tenant_id
       and reservation.product_id = v_target.product_id
       and reservation.state = 'active'
       and reservation.expires_at > clock_timestamp()
       and (not v_was_existing or reservation.id <> v_existing.id);

    v_physical := coalesce(
      v_target_product.stock_quantity,
      v_target_product.inventory_qty,
      0
    );
    if v_physical - v_reserved_other < v_target.required_quantity then
      raise exception 'Insufficient available stock for product %',
        v_target_product.name using errcode = '23514';
    end if;

    if v_was_existing then
      if v_existing.state not in ('released', 'expired') then
        raise exception 'Reservation is not eligible for reactivation: %',
          v_existing.state using errcode = '23514';
      end if;
      update public.online_order_inventory_reservations reservation
         set quantity = v_target.required_quantity,
             state = 'active',
             cycle = reservation.cycle + 1,
             version = reservation.version + 1,
             reserved_at = clock_timestamp(),
             expires_at = v_deadline,
             consumption_started_at = null,
             consumed_at = null,
             released_at = null,
             expired_at = null,
             release_reason = null,
             sales_invoice_id = null,
             stock_movement_ids = array[]::uuid[],
             created_by = auth.uid(),
             updated_at = clock_timestamp()
       where reservation.id = v_existing.id
         and reservation.tenant_id = v_existing.tenant_id
       returning reservation.* into v_reservation;
    else
      insert into public.online_order_inventory_reservations (
        tenant_id, order_id, order_item_id, product_id, quantity,
        state, reserved_at, expires_at, created_by
      ) values (
        v_item.tenant_id,
        v_item.order_id,
        v_item.id,
        v_target.product_id,
        v_target.required_quantity,
        'active',
        clock_timestamp(),
        v_deadline,
        auth.uid()
      ) returning * into v_reservation;
    end if;

    perform public.append_online_inventory_reservation_event(
      v_reservation,
      case when v_was_existing then 're_reserved' else 'reserved' end,
      case when v_was_existing then v_existing.state else null end,
      'active',
      coalesce(nullif(btrim(p_executor), ''), 'database_rpc'),
      'reservation-reserve:' || v_reservation.id::text || ':'
        || v_reservation.cycle::text,
      jsonb_build_object(
        'source_product_id', v_source.id,
        'is_set_component', coalesce(v_source.is_set, false),
        'physical_stock', v_physical,
        'other_reserved_quantity', v_reserved_other,
        'expires_at', v_reservation.expires_at
      )
    );
  end loop;

  if coalesce(v_source.is_set, false) and v_target_count = 0 then
    raise exception 'Tracked online set has no component definition: %',
      v_source.name using errcode = '23514';
  end if;

  return v_target_count;
end;
$$;

revoke all on function public.reserve_online_order_item_inventory(uuid, text)
  from public, anon, authenticated, service_role;

create or replace function public.ensure_online_order_inventory_reservations(
  p_order_id uuid,
  p_executor text default 'database_rpc'
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.online_orders%rowtype;
  v_item public.online_order_items%rowtype;
  v_count integer;
begin
  select orders.* into v_order
    from public.online_orders orders
   where orders.id = p_order_id
   for update;
  if not found then
    raise exception 'Online order not found' using errcode = '23503';
  end if;
  if v_order.status in ('cancelled', 'delivered') then
    raise exception 'Terminal online order cannot reserve inventory'
      using errcode = '23514';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'online_inventory_reservation:' || v_order.tenant_id::text,
    0
  ));
  perform public.expire_online_order_inventory_reservations(
    v_order.tenant_id,
    5000
  );

  for v_item in
    select item.*
      from public.online_order_items item
     where item.tenant_id = v_order.tenant_id
       and item.order_id = v_order.id
     order by item.id
  loop
    perform public.reserve_online_order_item_inventory(
      v_item.id,
      coalesce(nullif(btrim(p_executor), ''), 'database_rpc')
    );
  end loop;

  select count(*)::integer into v_count
    from public.online_order_inventory_reservations reservation
   where reservation.tenant_id = v_order.tenant_id
     and reservation.order_id = v_order.id
     and reservation.state in ('active', 'consuming')
     and (
       reservation.state = 'consuming'
       or reservation.expires_at > clock_timestamp()
     );
  return v_count;
end;
$$;

revoke all on function public.ensure_online_order_inventory_reservations(uuid, text)
  from public, anon, authenticated, service_role;

create or replace function public.renew_online_order_inventory_reservations(
  p_order_id uuid
)
returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.online_orders%rowtype;
  v_reservation public.online_order_inventory_reservations%rowtype;
  v_deadline timestamptz;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Reservation renewal is service-role only'
      using errcode = '42501';
  end if;

  select orders.* into v_order
    from public.online_orders orders
   where orders.id = p_order_id
   for update;
  if not found then
    raise exception 'Online order not found' using errcode = '23503';
  end if;
  if v_order.status in ('cancelled', 'delivered')
     or v_order.payment_status in ('paid', 'refunded') then
    raise exception 'Order is not eligible for inventory reservation renewal'
      using errcode = '23514';
  end if;

  perform public.ensure_online_order_inventory_reservations(
    v_order.id,
    'payment_preference'
  );
  v_deadline := clock_timestamp()
    + public.online_order_inventory_reservation_ttl(
        v_order.tenant_id,
        v_order.payment_method
      );

  for v_reservation in
    update public.online_order_inventory_reservations reservation
       set expires_at = v_deadline,
           version = reservation.version + 1,
           updated_at = clock_timestamp()
     where reservation.tenant_id = v_order.tenant_id
       and reservation.order_id = v_order.id
       and reservation.state = 'active'
       and reservation.expires_at > clock_timestamp()
     returning reservation.*
  loop
    perform public.append_online_inventory_reservation_event(
      v_reservation,
      're_reserved',
      'active',
      'active',
      'payment_preference',
      'reservation-renew:' || v_reservation.id::text || ':'
        || v_reservation.version::text,
      jsonb_build_object('expires_at', v_reservation.expires_at)
    );
  end loop;

  if not exists (
    select 1
      from public.online_order_inventory_reservations reservation
     where reservation.tenant_id = v_order.tenant_id
       and reservation.order_id = v_order.id
       and reservation.state = 'active'
       and reservation.expires_at = v_deadline
  ) and exists (
    select 1
      from public.online_order_items item
      join public.products product
        on product.id = item.product_id
       and product.tenant_id = item.tenant_id
     where item.tenant_id = v_order.tenant_id
       and item.order_id = v_order.id
       and not coalesce(item.is_service, product.is_service, false)
       and coalesce(item.product_type, product.product_type) <> 'service'
       and coalesce(item.purchase_treatment, product.purchase_treatment, 'inventory')
             <> 'workshop_consumable'
       and coalesce(product.track_stock, true)
  ) then
    raise exception 'Tracked order has no active inventory reservation'
      using errcode = '23514';
  end if;

  return case
    when exists (
      select 1
        from public.online_order_inventory_reservations reservation
       where reservation.tenant_id = v_order.tenant_id
         and reservation.order_id = v_order.id
         and reservation.state = 'active'
    ) then v_deadline
    else null
  end;
end;
$$;

revoke all on function public.renew_online_order_inventory_reservations(uuid)
  from public, anon, authenticated, service_role;
grant execute on function public.renew_online_order_inventory_reservations(uuid)
  to service_role;

create or replace function public.reserve_online_order_item_after_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.reserve_online_order_item_inventory(
    new.id,
    case
      when current_setting('app.public_order_rpc_in_progress', true) = 'true'
        then 'public_checkout'
      else 'database_trigger'
    end
  );
  return new;
end;
$$;

revoke all on function public.reserve_online_order_item_after_insert()
  from public, anon, authenticated, service_role;

drop trigger if exists trg_reserve_online_order_item_after_insert
  on public.online_order_items;
create trigger trg_reserve_online_order_item_after_insert
  after insert on public.online_order_items
  for each row execute function public.reserve_online_order_item_after_insert();

create or replace function public.prepare_online_inventory_reservation_consumption()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_non_posted constant text[] := array[
    'draft', 'borrador', 'sent', 'enviado', 'enviada',
    'issued', 'emitido', 'emitida',
    'cancelled', 'cancelado', 'cancelada', 'anulado', 'anulada'
  ];
  v_old_posted boolean := false;
  v_new_posted boolean;
  v_context_order_id uuid;
  v_order_id uuid;
  v_reservation public.online_order_inventory_reservations%rowtype;
begin
  v_new_posted := not (
    lower(coalesce(new.status, 'draft')) = any(v_non_posted)
  );
  if tg_op = 'UPDATE' then
    v_old_posted := not (
      lower(coalesce(old.status, 'draft')) = any(v_non_posted)
    );
  end if;
  if not v_new_posted or v_old_posted then
    return new;
  end if;

  begin
    v_context_order_id := nullif(
      current_setting('app.online_order_id', true),
      ''
    )::uuid;
  exception when invalid_text_representation then
    v_context_order_id := null;
  end;

  select orders.id into v_order_id
    from public.online_orders orders
   where orders.tenant_id = new.tenant_id
     and (
       (v_context_order_id is not null and orders.id = v_context_order_id)
       or orders.sales_invoice_id = new.id
     )
   order by (orders.id = v_context_order_id) desc
   limit 1
   for update;
  if not found then
    return new;
  end if;

  perform public.ensure_online_order_inventory_reservations(
    v_order_id,
    'sales_invoice_posting'
  );

  for v_reservation in
    update public.online_order_inventory_reservations reservation
       set state = 'consuming',
           consumption_started_at = clock_timestamp(),
           -- During BEFORE INSERT the invoice row does not exist yet, so an
           -- immediate FK cannot point at NEW.id. AFTER finalization binds the
           -- same id once the invoice and its stock movements are durable.
           sales_invoice_id = case
             when tg_op = 'INSERT' then reservation.sales_invoice_id
             else new.id
           end,
           version = reservation.version + 1,
           updated_at = clock_timestamp()
     where reservation.order_id = v_order_id
       and reservation.tenant_id = new.tenant_id
       and reservation.state = 'active'
       and reservation.expires_at > clock_timestamp()
     returning reservation.*
  loop
    perform public.append_online_inventory_reservation_event(
      v_reservation,
      'consumption_started',
      'active',
      'consuming',
      'sales_invoice_posting',
      'reservation-consume-start:' || v_reservation.id::text || ':'
        || new.id::text || ':' || v_reservation.cycle::text,
      jsonb_build_object('sales_invoice_id', new.id)
    );
  end loop;

  perform set_config(
    'app.online_order_reservation_order_id',
    v_order_id::text,
    true
  );
  return new;
end;
$$;

revoke all on function public.prepare_online_inventory_reservation_consumption()
  from public, anon, authenticated, service_role;

drop trigger if exists a0_online_inventory_reservation_prepare
  on public.sales_invoices;
create trigger a0_online_inventory_reservation_prepare
  before insert or update of status on public.sales_invoices
  for each row execute function
    public.prepare_online_inventory_reservation_consumption();

create or replace function public.finalize_online_inventory_reservations_for_invoice(
  p_order_id uuid,
  p_invoice_id uuid,
  p_tenant_id uuid,
  p_allow_deferred boolean default false
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_group record;
  v_moved integer;
  v_movement_ids uuid[];
  v_reservation public.online_order_inventory_reservations%rowtype;
begin
  if p_order_id is null or p_invoice_id is null or p_tenant_id is null then
    raise exception 'Order, invoice, and tenant are required to finalize reservations'
      using errcode = '22004';
  end if;

  -- A paid Mercado Pago event may insert the posted invoice from inside the
  -- online-order trigger stack. In that nested path the legacy invoice trigger
  -- deliberately defers its stock write until process_online_order_internal()
  -- resumes. Do not turn that valid sequencing into a false reconciliation
  -- failure; the public processor calls this same kernel strictly immediately
  -- after the stock movement is written. A partial movement is never deferred.
  if p_allow_deferred
     and exists (
       select 1
         from public.online_order_inventory_reservations reservation
        where reservation.tenant_id = p_tenant_id
          and reservation.order_id = p_order_id
          and reservation.state = 'consuming'
          and (
            reservation.sales_invoice_id = p_invoice_id
            or reservation.sales_invoice_id is null
          )
     )
     and not exists (
       select 1
         from public.stock_movements movement
        where movement.tenant_id = p_tenant_id
          and movement.reference = 'sales_invoice:' || p_invoice_id::text
          and movement.quantity < 0
          and exists (
            select 1
              from public.online_order_inventory_reservations reservation
             where reservation.tenant_id = p_tenant_id
               and reservation.order_id = p_order_id
               and reservation.state = 'consuming'
               and reservation.product_id = movement.product_id
          )
     ) then
    return false;
  end if;

  for v_group in
    select reservation.product_id,
           sum(reservation.quantity)::integer as required_quantity,
           array_agg(reservation.id order by reservation.id) as reservation_ids
      from public.online_order_inventory_reservations reservation
     where reservation.tenant_id = p_tenant_id
       and reservation.order_id = p_order_id
       and reservation.state = 'consuming'
       and (
         reservation.sales_invoice_id = p_invoice_id
         or reservation.sales_invoice_id is null
       )
     group by reservation.product_id
     order by reservation.product_id
  loop
    select coalesce(-sum(movement.quantity), 0)::integer,
           coalesce(array_agg(movement.id order by movement.id), array[]::uuid[])
      into v_moved, v_movement_ids
      from public.stock_movements movement
     where movement.tenant_id = p_tenant_id
       and movement.product_id = v_group.product_id
       and movement.reference = 'sales_invoice:' || p_invoice_id::text
       and movement.quantity < 0;

    if v_moved <> v_group.required_quantity then
      raise exception
        'Invoice stock movement does not reconcile to reservation for product %: expected %, moved %',
        v_group.product_id,
        v_group.required_quantity,
        v_moved
        using errcode = '23514';
    end if;

    for v_reservation in
      update public.online_order_inventory_reservations reservation
         set state = 'consumed',
             consumed_at = clock_timestamp(),
             sales_invoice_id = p_invoice_id,
             stock_movement_ids = v_movement_ids,
             version = reservation.version + 1,
             updated_at = clock_timestamp()
       where reservation.id = any(v_group.reservation_ids)
         and reservation.tenant_id = p_tenant_id
         and reservation.state = 'consuming'
       returning reservation.*
    loop
      perform public.append_online_inventory_reservation_event(
        v_reservation,
        'consumed',
        'consuming',
        'consumed',
        'sales_invoice_posting',
        'reservation-consumed:' || v_reservation.id::text || ':'
          || p_invoice_id::text || ':' || v_reservation.cycle::text,
        jsonb_build_object(
          'sales_invoice_id', p_invoice_id,
          'stock_movement_ids', to_jsonb(v_movement_ids)
        )
      );
    end loop;
  end loop;

  return true;
end;
$$;

revoke all on function public.finalize_online_inventory_reservations_for_invoice(
  uuid, uuid, uuid, boolean
) from public, anon, authenticated, service_role;

create or replace function public.finalize_online_inventory_reservation_consumption()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_non_posted constant text[] := array[
    'draft', 'borrador', 'sent', 'enviado', 'enviada',
    'issued', 'emitido', 'emitida',
    'cancelled', 'cancelado', 'cancelada', 'anulado', 'anulada'
  ];
  v_old_posted boolean := false;
  v_new_posted boolean;
  v_order_id uuid;
begin
  v_new_posted := not (
    lower(coalesce(new.status, 'draft')) = any(v_non_posted)
  );
  if tg_op = 'UPDATE' then
    v_old_posted := not (
      lower(coalesce(old.status, 'draft')) = any(v_non_posted)
    );
  end if;
  if not v_new_posted or v_old_posted then
    return new;
  end if;

  begin
    v_order_id := nullif(
      current_setting('app.online_order_reservation_order_id', true),
      ''
    )::uuid;
  exception when invalid_text_representation then
    v_order_id := null;
  end;
  if v_order_id is null then
    select orders.id into v_order_id
      from public.online_orders orders
     where orders.tenant_id = new.tenant_id
       and orders.sales_invoice_id = new.id
     limit 1;
  end if;
  if v_order_id is null then
    return new;
  end if;

  perform public.finalize_online_inventory_reservations_for_invoice(
    v_order_id,
    new.id,
    new.tenant_id,
    tg_op = 'INSERT'
  );
  perform set_config('app.online_order_reservation_order_id', '', true);
  return new;
end;
$$;

revoke all on function public.finalize_online_inventory_reservation_consumption()
  from public, anon, authenticated, service_role;

drop trigger if exists y_online_inventory_reservation_finalize
  on public.sales_invoices;
create trigger y_online_inventory_reservation_finalize
  after insert or update of status on public.sales_invoices
  for each row execute function
    public.finalize_online_inventory_reservation_consumption();

create or replace function public.release_online_order_inventory_reservations(
  p_order_id uuid,
  p_reason text,
  p_executor text default 'database_rpc',
  p_operation_prefix text default 'reservation-release'
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.online_orders%rowtype;
  v_reservation public.online_order_inventory_reservations%rowtype;
  v_released integer := 0;
begin
  select orders.* into v_order
    from public.online_orders orders
   where orders.id = p_order_id
   for update;
  if not found then
    raise exception 'Online order not found' using errcode = '23503';
  end if;
  if nullif(btrim(coalesce(p_reason, '')), '') is null then
    raise exception 'Reservation release reason is required'
      using errcode = '22023';
  end if;

  for v_reservation in
    update public.online_order_inventory_reservations reservation
       set state = 'released',
           released_at = clock_timestamp(),
           release_reason = left(btrim(p_reason), 500),
           version = reservation.version + 1,
           updated_at = clock_timestamp()
     where reservation.tenant_id = v_order.tenant_id
       and reservation.order_id = v_order.id
       and reservation.state = 'active'
     returning reservation.*
  loop
    perform public.append_online_inventory_reservation_event(
      v_reservation,
      'released',
      'active',
      'released',
      coalesce(nullif(btrim(p_executor), ''), 'database_rpc'),
      coalesce(nullif(btrim(p_operation_prefix), ''), 'reservation-release')
        || ':' || v_reservation.id::text || ':' || v_reservation.cycle::text,
      jsonb_build_object('reason', left(btrim(p_reason), 500))
    );
    v_released := v_released + 1;
  end loop;
  return v_released;
end;
$$;

revoke all on function public.release_online_order_inventory_reservations(
  uuid, text, text, text
) from public, anon, authenticated, service_role;

create or replace function public.release_online_inventory_on_order_cancel()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.status is distinct from new.status and new.status = 'cancelled' then
    perform public.release_online_order_inventory_reservations(
      new.id,
      coalesce(
        nullif(btrim(coalesce(new.cancelled_reason, '')), ''),
        'Pedido online cancelado'
      ),
      'online_order_cancellation',
      'reservation-cancel:' || new.id::text
    );
  end if;
  return new;
end;
$$;

revoke all on function public.release_online_inventory_on_order_cancel()
  from public, anon, authenticated, service_role;

drop trigger if exists trg_release_online_inventory_on_order_cancel
  on public.online_orders;
create trigger trg_release_online_inventory_on_order_cancel
  after update of status on public.online_orders
  for each row execute function public.release_online_inventory_on_order_cancel();

create or replace function public.guard_product_reserved_inventory_balance()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reserved integer;
  v_new_stock integer;
begin
  select coalesce(sum(reservation.quantity), 0)::integer
    into v_reserved
    from public.online_order_inventory_reservations reservation
   where reservation.tenant_id = old.tenant_id
     and reservation.product_id = old.id
     and reservation.state = 'active'
     and reservation.expires_at > clock_timestamp();

  v_new_stock := least(
    coalesce(new.inventory_qty, 0),
    coalesce(new.stock_quantity, 0)
  );
  if v_reserved > 0 and v_new_stock < v_reserved then
    raise exception
      'Stock update would consume % units reserved for online orders; available floor is %',
      v_reserved,
      v_reserved
      using errcode = '23514';
  end if;
  return new;
end;
$$;

revoke all on function public.guard_product_reserved_inventory_balance()
  from public, anon, authenticated, service_role;

drop trigger if exists zz_guard_product_reserved_inventory_balance
  on public.products;
create trigger zz_guard_product_reserved_inventory_balance
  before update of inventory_qty, stock_quantity on public.products
  for each row execute function public.guard_product_reserved_inventory_balance();

create or replace function public.guard_reserved_product_classification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if row(
    old.track_stock,
    old.is_service,
    old.product_type,
    old.purchase_treatment,
    old.is_set
  ) is distinct from row(
    new.track_stock,
    new.is_service,
    new.product_type,
    new.purchase_treatment,
    new.is_set
  ) and exists (
    select 1
      from public.online_order_inventory_reservations reservation
      join public.online_order_items item
        on item.id = reservation.order_item_id
       and item.tenant_id = reservation.tenant_id
     where reservation.tenant_id = old.tenant_id
       and reservation.state in ('active', 'consuming')
       and (
         reservation.state = 'consuming'
         or reservation.expires_at > clock_timestamp()
       )
       and (reservation.product_id = old.id or item.product_id = old.id)
  ) then
    raise exception
      'Product inventory classification is locked by an active online reservation'
      using errcode = '23514';
  end if;
  return new;
end;
$$;

revoke all on function public.guard_reserved_product_classification()
  from public, anon, authenticated, service_role;

drop trigger if exists zz_guard_reserved_product_classification
  on public.products;
create trigger zz_guard_reserved_product_classification
  before update of track_stock, is_service, product_type,
    purchase_treatment, is_set on public.products
  for each row execute function public.guard_reserved_product_classification();

create or replace function public.guard_reserved_product_set_components()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant_id uuid := coalesce(new.tenant_id, old.tenant_id);
  v_set_product_id uuid := coalesce(new.set_product_id, old.set_product_id);
begin
  if exists (
    select 1
      from public.online_order_inventory_reservations reservation
      join public.online_order_items item
        on item.id = reservation.order_item_id
       and item.tenant_id = reservation.tenant_id
     where reservation.tenant_id = v_tenant_id
       and item.product_id = v_set_product_id
       and reservation.state in ('active', 'consuming')
       and (
         reservation.state = 'consuming'
         or reservation.expires_at > clock_timestamp()
       )
  ) then
    raise exception
      'Set components are locked by an active online reservation'
      using errcode = '23514';
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

revoke all on function public.guard_reserved_product_set_components()
  from public, anon, authenticated, service_role;

drop trigger if exists trg_guard_reserved_product_set_components
  on public.product_set_components;
create trigger trg_guard_reserved_product_set_components
  before insert or update or delete on public.product_set_components
  for each row execute function public.guard_reserved_product_set_components();

create or replace function public.process_online_order(p_order_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant_id uuid;
  v_invoice_id uuid;
  v_previous_context text := current_setting('app.online_order_id', true);
begin
  select tenant_id into v_tenant_id
    from public.online_orders
   where id = p_order_id;
  if not found then
    raise exception 'Order not found: %', p_order_id;
  end if;

  if auth.uid() is not null
     and v_tenant_id is distinct from public.user_tenant_id() then
    raise exception 'Order not found or access denied: %', p_order_id
      using errcode = '42501';
  end if;

  perform set_config('app.online_order_id', p_order_id::text, true);
  v_invoice_id := public.process_online_order_internal(p_order_id);
  perform public.finalize_online_inventory_reservations_for_invoice(
    p_order_id,
    v_invoice_id,
    v_tenant_id,
    false
  );
  perform set_config('app.online_order_id', coalesce(v_previous_context, ''), true);
  return v_invoice_id;
exception when others then
  perform set_config('app.online_order_id', coalesce(v_previous_context, ''), true);
  raise;
end;
$$;

revoke all on function public.process_online_order(uuid)
  from public, anon, authenticated, service_role;
grant execute on function public.process_online_order(uuid)
  to authenticated, service_role;

comment on function public.process_online_order(uuid) is
  'Tenant-safe online-order processor. It binds invoice posting to the order reservation context so physical stock consumption and reservation finalization commit or roll back together.';

-- Preserve the current search/ranking implementation under a private base
-- name and wrap it with reservation-aware availability and pagination.
do $$
begin
  if to_regprocedure(
    'public.get_public_products_without_inventory_reservations(uuid,uuid[],uuid[],text,text,text,boolean,text,integer,integer)'
  ) is null then
    if to_regprocedure(
      'public.get_public_products(uuid,uuid[],uuid[],text,text,text,boolean,text,integer,integer)'
    ) is null then
      raise exception 'Canonical public product RPC is missing';
    end if;
    alter function public.get_public_products(
      uuid, uuid[], uuid[], text, text, text, boolean, text, integer, integer
    ) rename to get_public_products_without_inventory_reservations;
  end if;
end $$;

revoke all on function public.get_public_products_without_inventory_reservations(
  uuid, uuid[], uuid[], text, text, text, boolean, text, integer, integer
) from public, anon, authenticated, service_role;

create or replace function public.get_public_products(
  p_tenant_id uuid,
  p_category_ids uuid[] default null,
  p_product_ids uuid[] default null,
  p_sku text default null,
  p_search_term text default null,
  p_product_type text default null,
  p_only_in_stock boolean default true,
  p_sort_by text default 'name',
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id uuid,
  tenant_id uuid,
  name text,
  sku text,
  barcode text,
  price numeric,
  cost numeric,
  inventory_qty integer,
  stock_quantity integer,
  image_url text,
  image_url_optimized text,
  image_urls text[],
  description text,
  website_description text,
  category text,
  category_id uuid,
  category_name text,
  brand_id uuid,
  brand text,
  model text,
  manufacturer text,
  manufacturer_sku text,
  gtin text,
  product_type text,
  track_stock boolean,
  is_active boolean,
  is_published boolean,
  show_on_website boolean,
  created_at timestamptz,
  updated_at timestamptz,
  total_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with policy as (
    select case lower(coalesce(
      nullif(btrim(coalesce((
        select setting.value
          from public.website_settings setting
         where setting.tenant_id = p_tenant_id
           and setting.key = 'product_visibility_stock_policy'
         limit 1
      ), '')), ''),
      case when p_only_in_stock then 'available_only' else 'all' end
    ))
      when 'all' then 'all'
      when 'both' then 'all'
      when 'out_of_stock_only' then 'out_of_stock_only'
      when 'out_of_stock' then 'out_of_stock_only'
      when 'sin_stock' then 'out_of_stock_only'
      else 'available_only'
    end as stock_policy
  ), base_rows as (
    select raw.*,
           case
             when raw.product_type = 'service'
               or not coalesce(raw.track_stock, true)
               then greatest(coalesce(raw.stock_quantity, raw.inventory_qty, 0), 0)
             else public.online_product_available_quantity(
               raw.tenant_id,
               raw.id
             )
           end as available_quantity
      from public.get_public_products_without_inventory_reservations(
        p_tenant_id,
        p_category_ids,
        p_product_ids,
        p_sku,
        p_search_term,
        p_product_type,
        false,
        p_sort_by,
        2147483647,
        0
      ) with ordinality as raw
  ), filtered as (
    select base.*
      from base_rows base
      cross join policy
     where policy.stock_policy = 'all'
        or base.product_type = 'service'
        or not coalesce(base.track_stock, true)
        or (
          policy.stock_policy = 'available_only'
          and base.available_quantity > 0
        )
        or (
          policy.stock_policy = 'out_of_stock_only'
          and base.available_quantity <= 0
        )
  ), paged as (
    select filtered.*,
           count(*) over() as filtered_total
      from filtered
     order by filtered.ordinality
     limit greatest(coalesce(p_limit, 20), 0)
     offset greatest(coalesce(p_offset, 0), 0)
  )
  select
    paged.id,
    paged.tenant_id,
    paged.name,
    paged.sku,
    paged.barcode,
    paged.price,
    paged.cost,
    case
      when paged.product_type = 'service'
        or not coalesce(paged.track_stock, true)
        then paged.inventory_qty
      else paged.available_quantity
    end as inventory_qty,
    case
      when paged.product_type = 'service'
        or not coalesce(paged.track_stock, true)
        then paged.stock_quantity
      else paged.available_quantity
    end as stock_quantity,
    paged.image_url,
    paged.image_url_optimized,
    paged.image_urls,
    paged.description,
    paged.website_description,
    paged.category,
    paged.category_id,
    paged.category_name,
    paged.brand_id,
    paged.brand,
    paged.model,
    paged.manufacturer,
    paged.manufacturer_sku,
    paged.gtin,
    paged.product_type,
    paged.track_stock,
    paged.is_active,
    paged.is_published,
    paged.show_on_website,
    paged.created_at,
    paged.updated_at,
    paged.filtered_total as total_count
  from paged
  order by paged.ordinality;
$$;

revoke all on function public.get_public_products(
  uuid, uuid[], uuid[], text, text, text, boolean, text, integer, integer
) from public, anon, authenticated, service_role;
grant execute on function public.get_public_products(
  uuid, uuid[], uuid[], text, text, text, boolean, text, integer, integer
) to anon, authenticated, service_role;

create or replace view public.online_inventory_availability_view
with (security_invoker = true) as
select
  product.tenant_id,
  product.id as product_id,
  product.name as product_name,
  product.sku,
  coalesce(product.stock_quantity, product.inventory_qty, 0)::integer
    as physical_quantity,
  coalesce(reserved.quantity, 0)::integer as active_reserved_quantity,
  public.online_product_available_quantity(product.tenant_id, product.id)
    as available_quantity,
  coalesce(product.track_stock, true) as track_stock,
  coalesce(product.is_set, false) as is_set,
  product.updated_at
from public.products product
left join lateral (
  select coalesce(sum(reservation.quantity), 0)::integer as quantity
    from public.online_order_inventory_reservations reservation
   where reservation.tenant_id = product.tenant_id
     and reservation.product_id = product.id
     and reservation.state = 'active'
     and reservation.expires_at > clock_timestamp()
) reserved on true;

revoke all on public.online_inventory_availability_view
  from public, anon, authenticated, service_role;
grant select on public.online_inventory_availability_view to authenticated;

comment on table public.online_order_inventory_reservations is
  'Current tenant-scoped online stock commitments. Rows do not change physical stock; active commitments become consumed only after matching invoice stock movements exist.';
comment on table public.online_order_inventory_reservation_events is
  'Append-only reservation lifecycle evidence with deterministic operation keys, actor/executor and cycle provenance.';
comment on function public.get_online_order_inventory_reservation_deadline(uuid) is
  'Authorized active reservation deadline for a payment preference. It becomes null after expiry, cancellation, or physical consumption.';
comment on function public.renew_online_order_inventory_reservations(uuid) is
  'Service-only payment-preference command that atomically revalidates or recreates an unpaid order reservation and returns its authoritative deadline.';
comment on function public.online_product_available_quantity(uuid, uuid) is
  'Physical quantity minus live online commitments. Sets resolve the minimum available component bundle; services and non-stock products are never invented as reservations.';

do $$
declare
  v_job_exists boolean;
begin
  if to_regclass('cron.job') is not null
     and to_regprocedure('cron.schedule(text,text,text)') is not null then
    -- Dynamic SQL keeps schema-only/local databases portable when a stale
    -- `cron` namespace exists but the pg_cron extension objects do not.
    execute
      'select exists (select 1 from cron.job where jobname = $1)'
      into v_job_exists
      using 'vinabike_online_inventory_reservation_expiry';
    if not v_job_exists then
      execute 'select cron.schedule($1, $2, $3)'
        using
          'vinabike_online_inventory_reservation_expiry',
          '*/5 * * * *',
          'select public.expire_online_order_inventory_reservations(null, 1000);';
    end if;
  end if;
end $$;

-- Existing active orders are backfilled oldest-first. A conflicting historical
-- commitment fails the migration instead of silently accepting over-allocation.
do $$
declare
  v_order record;
begin
  for v_order in
    select orders.id
      from public.online_orders orders
     where orders.status not in ('cancelled', 'delivered')
       and exists (
         select 1
           from public.online_order_items item
           join public.products product
             on product.id = item.product_id
            and product.tenant_id = item.tenant_id
          where item.tenant_id = orders.tenant_id
            and item.order_id = orders.id
            and not coalesce(item.is_service, product.is_service, false)
            and coalesce(item.product_type, product.product_type) <> 'service'
            and coalesce(
                  item.purchase_treatment,
                  product.purchase_treatment,
                  'inventory'
                ) <> 'workshop_consumable'
            and coalesce(product.track_stock, true)
       )
       and not exists (
         select 1
           from public.stock_movements movement
          where orders.sales_invoice_id is not null
            and movement.tenant_id = orders.tenant_id
            and movement.reference =
                  'sales_invoice:' || orders.sales_invoice_id::text
            and movement.quantity < 0
       )
     order by orders.tenant_id, orders.created_at, orders.id
  loop
    perform public.ensure_online_order_inventory_reservations(
      v_order.id,
      'migration_backfill'
    );
  end loop;
end $$;

do $$
begin
  if exists (
    select 1
      from public.online_order_inventory_reservations reservation
     where reservation.state = 'consuming'
  ) then
    raise exception 'Reservation migration left a consuming row outside invoice posting';
  end if;
end $$;

commit;
